### ISSUE TITLE
安卓手机 termux软件安装 登录出错

### ISSUE THREAD

**Issue by 1028332602** [tickstep/aliyunpan#1]
安卓手机软件termux安装(aliyunpan)之后和其他的BaiduPCS-Go一样 会出现网络连接错误，在这个地址：https://github.com/qjfoidnh/BaiduPCS-Go/issues/107  有人编译了一下解决了。
阿里网盘有安卓客户端，但还是用这样的方式去用阿里云盘，确实有点欠打。但这确实是个问题
![Screenshot_20210820_104222](https://user-images.githubusercontent.com/53212274/130171390-73ad6faf-5969-4cc1-84ed-845a92f55dc5.jpg)

**Comment by tickstep** [comment]
感谢反馈，我去看一下先

**Comment by tickstep** [comment]
> 安卓手机软件termux安装(aliyunpan)之后和其他的BaiduPCS-Go一样 会出现网络连接错误，在这个地址：[qjfoidnh/BaiduPCS-Go#107](https://github.com/qjfoidnh/BaiduPCS-Go/issues/107) 有人编译了一下解决了。
> 阿里网盘有安卓客户端，但还是用这样的方式去用阿里云盘，确实有点欠打。但这确实是个问题
> ![Screenshot_20210820_104222](https://user-images.githubusercontent.com/53212274/130171390-73ad6faf-5969-4cc1-84ed-845a92f55dc5.jpg)

v0.0.2 版本已经支持android

**Comment by 1028332602** [comment]
已经修复好了😁，是改了一下代理吗？
下载android-api那个根据自己手机的型号

**Comment by 1028332602** [comment]
![Uploading Screenshot_20210909_120057.jpg…]()

**Comment by tickstep** [comment]
> 已经修复好了😁，是改了一下代理吗？
> 下载android-api那个根据自己手机的型号

用了android NDK进行编译就可以了
