### ISSUE TITLE
挂载为Webdav

### ISSUE THREAD

**Issue by qinyuhang** [tickstep/aliyunpan#10]
请问一下后续有计划开发挂载到本地WebDAV的功能吗？谢谢。

**Comment by tickstep** [comment]
> 请问一下后续有计划开发挂载到本地WebDAV的功能吗？谢谢。

v0.0.7 版本已经支持webdav功能，欢迎下载使用。同时支持docker部署

**Comment by kwingart** [comment]
> 可以考虑下，这个看需要的人多不多把，得等阿里云盘稳定之后再搞了

这个挂载功能，目前的版本有了吗？看完readme，好像没发现。。。谢谢
