### ISSUE TITLE
同步文件夹时可以不自动在文件夹内生成.adrive文件夹吗

### ISSUE THREAD

**Issue by crh251** [tickstep/aliyunpan#100]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/26644609/172974818-161b4fba-d64c-4add-980c-e3012abe7f35.png">

**Comment by xiaoyaofenfen** [comment]
下个版本会增加新备份功能sync。可以解决你这个问题

**Comment by tickstep** [comment]
使用v0.1.6 版本的sync命令可以解决
