### ISSUE TITLE
服务器带宽小，有没有对上传限速的方法

### ISSUE THREAD

**Issue by sw586** [tickstep/aliyunpan#101]
软件太好了感谢作者，不过服务器带宽小于是有了这个贪婪的想法

**Comment by tickstep** [comment]
有的，config可以配置，结合并发和限速应该可以达到你想要的效果
 max_download_parallel  1                                1 ~ 20               最大下载并发量，即同时下载文件最大数量                                         
  max_upload_parallel    2                                1 ~ 20               最大上传并发量，即同时上传文件最大数量                                         
  max_download_rate      100.00KB/s                                            限制单个文件最大下载速度, 0代表不限制                                          
  max_upload_rate        100.00KB/s                                            限制单个文件最大上传速度, 0代表不限制  

例如，配置单个文件上传限速为100KB/s，可以这样配置：
config set -max_upload_rate 100KB
