### ISSUE TITLE
sync的sync模式问题

### ISSUE THREAD

**Issue by dltianzheng** [tickstep/aliyunpan#111]
断网后，会出现删除文件的问题。#109之前碰到过删除文件，问题必现☹️，希望能解决下。
另外希望能增加同步Windows硬链接文件夹的需求 ，。

**Comment by tickstep** [comment]
> 断网后，会出现删除文件的问题。#109之前碰到过删除文件，问题必现☹️，希望能解决下。
> 另外希望能增加同步Windows硬链接文件夹的需求 ，。

这个详细步骤能描述下么？

**Comment by dltianzheng** [comment]
通过winsm开启任务,然后在执行过程中断网,之后就会删除同步文件夹中的文件

**Comment by dltianzheng** [comment]
> > 断网后，会出现删除文件的问题。#109之前碰到过删除文件，问题必现☹️，希望能解决下。
> > 另外希望能增加同步Windows硬链接文件夹的需求 ，。
> 
> 这个详细步骤能描述下么？



> > 断网后，会出现删除文件的问题。#109之前碰到过删除文件，问题必现☹️，希望能解决下。
> > 另外希望能增加同步Windows硬链接文件夹的需求 ，。
> 
> 这个详细步骤能描述下么？


通过winsm开启任务,然后在执行过程中断网,之后就会删除同步文件夹中的文件

**Comment by tickstep** [comment]
v0.1.8 已修复网络问题，你可以试试。
软链接暂时还没有，后续会考虑集成。
