### ISSUE TITLE
同步备份的问题（bug？）

### ISSUE THREAD

**Issue by mxk736850509** [tickstep/aliyunpan#112]
同步b站录播姬的工作目录，生成录播flv文件  大小几个GB
阿里云盘上出现了该文件，但大小才几十MB
但服务器上传一直没停

系统:腾讯云的ubuntu20.04
b站录播姬:https://github.com/BililiveRecorder/BililiveRecorder

**Comment by xiaoyaofenfen** [comment]
同步备份功能当前还是beta版，确实可能有bug。
你这边用的那种模式？如果是upload模式，基本功能应该是没问题的，我自己用了差不多半个月了，备份一直都OK，不过我这边主要是小文件。
你这边能否提供多点信息，例如debug日志，例如你具体场景和使用流程是怎么样的。现在这些信息无法判断问题

**Comment by xiaoyaofenfen** [comment]
初步判断是流文件一直被修改，导致上传无效导致。当前已经增加了相关的检测去避免该问题，下个版本合入
