### ISSUE TITLE
Sync的refreshToken过期情况

### ISSUE THREAD

**Issue by lxy85034** [tickstep/aliyunpan#117]
在使用docker的aliyunpan-sync时遇到了refreshToken过期的情况，请问是docker的aliyunpan-sync没有更新refreshToken的功能项吗。如果需要延长refreshToken的有效期，是需要再安装完整的CLI来手动刷新吗

**Comment by tickstep** [comment]
> 在使用docker的aliyunpan-sync时遇到了refreshToken过期的情况，请问是docker的aliyunpan-sync没有更新refreshToken的功能项吗。如果需要延长refreshToken的有效期，是需要再安装完整的CLI来手动刷新吗

每一个半小时更新一次，理论上不会过期的，我有一个docker跑了两个星期都没过期。你有没有其他操作，例如频繁重启容器这种。

**Comment by lxy85034** [comment]
在上个月30号的时候启动了sync的容器，那个时候是17版本，是能用的。今天我上去看的时候发现不同步了，重启容器报登录失败。这段时间没有进行过操作，也没有登录过阿里云盘。今天更新了镜像重启容器看下之后会不会复现

**Comment by tickstep** [comment]
> 在上个月30号的时候启动了sync的容器，那个时候是17版本，是能用的。今天我上去看的时候发现不同步了，重启容器报登录失败。这段时间没有进行过操作，也没有登录过阿里云盘。今天更新了镜像重启容器看下之后会不会复现

v0.2.2版本有做修正，你可以试试这个版本
