### ISSUE TITLE
aliyunpan sync start -ldir "我的同步" -pdir "/我的同步" -mode "sync" 会在本地生成 .\我的同步\我的同步\我的同步

### ISSUE THREAD

**Issue by xiaogongqin** [tickstep/aliyunpan#119]
云端空文件夹 \我的同步
aliyunpan sync start -ldir "我的同步" -pdir "/我的同步" -mode "sync" 会在本地当前路径下生成 .\我的同步\我的同步\我的同步

**Comment by tickstep** [comment]
ldir用绝对距离试试

**Comment by xiaogongqin** [comment]
绝对路径正常，只是相对路径有问题，测试环境win10-x64
