### ISSUE TITLE
能否添加打包上传的选项且CPU占用有点大（可能是我服务器不行）

### ISSUE THREAD

**Issue by Da-Hua** [tickstep/aliyunpan#125]

**Comment by Da-Hua** [comment]
甲骨云amd的机器  1核  我用的是您的docker镜像  只用来将数据上传到网盘

**Comment by tickstep** [comment]
> 甲骨云amd的机器  1核  我用的是您的docker镜像  只用来将数据上传到网盘

cpu是在10%左右？

**Comment by Da-Hua** [comment]
32-97%不等

**Comment by tickstep** [comment]
> 32-97%不等

如果是首次备份确实会大点，后面都是增加备份了，不应该这么高(~_~;)
﻿
你用的是哪个版本，发一下版本号？
开下debug日志，看一下看是不是有出错

**Comment by Da-Hua** [comment]
版本是v0.1.8 日志的话目测没有报错的地方

**Comment by Da-Hua** [comment]
我换成了v0.1.8-arm64 现在稳定了 最高在2-3%

**Comment by tickstep** [comment]
> 我换成了v0.1.8-arm64 现在稳定了 最高在2-3%

这个就是正常状态了，后面如果能复现，记得开下debug日志，看能不能定位到问题

**Comment by Da-Hua** [comment]
我又尝试了一下  我amd内核的机器 用v0.1.8-arm64是正常的 用v0.1.8-amd64 cpu使用率就飙起来了
我另一台arm的正好相反 用v0.1.8-arm64飙起来 用v0.1.8-amd64就正常

**Comment by xiaoyaofenfen** [comment]
> 我又尝试了一下 我amd内核的机器 用v0.1.8-arm64是正常的 用v0.1.8-amd64 cpu使用率就飙起来了 我另一台arm的正好相反 用v0.1.8-arm64飙起来 用v0.1.8-amd64就正常

有点疑问，arm64和amd64二进制不兼容的，在amd64内核的机器，你是怎么运行arm64版本的？用的模拟器么？
开一下debug日志看看，CPU飙升的时候，aliyunpan工具在做啥的。native运行我感觉应该不会有这么高的CPU使用率才对。

**Comment by xiaoyaofenfen** [comment]
> > 我又尝试了一下 我amd内核的机器 用v0.1.8-arm64是正常的 用v0.1.8-amd64 cpu使用率就飙起来了 我另一台arm的正好相反 用v0.1.8-arm64飙起来 用v0.1.8-amd64就正常
> 
> 有点疑问，arm64和amd64二进制不兼容的，在amd64内核的机器，你是怎么运行arm64版本的？用的模拟器么？ 开一下debug日志看看，CPU飙升的时候，aliyunpan工具在做啥的。native运行我感觉应该不会有这么高的CPU使用率才对。

在docker-compose.yml文件增加以下环境变量可以开启debug日志
    environment:
      - ALIYUNPAN_VERBOSE=1

**Comment by Da-Hua** [comment]
services:
  sync:
    image: tickstep/aliyunpan-sync:v0.1.8-amd64
    container_name: aDriveSync
    restart: always
    volumes:
      - /root/data:/home/app/data:rw
    environment:
      - TZ=Asia/Shanghai
      - ALIYUNPAN_REFRESH_TOKEN=*
      - ALIYUNPAN_TRANSFER_URL_TYPE=1
      - ALIYUNPAN_DOWNLOAD_PARALLEL=2
      - ALIYUNPAN_UPLOAD_PARALLEL=2
      - ALIYUNPAN_DOWNLOAD_BLOCK_SIZE=1024
      - ALIYUNPAN_UPLOAD_BLOCK_SIZE=1024
      - ALIYUNPAN_PAN_DIR=/
      - ALIYUNPAN_SYNC_MODE=upload
      - ALIYUNPAN_VERBOSE=1


这个是我在amd机器上的docker-compose文件

**Comment by tickstep** [comment]
你用新版本试试，旧版本之前有bug，会概率重复上传已上传的文件，导致做了无用功，浪费系统资源。

**Comment by Da-Hua** [comment]
最新版本 没有问题 感谢大佬

**Comment by Da-Hua** [comment]
emmmmmmmmm
![image](https://user-images.githubusercontent.com/58766472/194330114-69c8874f-c687-4477-91c0-a7161d17ee9a.png)
