### ISSUE TITLE
使用配置文件启动同步备份服务，修改其中一个文件夹名字会在网盘把整个同步目录清空

### ISSUE THREAD

**Issue by tangkuili** [tickstep/aliyunpan#129]
centos7.9系统，使用配置文件启动同步备份服务，有三个目录都是上传模式。
文件全部同步完成后，修改其中一个同步目录中的文件夹名字会在网盘把整个同步目录清空。然后重新上传整个同步目录。导致硬盘读取大量占用。

**Comment by tickstep** [comment]
确实是这样，当前无法区分新增目录和重名命目录的，所以都是当做新目录开上传了

**Comment by tangkuili** [comment]
搞错了现在没问题了，当时配置文件不知道怎么被改掉了，然后就一个目录在重新同步，同时把网盘整个同步目录删除了。
