### ISSUE TITLE
下载文件夹的时候,里面的文件会新建一个文件夹,这种情况算bug吗?

### ISSUE THREAD

**Issue by meislzhua** [tickstep/aliyunpan#130]
![image](https://user-images.githubusercontent.com/8063591/183296471-7926d6bb-9288-4ad5-9ed9-df52afc8cde2.png)
执行命令:  aliyunpan d -p 20 --save  /py_ml 
当我下载指定文件夹的时候,会用一个文件夹包裹我非文件夹的文件
原始目录:
![image](https://user-images.githubusercontent.com/8063591/183296549-4bd86dde-eadf-44aa-b839-2e8bd4dccedd.png)

**Comment by tickstep** [comment]
这个应该文件类型识别错了，把文件当作文件夹了。你帮忙开debug日志贴一下，看为什么会这样

**Comment by xiaoyaofenfen** [comment]
确实是bug的，指定下载路径有问题，下个版本会修复

**Comment by antecede** [comment]
> 确实是bug的，指定下载路径有问题，下个版本会修复
v0.1.9仍然未修复 @xiaoyaofenfen
