### ISSUE TITLE
sync模式下CPU长时间满载

### ISSUE THREAD

**Issue by xiaojueshi** [tickstep/aliyunpan#132]
设备： X86 阿里云1核

情况：使用二进制文件nohup后台运行syncCPU会满负荷，在同步完成后依旧保持CPU100%满负荷，查看系统进程aliyunpan占用100%，使用kill杀死后台进程后，aliyunpan依旧会满载CPU，直到重启服务器，本人因菜的一批的原因，未找到原因

**Comment by ZaneYork** [comment]
用screen启动可破，主要原因是这个程序会等待从标准输入读取字符来判断是否要关闭，nohup或者其它后台启动方案都会把标准输入立即返回空，结果就是个死循环。另附systemd的service模式下的修复方案：
```
[Unit]
Requires=network-online.target
After=network-online.target
 
[Service]
SyslogIdentifier=sync_video.service
Type=simple
ExecStart=/home/zane/docker/aliyun/sync.sh
Restart=always
StandardInput=tty
StandardOutput=tty
StandardError=null
TTYPath=/dev/tty12
 
[Install]
WantedBy=multi-user.target
```

**Comment by xiaoyaofenfen** [comment]
> 用screen启动可破，主要原因是这个程序会等待从标准输入读取字符来判断是否要关闭，nohup或者其它后台启动方案都会把标准输入立即返回空，结果就是个死循环。另附systemd的service模式下的修复方案：
> 
> ```
> [Unit]
> Requires=network-online.target
> After=network-online.target
>  
> [Service]
> SyslogIdentifier=sync_video.service
> Type=simple
> ExecStart=/home/zane/docker/aliyun/sync.sh
> Restart=always
> StandardInput=tty
> StandardOutput=tty
> StandardError=null
> TTYPath=/dev/tty12
>  
> [Install]
> WantedBy=multi-user.target
> ```

确实是有这个问题
