### ISSUE TITLE
建议：通过序号进入或者下载

### ISSUE THREAD

**Issue by yanght1001** [tickstep/aliyunpan#134]
例如我使用ls展示目录结果未如下：
 #     文件大小         修改日期                        文件(目录)                  
   0             -  2022-08-10 06:39:51  游戏名字很长还有其他的东西/                                       
   1             -  2022-08-03 08:32:21  小米/                                      
   2             -  2022-04-07 07:28:28  模板/                                       
   3             -  2022-02-22 07:04:28  学习/          

我可以使用cd #2  序号直接进入【模板】文件夹

也可以使用download 或者dl 命令 下载；例如 dl  #2   直接下载序号2的目录或文件；

**Comment by xiaoyaofenfen** [comment]
这个需求使用通配符进行适配了，例如要cd到这个目录 “游戏名字很长还有其他的东西/”
可以这样：cd 游戏*
下个版本会合入
