### ISSUE TITLE
http://127.0.0.1:23077/ 打开了 但是是一个xml文件 该如何下载

### ISSUE THREAD

**Issue by Faker0715** [tickstep/aliyunpan#137]
![image](https://user-images.githubusercontent.com/36560441/185047583-450b2242-dc73-472e-ad7e-9a69f8edb1cc.png)

**Comment by Faker0715** [comment]
这里也没有webdav
![image](https://user-images.githubusercontent.com/36560441/185048552-4a333b0a-593c-4777-a073-fd7fadc91662.png)

**Comment by xiaoyaofenfen** [comment]
aliyunpan启动的是一个webdav服务器。你需要自己安装一个客户端去使用的
