### ISSUE TITLE
使用sync时，备份配置文件可以设置过滤条件吗

### ISSUE THREAD

**Issue by shcat10** [tickstep/aliyunpan#139]
upload我看是可以过滤后缀名的。请问使用sync同步可以设置吗，是在备份配置文件设置吗

**Comment by shcat10** [comment]
> 

具体是指sync的upload模式

**Comment by HuaChan233** [comment]
[这里](https://github.com/tickstep/aliyunpan/blob/main/docs/manual.md#%E5%90%8C%E6%AD%A5%E5%A4%87%E4%BB%BD%E5%8A%9F%E8%83%BD)有写针对 sync 的配置，但是是写在 docker 环境下的，我没有看过源代码，不确定非 docker 环境是否同样有效

**Comment by shcat10** [comment]
已解决，通过js插件

**Comment by xiaoyaofenfen** [comment]
JS插件可以过滤文件和文件夹。docker也支持的。
