### ISSUE TITLE
windows环境sync的upload模式下会删除网盘文件，没有仅上传

### ISSUE THREAD

**Issue by shcat10** [tickstep/aliyunpan#140]
我认为的upload模式是只管上传，本地删除不影响网盘内容。不知道是不是我理解错了，感觉这和sync模式一样了。我删除了刚上传的文件后，网盘也会紧跟着删除

启动同步备份进程
备份配置文件：D:\aliyunpan/sync_drive/sync_drive_config.json
链接类型：默认链接
下载并发：2
上传并发：2
下载分片大小：1.00MB
上传分片大小：10.00MB

启动同步任务
任务: 电影备份(fffb4908-3e45-462e-861a-228ecc2e4802)
同步模式: 备份本地文件（只上传）
本地目录: C:/Users/Administrator/Desktop/bt/电影
云盘目录: /服务器/电影

启动同步任务
任务: 电视剧备份(6983d118-2030-4480-a34f-b25cb3b534b6)
同步模式: 备份本地文件（只上传）
本地目录: C:/Users/Administrator/Desktop/bt/电视剧
云盘目录: /服务器/电视剧

本命令不会退出，如需要结束同步备份进程请输入y，然后按Enter键进行停止。
[2022-08-17 22:37:10] 上传文件：C:/Users/Administrator/Desktop/bt/电视剧/新建位图图像.bmp
[2022-08-17 22:37:45] 删除云盘文件：/服务器/电视剧/新建位图图像.bmp
[2022-08-17 22:38:18] 上传文件：C:/Users/Administrator/Desktop/bt/电视剧/新建文本文档.txt
[2022-08-17 22:38:18] 删除云盘文件：/服务器/电视剧/新建位图图像.bmp
[2022-08-17 22:38:51] 删除云盘文件：/服务器/电视剧/新建位图图像.bmp
[2022-08-17 22:39:25] 删除云盘文件：/服务器/电视剧/新建位图图像.bmp
[2022-08-17 22:39:29] 删除云盘文件：/服务器/电视剧/新建位图图像.bmp

**Comment by xiaoyaofenfen** [comment]
我删除了刚上传的文件后，网盘也会紧跟着删除

**Comment by tangkuili** [comment]
upload挺需要网盘紧跟着删除，能不能设置个选项，（这样网盘能和本地一致）    sync模式怕删除本地文件

**Comment by tangkuili** [comment]
或者sync模式本地能设置个回收站

**Comment by tangkuili** [comment]
自己改代码，打包不了

**Comment by xiaoyaofenfen** [comment]
不要在最新代码去编译，开发中的代码是可能编译不过的，你要切回版本发布的tag节点去编译



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 唐大土土 ***@***.***&gt;
发送时间: 2022年8月25日 15:23
收件人: tickstep/aliyunpan ***@***.***&gt;
抄送: xiaoyaofenfen ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [tickstep/aliyunpan] windows环境sync的upload模式下会删除网盘文件，没有仅上传 (Issue #140)





 
自己改代码，打包不了

**Comment by tangkuili** [comment]
才发现sync模式可以以本地为准，赞
