### ISSUE TITLE
期望解决文件名长度的问题，谢谢。

### ISSUE THREAD

**Issue by limingx** [tickstep/aliyunpan#147]
我在下载一些电子书，有些文件的路径名或文件名特别长，例如：

/亚马逊书籍合集/亚马逊 kindle ebook 大合集5289册/经济金融 (2)/解密Instagram（ 《金融时报》和麦肯锡2020年度商业书籍！社交应用如何改变世界？解锁打造估值千亿美元爆品的核心方法！ ) by 莎拉·弗莱尔(z-lib.org).mobi

/亚马逊书籍合集/亚马逊 kindle ebook 大合集5289册/哲学宗教/哲人石珍藏版第一辑（套装6册） by 约翰·M·巴里, 伊利亚·普里戈金, 罗伯特·卡尼格尔, 埃里克·坦普尔·贝尔, 约翰·格里宾, 玛丽·格里宾, 西尔维娅·娜萨(z-lib.org).epub

这些超过linux命名长度限制的文件，会导致下载过程中断。

建议可否考虑：
1，按某种设置好的规则下载后重命名再保存？
2，跳过这些文件下载，并将记录写入一份异常日志？以供用户手工排查
3，跳过文件下载，并将这些文件在云端移动到一个指定的异常文件夹？（方便用户云端批量调整）
4，将这些文件打包成zip，重新命名并下载？
5，…… maybe 脑洞大开

谢谢。

**Comment by xiaoyaofenfen** [comment]
这个应该可以用JS插件解决，我给你个例子参考，你要学点JavaScript的基础即可

```
function downloadFilePrepareCallback(context, params) {
    console.log(params)

    var result = {
        "downloadApproved": "yes",
        "localFilePath": ""
    };

    // 下面的代码都是分隔路径，方便下面处理
    var filePath =  params["localFilePath"];
    filePath = filePath.replaceAll("\\", "/");
    var dirPath = "";
    var fileName = "";
    var fileExt = "";
    var idx = filePath.lastIndexOf('/');
    if (idx > 0) {
        dirPath = filePath.substring(0,idx);
        fileName = filePath.substring(idx+1,filePath.length);
    } else {
        fileName = filePath;
    }
    idx = fileName.lastIndexOf(".")
    if (idx > 0) {
        fileExt = fileName.substring(idx,fileName.length);
        fileName = fileName.substring(0, fileName.length-fileExt.length)
    }

    // 开始按照需要截断太长的文件路径，例如下面的这个例子:
    // 
    // dirPath + "/"          ==> 这个的意思是保留前面的文件夹路径，如果不需要就去掉
    // fileName.substr(0,10)  ==> 文件名只取前面10个字符，其他的不要了
    // + fileExt              ==> 把文件的后缀名补上
    saveFilePath = dirPath + "/" + fileName.substr(0,10) + fileExt;

    // 返回
    result["localFilePath"] = saveFilePath;
    return result;
}

```

这个结果就是：
1）你的网盘路径是：/亚马逊书籍合集/亚马逊 kindle ebook 大合集5289册/经济金融 (2)/解密Instagram（ 《金融时报》和麦肯锡2020年度商业书籍！社交应用如何改变世界？解锁打造估值千亿美元爆品的核心方法！ ) by 莎拉·弗莱尔(z-lib.org).mobi
2）最终保存的文件路径是：亚马逊书籍合集/亚马逊 kindle ebook 大合集5289册/经济金融 (2)/解密Instagra.mobi
3）如果你把前面的目录也去掉就是：解密Instagra.mobi

应该是能满足你的需要的，你可以参考文档：![JavaScript插件](https://github.com/tickstep/aliyunpan/blob/main/docs/manual.md#JavaScript%E6%8F%92%E4%BB%B6)

**Comment by limingx** [comment]
谢谢指点，我研究了一下，加了一个判断文件名长度超过250则截断的条件，验证可用了，多谢。

btw， 这个问题应该比较常见，还是建议作者考虑默认支持。：）

**Comment by tickstep** [comment]
谢谢反馈。因为每个人的需求都不太一样，所以当前的JS插件的方式是最好的，每个人可以根据自己的需求定制。唯一的问题就是有一定的门槛。
