### ISSUE TITLE
有没有比RefreshToken更好的登录方式？

### ISSUE THREAD

**Issue by epcit** [tickstep/aliyunpan#15]
这个RefreshToken每3天就过期了，都需要重新获取来登录，不能作为自动化备份工具，非常头疼，能有办法优化吗？或者能让其自动获取RefreshToken来登录吗？

**Comment by pongfcnkl** [comment]
可以挂在下载站上，做个图床链接，放在访问量多的论坛签名上，只要水的多，访问多，就不怕过期。

**Comment by tickstep** [comment]
> > 暂时没有，阿里这个网盘登录限制非常多，登录过期时间短，账号密码登录实现又非常复杂。
> 
> 貌似[这个网址](https://github.com/wxy1343/aliyunpan)aliyunpan工具中有刷新refresh token的功能，执行命令是 `aliyunpan token -r `每次执行都会更新一个refresh token，是否可以用这种方法，放在系统定时任务中，每半小时更新一次refresh token，这样就永不过期了

v.0.0.4版本已经增加Token刷新命令

**Comment by epcit** [comment]
> > > 暂时没有，阿里这个网盘登录限制非常多，登录过期时间短，账号密码登录实现又非常复杂。
> > 
> > 
> > 貌似[这个网址](https://github.com/wxy1343/aliyunpan)aliyunpan工具中有刷新refresh token的功能，执行命令是 `aliyunpan token -r `每次执行都会更新一个refresh token，是否可以用这种方法，放在系统定时任务中，每半小时更新一次refresh token，这样就永不过期了
> 
> v.0.0.4版本已经增加Token刷新命令

非常感谢您的更新，有了这个功能就不怕过期了。
自动化备份数据再也不用担心上传网盘的问题了
