### ISSUE TITLE
请求添加超时时间参数

### ISSUE THREAD

**Issue by dreammu** [tickstep/aliyunpan#157]
晚高峰的时候海外服务器与阿里云盘的连接情况实在不太好，上传时总是出现读取Response Body超时的问题，能否添加一个超时时间的参数增加其重试时间？

**Comment by tickstep** [comment]
试试增加重试次数看是否有改善？

OPTIONS:
--retry value    上传失败最大重试次数 (default: 3)

**Comment by dreammu** [comment]
这两天尝试了一下增加重试次数，但同样难以创建上传任务，且增加重试次数并不能改善问题，均提示：
`文件上传结果： 失败！创建上传任务失败：context deadline exceeded (Client.Timeout or context cancellation while reading body),context deadline exceeded (Client.Timeout or context cancellation while reading body) 耗时 33秒

上传结束, 时间: 33秒, 数据总量: 0B`
增加了重试次数也同样是这个提示以及结束时间，这个参数似乎只能在创建上传任务成功的前提下才有用，而我这边的主要问题是晚高峰时创建上传任务本身很困难。

**Comment by lengyefenghan** [comment]
遇到了同样地问题 希望后面能加上这个参数

**Comment by xiaoyaofenfen** [comment]
已经增加upload的超时选项，预计下个版本合入。
