### ISSUE TITLE
备份模式，如何关闭默认分片

### ISSUE THREAD

**Issue by 692568516** [tickstep/aliyunpan#158]
文件比较大，upload时候默认会进行分片，这时候就会超出允许的分片数量导致失败，请问如何关闭分片和校验，直接上传呢

**Comment by xiaoyaofenfen** [comment]
> 文件比较大，upload时候默认会进行分片，这时候就会超出允许的分片数量导致失败，请问如何关闭分片和校验，直接上传呢

阿里默认是需要分片的，这样续传才能做。
你可以调大分片大小，这样大文件也支持，你试试这个选项调大分片大小：

```
$ sync start -h
OPTIONS:
   --ubs value   upload block size，上传分片大小，单位KB。推荐值：1024 ~ 10240 (default: 10240)

```

**Comment by 692568516** [comment]
好的谢谢，推荐值是1024-10240   ，当时看到这个帮助看选项默认最大了就没调整，测试其实是可以设置为大于10240的值的

**Comment by tickstep** [comment]
> 好的谢谢，推荐值是1024-10240 ，当时看到这个帮助看选项默认最大了就没调整，测试其实是可以设置为大于10240的值的

是的可以调大的，这个推荐值是考虑到上传效率，以及系统资源消耗，定出来的。
