### ISSUE TITLE
aliyunpan sync 不能同步文件夹

### ISSUE THREAD

**Issue by kerrer** [tickstep/aliyunpan#159]
aliyunpan sync start  -mode ""upload/download“  只能上传或下载文件夹，不能真正的同步，本地文件删除了，也无法同步到盘。而且命令每次运行都重新上传或下载所有文件。

**Comment by xiaoyaofenfen** [comment]
> aliyunpan sync start -mode ""upload/download“ 只能上传或下载文件夹，不能真正的同步，本地文件删除了，也无法同步到盘。而且命令每次运行都重新上传或下载所有文件。

同步要用这个模式“sync”

**Comment by tickstep** [comment]
命令每次运行都重新上传或下载所有文件
==》这个在新版本有修复，你可以试试新版本
