### ISSUE TITLE
同步任务失败,一直报错 ERROR: get download url error: 632824b2af32a8f876074abd8e2c579756acb6db

### ISSUE THREAD

**Issue by zzw6776** [tickstep/aliyunpan#162]
如题,开启debug后一直
 ERROR: get download url error: 632824b2af32a8f876074abd8e2c579756acb6db
错误

**Comment by zzw6776** [comment]
我手动删除sync_drive的数据,同步又正常,但是还是有个问题,假设一个文件被其他进程上锁,同步会忽略,就算之后解锁也不会重新同步,除非重新运行命令才行,希望作者修复下

**Comment by xiaoyaofenfen** [comment]
> 

这个看不出来啥问题，你这个下载的文件有非法的文件么？

**Comment by xiaoyaofenfen** [comment]
> 我手动删除sync_drive的数据,同步又正常,但是还是有个问题,假设一个文件被其他进程上锁,同步会忽略,就算之后解锁也不会重新同步,除非重新运行命令才行,希望作者修复下

这个确实是个问题。sync_drive同步的bolt数据库没有留存了么，有的话传上来看看

**Comment by zzw6776** [comment]
没留存了   我看用不了就删了～～触发场景就是在linux和windows都开对同一个文件夹的同步  然后在windows这个文件夹里面有个文件是被其他进程占用  就会发生我说的情况(小概率会一直报错  除非手动去删除缓存)

**Comment by tickstep** [comment]
文件锁定问题已做适配
