### ISSUE TITLE
关闭webdav模式屏蔽某个文件夹

### ISSUE THREAD

**Issue by ixinshang** [tickstep/aliyunpan#164]
工具很好用。
请教一个1个问题，在docker的webdav模式下,如何排除一个文件夹的上传。

**Comment by tickstep** [comment]
你这个得在webdav客户端去搞才行，你看看你的客户端怎么支持排除文件

**Comment by ixinshang** [comment]
> 你这个得在webdav客户端去搞才行，你看看你的客户端怎么支持排除文件

好的，谢谢。
