### ISSUE TITLE
sync的upload模式没有执行脚本

### ISSUE THREAD

**Issue by Tiannary** [tickstep/aliyunpan#166]
sync的upload模式没有执行设置好的脚本，用的uploadFileFinishCallback函数，但是单独运行upload的时候脚本成功运行了，请问是bug还是说sync模式不会运行uploadFileFinishCallback函数吗

**Comment by Tiannary** [comment]
> > sync的upload模式没有执行设置好的脚本，用的uploadFileFinishCallback函数，但是单独运行upload的时候脚本成功运行了，请问是bug还是说sync模式不会运行uploadFileFinishCallback函数吗
> 
> sync有独立的脚本，是这个文件：sync_handler.js。不过sync还没做上传文件后的回调，现在只有准备阶段扫描文件的回调

了解了，谢谢

**Comment by xiaoyaofenfen** [comment]
已经增加回调，下个版本合入
```
function syncFileFinishCallback(context, params) {
	console.log(params)
}
```
