### ISSUE TITLE
refresh_token会过期？

### ISSUE THREAD

**Issue by auqhjjqdo** [tickstep/aliyunpan#167]
自己写了服务器备份脚本每天定时自动备份到阿里云盘上，但每隔一段时间就会提示token失效需要重新登录，隔壁alist的refresh_token从没出现过期，是否考虑采用alist的方案
alist的refresh_token方案详见[https://alist.nn.ci/zh/guide/drivers/aliyundrive.html](https://alist.nn.ci/zh/guide/drivers/aliyundrive.html)

**Comment by xiaoyaofenfen** [comment]
会过期，所以需要定时刷新，最好每个小时刷新一次。有刷新命令：aliyunpan token update
抓APP的token有点麻烦，有空看看

**Comment by auqhjjqdo** [comment]
app的refresh_token应该也是要经常刷新的，只是有效期可能更长一些，alist因为需要后台常驻所以可以自己定时刷新令牌。
cli的话因为不是常驻后台不能自己刷新（webdav除外），建议可以在每次上传&下载&同步时自动执行一下刷新，这样就不用单独写个定时刷新脚本或者执行命令前先刷新令牌了

**Comment by tickstep** [comment]
> app的refresh_token应该也是要经常刷新的，只是有效期可能更长一些，alist因为需要后台常驻所以可以自己定时刷新令牌。
> cli的话因为不是常驻后台不能自己刷新（webdav除外），建议可以在每次上传&下载&同步时自动执行一下刷新，这样就不用单独写个定时刷新脚本或者执行命令前先刷新令牌了

上传，和下载过程中会有刷新的。但是当程序没有在运行，程序自身是没有条件刷新的，所以只能用类似crontab任务进行定时刷新了，也就一条指令，不算麻烦

**Comment by auqhjjqdo** [comment]
我通过观察config文件发现上传后会刷新webToken里的refreshToken，但登录时输入的的refreshToken字段并未刷新
另外我的服务器备份脚本也是crontab每天自动上传的，理论上每天也是会刷新webToken里的refreshToken，但依旧出现了一段时间后令牌失效的问题，是一天一次刷新过长还是说有什么bug导致的令牌失效呢

**Comment by tickstep** [comment]
> 我通过观察config文件发现上传后会刷新webToken里的refreshToken，但登录时输入的的refreshToken字段并未刷新
> 
> 另外我的服务器备份脚本也是crontab每天自动上传的，理论上每天也是会刷新webToken里的refreshToken，但依旧出现了一段时间后令牌失效的问题，是一天一次刷新过长还是说有什么bug导致的令牌失效呢

需要每小时刷新一下，token一般两个小时就过期了。

**Comment by xiaoyaofenfen** [comment]
已经做了一些优化，新版本可以再验证下
