### ISSUE TITLE
[登录失败] 使用RefreshToken登录，报错存在异常

### ISSUE THREAD

**Issue by danger2you** [tickstep/aliyunpan#170]
invalid character 'ï' looking for beginning of value

如图： 
![image](https://user-images.githubusercontent.com/33245233/194740997-03fce9d8-68fa-4242-9412-3a4b56944674.png)

**Comment by xiaoyaofenfen** [comment]
开debug看看日志。
这个大概是网络或者是接口风控的问题，一般过段时间应该就能好

**Comment by danger2you** [comment]
好的，网络问题，已处理，谢谢
