### ISSUE TITLE
Refreshtoken登陆失败

### ISSUE THREAD

**Issue by Forone-Shijie** [tickstep/aliyunpan#173]
为什么用token无法登陆，是网络还是程序有什么问题呢？
<img width="570" alt="image" src="https://user-images.githubusercontent.com/63043963/195487078-fba2d2c6-2e4b-4764-98fe-7b35b27ecd49.png">

**Comment by CozyDust** [comment]
如果网页版没关闭可以试试关闭网页版后再用token登陆一次试试
