### ISSUE TITLE
可以上传FTP文件吗

### ISSUE THREAD

**Issue by zxniuniu** [tickstep/aliyunpan#174]
你好，可以上传自己FTP上的文件吗，如果不能上传，是不是只能先自己下载下来，再上传？

**Comment by tickstep** [comment]
> 你好，可以上传自己FTP上的文件吗，如果不能上传，是不是只能先自己下载下来，再上传？

是的，只能先下载再上传。如果你有ftp server的访问权限，可以直接在server端进行上传会省事点
