### ISSUE TITLE
云盘中的文件如果以“.”为后缀名，下载后会将“.”改回“_”

### ISSUE THREAD

**Issue by Using-jie** [tickstep/aliyunpan#177]
上传项目时候，将本地git也同时上传，出现  _git、_idea文件

**Comment by xiaoyaofenfen** [comment]
> 上传项目时候，将本地git也同时上传，出现 _git、_idea文件

我在最新版本试了，没啥问题呀。你能传下log吗？

**Comment by Using-jie** [comment]
上传可以，下载下来就变了。我是在使用软件中出现的这个情况
![image](https://user-images.githubusercontent.com/65282727/197683119-68288c51-5dc9-4855-b2dc-c89eaaf8d195.png)

**Comment by xiaoyaofenfen** [comment]
> 上传可以，下载下来就变了。我是在使用软件中出现的这个情况 ![image](https://user-images.githubusercontent.com/65282727/197683119-68288c51-5dc9-4855-b2dc-c89eaaf8d195.png)

下载我也试了，我这边也没啥问题。你现在能复现吗？开debug 日志看看

**Comment by xiaoyaofenfen** [comment]
最新版本验证了，没有复现，先关闭了哈
