### ISSUE TITLE
建议支持 夸克云盘 

### ISSUE THREAD

**Issue by ghost** [tickstep/aliyunpan#180]
目前夸克网盘速度和容量非常可观了
希望大佬能够考虑添加夸克网盘

@xiaoyaofenfen

**Comment by yishuiwang** [comment]
感觉希望渺茫

**Comment by xiaoyaofenfen** [comment]
精力有限，这个真搞不了了。看看有没有其他网友感兴趣想做的，我这边抽空可以提些PR做些支援
