### ISSUE TITLE
反馈：v0.2.2-linux-mips在 MediaTek MT7621 SoC下运行不了  请求作者分析

### ISSUE THREAD

**Issue by sw586** [tickstep/aliyunpan#182]
![image](https://user-images.githubusercontent.com/24788222/198896860-d33e8b00-72d6-4ed8-ab81-b85dc4094203.png)
以上版本都尝试过
报错如下
![image](https://user-images.githubusercontent.com/24788222/198896876-270201e0-12cc-4de0-a9e3-dfaf5db5dded.png)
设备：小米路由器(MI-R3G)
系统：openwrt

CPU信息：
```
MI-R3G:/home/root # cat /proc/cpuinfo
system type             : MediaTek MT7621 SoC
processor               : 0
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 731.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0ff8, 0x00                                                                              00, 0x0ff8]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 731.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x00                                                                              00, 0x0ffb]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 2
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 731.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x00                                                                              00, 0x0ff8]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VPE                     : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 3
cpu model               : MIPS 1004Kc V2.15
BogoMIPS                : 731.13
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0000, 0x0000, 0x00                                                                              00, 0x0ffb]
ASEs implemented        : mips16 dsp mt
shadow register sets    : 1
kscratch registers      : 0
core                    : 1
VPE                     : 1
VCED exceptions         : not available
VCEI exceptions         : not available

```

系统信息：
```
MI-R3G:/home/root # cat /proc/version
Linux version 3.4.113 (padavan@hms) (gcc version 7.4.0 (crosstool-NG UNKNOWN) )      
```

**Comment by tickstep** [comment]
修改了下编译配置，你帮忙验证下以下那个版本能正常用的，我手头没有这种设备验证不了

[aliyunpan-v0.2.3-linux-mipshf.zip](https://github.com/tickstep/aliyunpan/files/9901415/aliyunpan-v0.2.3-linux-mipshf.zip)
[aliyunpan-v0.2.3-linux-mipsle.zip](https://github.com/tickstep/aliyunpan/files/9901420/aliyunpan-v0.2.3-linux-mipsle.zip)
[aliyunpan-v0.2.3-linux-mipsle2.zip](https://github.com/tickstep/aliyunpan/files/9901424/aliyunpan-v0.2.3-linux-mipsle2.zip)
[aliyunpan-v0.2.3-linux-mipslehf.zip](https://github.com/tickstep/aliyunpan/files/9901434/aliyunpan-v0.2.3-linux-mipslehf.zip)
[aliyunpan-v0.2.3-linux-mips.zip](https://github.com/tickstep/aliyunpan/files/9901408/aliyunpan-v0.2.3-linux-mips.zip)
[aliyunpan-v0.2.3-linux-mips2.zip](https://github.com/tickstep/aliyunpan/files/9901412/aliyunpan-v0.2.3-linux-mips2.zip)

**Comment by sw586** [comment]
> 修改了下编译配置，你帮忙验证下那个版本可以正常使用的，我手头没有这个设备验证不了
> 
> [aliyunpan-v0.2.3-linux-mipshf.zip ](https://github.com/tickstep/aliyunpan/files/9901415/aliyunpan-v0.2.3-linux-mipshf.zip) [aliyunpan-v0.2.3-linux-mipsle.zip ](https://github.com/tickstep/aliyunpan/files/9901420/aliyunpan-v0.2.3-linux-mipsle.zip) [aliyunpan-v0.2.3-linux-mipsle2.zip ](https://github.com/tickstep/aliyunpan/files/9901424/aliyunpan-v0.2.3-linux-mipsle2.zip) [aliyunpan-v0.2.3-linux-mipslehf.zip ](https://github.com/tickstep/aliyunpan/files/9901434/aliyunpan-v0.2.3-linux-mipslehf.zip) [aliyunpan-v0.2.3- linux-mips.zip ](https://github.com/tickstep/aliyunpan/files/9901408/aliyunpan-v0.2.3-linux-mips.zip) [aliyunpan-v0.2.3-linux-mips2.zip](https://github.com/tickstep/aliyunpan/files/9901412/aliyunpan-v0.2.3-linux-mips2.zip)

感谢回复，以下是6个版本验证结果，均为失败，如果您愿意继续跟进，我将配合您测试或提供必要的信息，谢谢您。
![image](https://user-images.githubusercontent.com/24788222/199579360-6a1413ad-5f8b-4634-9675-df4dc2363686.png)
![image](https://user-images.githubusercontent.com/24788222/199579455-a6376d2a-70c6-4134-8f9a-5e2842a2c503.png)
![image](https://user-images.githubusercontent.com/24788222/199580074-b49ab411-5fcd-440e-bfc1-995313fe266f.png)
![image](https://user-images.githubusercontent.com/24788222/199580514-beedadaf-23c9-4e79-bf02-ac4b1942dbf5.png)
![image](https://user-images.githubusercontent.com/24788222/199580964-4fbe9d0e-0a38-4dd2-bba5-333148c81421.png)
![image](https://user-images.githubusercontent.com/24788222/199581253-d7512574-2cbb-43ab-83a7-0b44eb5971f0.png)

**Comment by tickstep** [comment]
有空再研究下先

**Comment by sw586** [comment]
> 有空再研究下先

好的 感谢

**Comment by tickstep** [comment]
这两天花了点时间研究了下，理论上看，go内置是支持mips程序的编译。
我也看到有人分享了在R3G路由器openwrt下正常运行的go程序：https://zhuanlan.zhihu.com/p/57163950
你之前提到的mipsel_24kc编译在go这边对应的是开启交叉编译，下面带有cxx的就是交叉编译的

我们再验一次，你看下面有没有能正确运行成功的
[aliyunpan-cxx-v0.2.3-linux-mipsle.zip](https://github.com/tickstep/aliyunpan/files/9942829/aliyunpan-cxx-v0.2.3-linux-mipsle.zip)
[aliyunpan-v0.2.3-linux-mipsle.zip](https://github.com/tickstep/aliyunpan/files/9942830/aliyunpan-v0.2.3-linux-mipsle.zip)

[hello-cxx-v0.0.1-linux-mipsle.zip](https://github.com/tickstep/aliyunpan/files/9942831/hello-cxx-v0.0.1-linux-mipsle.zip)
[hello-mac-v0.0.1-linux-mipsle.zip](https://github.com/tickstep/aliyunpan/files/9942832/hello-mac-v0.0.1-linux-mipsle.zip)
[hello-v0.0.1-linux-mipsle.zip](https://github.com/tickstep/aliyunpan/files/9942833/hello-v0.0.1-linux-mipsle.zip)

**Comment by tickstep** [comment]
最新版本在openwrt下是可以的，小米R3G刷了openwrt，测试如下：
![image](https://user-images.githubusercontent.com/31570634/213691777-a49dcd72-c41b-46f5-b788-06b640c7aadf.png)
