### ISSUE TITLE
修改/添加docker环境（-e）不会更新现有的任务

### ISSUE THREAD

**Issue by HySand** [tickstep/aliyunpan#195]
Docker的aliyunpan-sync一旦启动就没办法修改参数了吗，有没有指令可以修改ALIYUNPAN_LOCAL_DELAY_TIME之类的参数，还是只能把配置文件删了重新上传。
希望每次重启都能重新读取一下环境变量。

**Comment by xiaoyaofenfen** [comment]
你进入到docker容器里面改，然后restart一下docker就能生效了，类似
docker exec -it aliyunpan-sync sh
export ALIYUNPAN_LOCAL_DELAY_TIME=10
docker start  aliyunpan-sync
