### ISSUE TITLE
sync命令如何查看进度？

### ISSUE THREAD

**Issue by yejustme** [tickstep/aliyunpan#197]
把本地文件夹与阿里云盘同步时，本地文件夹内容比较多，虽然一直开着aliyun sync命令，但不知道有没有同步完成。如果能显示进度就好了！谢谢

**Comment by xiaoyaofenfen** [comment]
sync命令增加 -log ture 参数可以查看已经同步的文件

**Comment by xiaoyaofenfen** [comment]
最新版本，会在配置目录下的 logs/sync.csv 文件保存成功同步的文件记录了，可以使用这个

**Comment by Haixing-Hu** [comment]
> 最新版本，会在配置目录下的 logs/sync.csv 文件保存成功同步的文件记录了，可以使用这个

0.2.8 版本，同步时，并没有在配置目录下看到有 logs/sync.csv 啊
