### ISSUE TITLE
请教Token刷新失败通过邮件发送通知的方法

### ISSUE THREAD

**Issue by 7161457** [tickstep/aliyunpan#203]
关于token失效尝试发送邮件通知，但是没有成功，下面贴出我的配置，请帮忙看下是哪里的问题。
1  token_handler.js.sample和token_handler.js都有创建。
2  环境变量ALIYUNPAN_CONFIG_DIR设置配置目录也已经更改并且配置plugin/js文件夹
3  js和sample文件也都放在js文件夹
![1670471938312](https://user-images.githubusercontent.com/113887555/206354146-b659b039-0cff-4828-a7a7-2344a07e0deb.jpg)
![1670471964939](https://user-images.githubusercontent.com/113887555/206354154-2f65df80-e5ba-48d7-9b4f-48bdab57a322.jpg)
![1670472001584](https://user-images.githubusercontent.com/113887555/206354157-467e7b95-0328-4d52-bb01-047c100d3663.jpg)
![1670472068320](https://user-images.githubusercontent.com/113887555/206354158-dd91efc7-3762-4f66-b3a4-e09a94755fd4.jpg)

**Comment by xiaoyaofenfen** [comment]
你用的是docker容器，ALIYUNPAN_CONFIG_DIR 需要配置docker容器里面的路径，你目前配置的是你主机Host的路径肯定是不对的。

可以这样去改：
1）删掉 ALIYUNPAN_CONFIG_DIR 这个配置
2）增加以下卷挂载，直接把JS脚本挂载到容器里面供程序使用
```
services:
...
    volumes:
      - /volume1/docker/aliyunpan/plugin/js/token_handler.js:/home/app/config/plugin/js/token_handler.js
...
```

JS脚本你只需要发邮件，可以这样写，注意你的邮件必须开启smtp发送功能，这个你得找邮箱提供商去开
```
function userTokenRefreshFinishCallback(context, params) {
    try {
        if (params["result"] === "fail") {
            // 避免频繁发送
            var ONE_MINUTE = 60 * 1000;
            var lastSendEmailTime = PluginUtil.KV.getString("email_last_send_time");
            if (lastSendEmailTime != "") {
                if ((Date.now() - lastSendEmailTime) < (10 * ONE_MINUTE)) {
                    console.log("距离上次发送邮件小于10分钟，先不发送了");
                    return
                }
            }
            PluginUtil.KV.putString("email_last_send_time", Date.now());

            // 发送通知邮件，请确保你的发送邮箱具备smtp发送权限
            console.log("发送通知邮件");
            PluginUtil.Email.sendTextMail("smtp.qq.com:465", "123xxx@qq.com", "pwdxxxxxx", "12545xxx@qq.com", "Token刷新失败了", "Token过期了，快去手动恢复吧");
        }
    } catch (e) {
        if (e !== "Error") {
            throw e;
        }
    }
}

```

**Comment by 7161457** [comment]
目前还是不能激活发送邮件的js，配置全部正确，js的编码是utf-8的。由于我是直接输入错误的token，然后启动docker程序来测试的，初步判断是 刚启动时候token过期，是不是代码没有跑到发送邮件这里，只有在启动后使用中token过期才会激活发送邮件的js。
1已经删掉 ALIYUNPAN_CONFIG_DIR 这个配置
2直接把JS脚本挂载到容器里面供程序使用
3smtp功能正常，因为已经用其他程序测试发件正常。
![1670555962630](https://user-images.githubusercontent.com/113887555/206617675-4eb6a57d-9b00-4420-97cf-f29534c251c9.jpg)
![1670556045048](https://user-images.githubusercontent.com/113887555/206617681-aeb07051-54fe-4ce2-8ec0-8d8744bd12b3.jpg)
![1670556063836](https://user-images.githubusercontent.com/113887555/206617685-0cb0cb32-ceeb-488e-9ad6-ca7ae03c6a35.jpg)
![1670556098320](https://user-images.githubusercontent.com/113887555/206617686-c9e841ff-9c55-445c-83d4-09f4ee08bc5f.jpg)

**Comment by xiaoyaofenfen** [comment]
1）登录这个没有hook，目前只有运行过程中token过期了才会hook并触发插件调用。登录Hook这个功能下个版本再加下

2）你的配置应该是没有问题的，我们可以这样验证
将JS脚本中的fail改成"success"，然后重启docker容器，这样两个小时后token会自己刷新，会触发成功刷新的token的调用，这样就会触发JS里面的发邮件任务，通过这种方式确认你的JS配置是没有问题后，你再改回来即可
```
if (params["result"] === "fail") {
           ...
}

将fail改成"success"，如下所示，其他不用改

if (params["result"] === "success") {
           ...
}

```

**Comment by 7161457** [comment]
已经把fail改成"success，换了好几种方法尝试，DIR 配置和储存空间映射，都是失败的，而且运行日志没有 console.log("发送通知邮件");这个的体现。不知道此段代码，你是否运行尝试，有没有可能缺少符号之类的。
![1670751584656](https://user-images.githubusercontent.com/113887555/206896562-ceb5a611-81d6-400e-90a0-f2f9ab03824e.jpg)

**Comment by xiaoyaofenfen** [comment]
> 已经把fail改成"success，换了好几种方法尝试，DIR 配置和储存空间映射，都是失败的，而且运行日志没有 console.log("发送通知邮件");这个的体现。不知道此段代码，你是否运行尝试，有没有可能缺少符号之类的。 ![1670751584656](https://user-images.githubusercontent.com/113887555/206896562-ceb5a611-81d6-400e-90a0-f2f9ab03824e.jpg)

1，JS脚本没有问题的，这个放心。之前有在本地aliyunpan工具验证过
![image](https://user-images.githubusercontent.com/5262333/206978879-0b415f3b-245d-4a23-ab8c-1d08c31053d9.png)
![image](https://user-images.githubusercontent.com/5262333/206978975-f6682997-76cd-47c9-a3dc-174325d8da76.png)

2，我看了下代码是aliyunpan-webdav这边有bug，success的情况不会调用JS，只有fail才会调用
所以两种方案
1）你可以用我编译的docker镜像，里面修正了JS调用的问题，其他功能和官方版本一样，如下
```
docker pull feny/aliyunpan-webdav:v0.2.4-1
```
2）JS脚本你改回fail，放着等待fail情况会触发调用，到时候再确认

**Comment by 7161457** [comment]
好的，明白了，群辉nas， pull不太方便，只能从https://registry.hub.docker.com里面搜索。
并且我这边是每周会关机1夜，然后重启群辉nas docker，应该都是这个时候token过期的，所以我应该用你的下一版登录Hook的调用， 启动时候对token的验证发送邮件。
期待你下一版 早点发布。
![1670829029827](https://user-images.githubusercontent.com/113887555/206982824-9eee3dc2-19d5-4c56-afe5-8dab125be6f7.jpg)
![1670829053343](https://user-images.githubusercontent.com/113887555/206982834-485184d5-fe3a-4ec5-870c-178cfcb9d4c2.jpg)

**Comment by 7161457** [comment]
![1670831461393](https://user-images.githubusercontent.com/113887555/206990545-d3aab864-1c24-4849-a0b1-76cb748228a0.jpg)
发现了你的新更新，请问这个版本有登录Hook的调用吗？

**Comment by xiaoyaofenfen** [comment]
> ![1670831461393](https://user-images.githubusercontent.com/113887555/206990545-d3aab864-1c24-4849-a0b1-76cb748228a0.jpg) 发现了你的新更新，请问这个版本有登录Hook的调用吗？

是的，登录的，webdav的都有的

**Comment by tickstep** [comment]
新版已发布
