### ISSUE TITLE
增加日志功能

### ISSUE THREAD

**Issue by xiatao** [tickstep/aliyunpan#206]
首先非常感谢作者的无私分享，阿里云盘命令行版相当实用好用，我也非常有需求。相比Rclone机械性的上传，这个项目最大优势是支持秒传，我现在主要是利用qbittorrent下载完成后调用这个项目upload功能上传下载完的文件至阿里云盘，由于该过程均在VPS后台运行，故希望增加日志功能，便于时候查看上传的具体情况，最后再次致敬！

**Comment by xiaoyaofenfen** [comment]
已经增加，下个版本发布
