### ISSUE TITLE
输入login 之后按Tab键闪退

### ISSUE THREAD

**Issue by lixiaojie1245** [tickstep/aliyunpan#212]

**Comment by tickstep** [comment]
试了以下没有，你是哪种环境下测试的？windows?

**Comment by lixiaojie1245** [comment]
aliyunpan:video 网盘别挂$ logout
确认退出当前帐号: 网盘别挂 ? (y/n) > y
退出用户成功: 网盘别挂
aliyunpan > login panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x822146]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/config.(*PanUser).GetActiveDriveInfo(0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/config/pan_user.go:202 +0x26
github.com/tickstep/aliyunpan/internal/config.(*PanUser).IsFileDriveActive(...)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/config/pan_user.go:211
main.main.func2.2(0xc0002be5d0, 0x6, 0x6, 0x20, 0xc0002be5d0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:249 +0x1205
github.com/peterh/liner.(*State).SetCompleter.func1(0xc0002be5c0, 0x6, 0x6, 0x20, 0xc0002be5c0, 0x6, 0x1, 0x0, 0xc0004a3448, 0x449c0e)
	/Users/tickstep/Applications/go/pkg/mod/github.com/peterh/liner@v1.2.1/common.go:199 +0xc5
github.com/peterh/liner.(*State).tabComplete(0xc0000d3400, 0xc0004a3860, 0xc, 0x20, 0xc0004a37e0, 0x6, 0x20, 0x6, 0x0, 0x0, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/peterh/liner@v1.2.1/line.go:368 +0xb2
github.com/peterh/liner.(*State).PromptWithSuggestion(0xc0000d3400, 0xc0002be570, 0xc, 0x0, 0x0, 0x6, 0x0, 0x0, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/peterh/liner@v1.2.1/line.go:825 +0x3fe
github.com/peterh/liner.(*State).Prompt(...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/peterh/liner@v1.2.1/line.go:595
main.main.func2(0xc00013a000)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:356 +0x558
github.com/urfave/cli.HandleAction(0xbc7ec0, 0xc00031ea30, 0xc00013a000, 0xc00013a000, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:525 +0x59
github.com/urfave/cli.(*App).Run(0xc0000ec000, 0xc000030210, 0x1, 0x1, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:285 +0x655
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:630 +0x1587
lxj@lxj-ThinkPad-T420:~/hdd320/download$ ^C

**Comment by lixiaojie1245** [comment]
ubuntu22
在没有登陆的时候,输入:login <tab> 闪退

**Comment by tickstep** [comment]
感谢反馈，已修复。下个版本合入
