### ISSUE TITLE
上传大文件在1小时的时候出现：文件分片上传顺序错误，开始重新上传文件

### ISSUE THREAD

**Issue by Adoirsa** [tickstep/aliyunpan#214]
[日志.txt](https://github.com/tickstep/aliyunpan/files/10301148/default.txt)

日志太多了 我是从开始报错的地方截取的

每次都是 1小时零几秒的时候就出现 文件分片上传顺序错误，开始重新上传文件

昨天晚上挂了一晚上，早晨起来一看 每次都是1小时零几秒就开始重新上传，一晚上重新上传了N次

**Comment by Adoirsa** [comment]
问题出在 internal\functions\panupload\utils.go 

func IsUrlExpired(urlStr string) bool {
	u, err := url.Parse(urlStr)
	if err != nil {
		return true
	}
	expiredTimeSecStr := u.Query().Get("x-oss-expires")
	expiredTimeSec, _ := strconv.ParseInt(expiredTimeSecStr, 10, 64)
	if (time.Now().Unix() - 10) >= expiredTimeSec {
		// expired
		return true
	}
	return false
}

我改成

func IsUrlExpired(urlStr string) bool {
	u, err := url.Parse(urlStr)
	if err != nil {
		return true
	}
	expiredTimeSecStr := u.Query().Get("x-oss-expires")
	expiredTimeSec, _ := strconv.ParseInt(expiredTimeSecStr, 10, 64)
	if (time.Now().Unix() + 300) >= expiredTimeSec {
		// expired
		return true
	}
	return false
}

之后就会在55分左右的时候更新上传地址，然后就没有问题了。已经成功上传了

**Comment by tickstep** [comment]
> 问题出在 internal\functions\panupload\utils.go
> 
> func IsUrlExpired(urlStr string) bool { u, err := url.Parse(urlStr) if err != nil { return true } expiredTimeSecStr := u.Query().Get("x-oss-expires") expiredTimeSec, _ := strconv.ParseInt(expiredTimeSecStr, 10, 64) if (time.Now().Unix() - 10) >= expiredTimeSec { // expired return true } return false }
> 
> 我改成
> 
> func IsUrlExpired(urlStr string) bool { u, err := url.Parse(urlStr) if err != nil { return true } expiredTimeSecStr := u.Query().Get("x-oss-expires") expiredTimeSec, _ := strconv.ParseInt(expiredTimeSecStr, 10, 64) if (time.Now().Unix() + 300) >= expiredTimeSec { // expired return true } return false }
> 
> 之后就会在55分左右的时候更新上传地址，然后就没有问题了。已经成功上传了
好的，我也统一改成5分钟

**Comment by tickstep** [comment]
有做了优化，请在新版中验证
