### ISSUE TITLE
关于  rename 批量重命名 的建议

### ISSUE THREAD

**Issue by iCodyYang** [tickstep/aliyunpan#215]
希望可以支持 rename 批量重命名

我目前在配合 infuse + alist + 阿里云盘 使用 Apple TV ，经常遇到需要批量重命名的需求。如果我把阿里云挂在本地，再批量重命名的时候 finder会经常挂（m1 mac mini），所以想通过命令行修改，于是就找到了这里。希望可以支持一下  rename 批量重命名 ，有同样需求的朋友也不少。谢谢。

**Comment by tickstep** [comment]
借鉴以前旧的Linux批量重命名的方式，先做个简单能用的。下版本会合入
