### ISSUE TITLE
请求加入网盘文件向本地同步功能

### ISSUE THREAD

**Issue by muxiachuixue** [tickstep/aliyunpan#22]
想把icloud照片同步到linux 外接的硬盘，可以设置先把icloud 照片同步到阿里云盘，然后把阿里云盘照片同步到本地。但是本插件貌似只有本地向云端同步，没有云端到本地的同步功能？如果方便的话，请求大佬加上此功能！我看百度网盘工具bypy是支持的。

**Comment by tickstep** [comment]
你要不要试试webdav同步，理论上是可行的

**Comment by tickstep** [comment]
可以试试v0.1.6 版本的sync命令
