### ISSUE TITLE
建议列出目录可以排序

### ISSUE THREAD

**Issue by StrollStars** [tickstep/aliyunpan#224]
发现有些目录并非按一定顺序排序，给查找文件带来麻烦，所以希望能够支持列出目录可按文件名排序。

**Comment by xiaoyaofenfen** [comment]
支持的，你可以看帮助文档
```
ls --name --asc
```

**Comment by StrollStars** [comment]
@xiaoyaofenfen 感谢帮助，不过[命令手册](https://github.com/tickstep/aliyunpan/blob/main/docs/manual.md)中并没有提到，请问帮助文档在哪里？
