### ISSUE TITLE
aliyunpan version v0.2.5，分片上传出错

### ISSUE THREAD

**Issue by xyxy** [tickstep/aliyunpan#235]
yum install 安装的aliyunpan version v0.2.5
阿里云ECS机器。

文件大于10M的都无法上传，小于10M的正常，大于10M的文件每次上传到10M的时候就提示失败：
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2542438/216480143-30f5ecba-a06e-4018-a242-472870f3dc19.png">
<img width="632" alt="image" src="https://user-images.githubusercontent.com/2542438/216480290-cf4b55b8-3fbb-455b-bb69-5216d3364dd1.png">

**Comment by WUyinwei-hah** [comment]
我也遇到了这个问题 请问解决了吗
