### ISSUE TITLE
几个功能优化的建议

### ISSUE THREAD

**Issue by bjzhush** [tickstep/aliyunpan#236]
首先感谢作者及各位代码贡献者，让我们在Linux没有官方客户端的情况下拥有如此方便且功能强大的命令行客户端。
在使用的过程中，发现一些或许可以让这个程序更好用的点，来建议一下，抛砖引玉。
**①建议支持暂停功能**
    由于阿里云盘不限速，很多时候在挂下载任务的时候能跑满带宽，这时候如果在网页端进行一些比如类似查看视频之类的任务可能就会卡顿，如果增加一个命令，比如pause ，在新开一个命令行实例的情况下，输入pause，可以暂停其它实例在进行的任务，这样会更方便，其它任务完成后再输入NoPause恢复下载。
**②建议增加一个进度条功能**
    在tree命令的最后，我是看到了总计的文件大小的，这说明aliyunpan支持文件夹大小统计，在下载的过程中，很多时候我们不知道总的下载量是多大，也不知道已经下载了百分之多少，如果能支持展示百分比，相信是一个非常受用户欢迎的功能。
**③建议tree命令支持输出文件大小以及过滤只展示指定大小的文件**
    这个功能在梳理网盘文件的时候非常有用，比如我就想看看超过10G的有哪些文件，比如 tree  --minSize=10G 这样，梳理和删除大文件就会非常方便，通过20G 10G 5G这样用户自己调整大小，可以极其方便的筛选过滤文件。
     另外tree命令可以考虑加一个参数支持，比如 --showSize ，带这个参数就会在tree的结果展示文件的大小。

以上仅为个人的一点想法，抛砖引玉，再次感谢各位的贡献 ！！

**Comment by xiaoyaofenfen** [comment]
感谢反馈，可以排着做做看。不过有些以前有做过类似，例如进度条这个，这需要要统计下载的文件总大小（文件很多时候）会有性能问题，所以砍掉了

**Comment by xiaoyaofenfen** [comment]
① 这个先不加了，直接Ctrl+C退出就算是暂停了，再启动应用可以续传
② 上传和下载都增加了单个文件的百分比显示，但是总的百分比因为性能问题就先不做了。下个版本合入
③ 已增加，包括showSize maxSize minSize。下个版本合入
