### ISSUE TITLE
错误 syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by DingJianhao** [tickstep/aliyunpan#24]
您好 下载您的aliyunpan-v0.0.5-freebsd-amd64.zip版本 
chmod 777 aliyunpan
后
运行 ./aliyunpan
显示
./aliyunpan: line 1: syntax error near unexpected token `newline'
./aliyunpan: line 1: `<!DOCTYPE html>'

我的机器 
uname -a:
Linux d6d2a1500408f011ec08bb20f3128d160513-dingjh179-0 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tickstep** [comment]
你这看着不像freebsd呀，你用linux amd64那个版本试试

**Comment by DingJianhao** [comment]
好嘞。我会去试试的。
