### ISSUE TITLE
建议把命令行， 名字改为 alipan

### ISSUE THREAD

**Issue by shinvdu** [tickstep/aliyunpan#243]
建议把命令行， 名字改 alipan

linux 下面， 打aliyunpan, 这个命令太长了。    其实用alipan更合适。    网盘不都是在云上的么， 加个yun没什么用。   

我本地自己是用重命名为alipan,   只是为项目简便性， 提个建议。

**Comment by tickstep** [comment]
> 建议把命令行， 名字改 alipan
> 
> 
> 
> linux 下面， 打aliyunpan, 这个命令太长了。    其实用alipan更合适。    网盘不都是在云上的么， 加个yun没什么用。   
> 
> 
> 
> 我本地自己是用重命名为alipan,   只是为项目简便性， 提个建议。   

感谢反馈。这个名字就不改了，改名有点麻烦，很多编译脚本配置都要改。
linux下你可以用alias命令配置别名解决你的问题
也可以加环境变量用tab键补全也方便

**Comment by shinvdu** [comment]
理解^_^
