### ISSUE TITLE
命令行用logout退出无效

### ISSUE THREAD

**Issue by pda8888** [tickstep/aliyunpan#249]
使用 aiuyunpan.exe logout，回答“y"之后，在手机端的“账号与安全”的“登录设备管理”，仍然看到刚才登录的设备还在线，名称是"Chrome 浏览器“，且过了8个小时后，依然未退出。
另外，使用aliyunpan logout -y，可以实现无应答退出，这个“-y“的开关，在文档里好像未列出。但是效果完全一样，无法登出。

**Comment by tickstep** [comment]
> 使用 aiuyunpan.exe logout，回答“y"之后，在手机端的“账号与安全”的“登录设备管理”，仍然看到刚才登录的设备还在线，名称是"Chrome 浏览器“，且过了8个小时后，依然未退出。
> 另外，使用aliyunpan logout -y，可以实现无应答退出，这个“-y“的开关，在文档里好像未列出。但是效果完全一样，无法登出。

这个功能和登录设备没有关系的，这个logout是登出本客户端，密钥和用户信息在本地删除。
我看看能不能实现联动

**Comment by pda8888** [comment]
就是在cli模式下没法登出，只能退出cli客户端？

**Comment by xiaoyaofenfen** [comment]
已修复，下个版本合入
