### ISSUE TITLE
对于大文件，用 aliyunpan locate 获取的下载直链报错

### ISSUE THREAD

**Issue by pda8888** [tickstep/aliyunpan#250]
我试了一下，65M的文件，用locate获得的下载直链有效。
而实验了几个 4GB 以上的文件，均报错。
其中，在浏览器里面输入下载直链，报错的信息如下：
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>InvalidArgument</Code>
<Message>At least one of AdditionalHeaders is not in request headers.</Message>
<RequestId>63F18C8DC5BC5B38393CA0A2</RequestId>
<HostId>cn-beijing-data.aliyundrive.net</HostId>
<EC>0002-00000078</EC>
</Error>

在IDM里面输入直链下载，弹窗提示：“服务器响应显示您没有权限下载此文件。备注：HTTP/1.1 403 Forbidden“

用aria2c下载，报错信息如下：
  -> [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403

02/19 10:40:30 [NOTICE] Download GID#4dba7f262b7d4946 not complete:

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
4dba7f|ERR |       0B/s|https://cn-beijing-data.aliyundrive.net/xOU8jzTa%2F271285371%2F63eff7ca0df926fc186b44eabf20d9feb508b3ac%2F63eff7ca15a18a5f3568480a8eba6920e4877349?di=bj29&dr=271285371&f=63eff7ca0df926fc186b44eabf20d9feb508b3ac&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27WIN10-22H2-19045-2546-intel-nvidia-%25E5%25BE%25AE%25E6%2598%259F%25E7%2581%25AF%25E6%2595%2588.ESD&security-token=CAIS%2BgF1q6Ft5B2yfSjIr5fHHNnXi69LgqyFO0TDhVQ6O8IZgbHupjz2IHFPeHJrBeAYt%2FoxmW1X5vwSlq5rR4QAXlDfNWiYdQnZqVHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLukMWr%2Fwq3PIdp2ma447NWQlLnzyCMvvJ9OVDFyN0aKEnH7J%2Bq%2FzxhTPrMnpkSlacGoABRFO4opFyybx7O4ahTdxfIiuZe4geOiXLlerja5gvvL4WC1s%2BqN7fJgHC3EKZgDO1DRzKFlK1BYhueT1xsUOO4AcnKAyAkDOtK%2Ftu97z4KsNhj8iFpmHkJLcIV39UYRJy6u1rQ3CYyWVH9fc1yGxbu6z%2BMWeyZ%2BXi%2BKbLpym9D%2F8%3D&u=7783b34e78a64c20a31d42e011e08085&x-oss-access-key-id=STS.NTrWccfpj5nn9braTo7M5ntED&x-oss-additional-headers=referer&x-oss-expires=1676788570&x-oss-signature=Gkhb6KgRyHyr4IA2qUqHtLmv6v8YjnNCJvBKdd0bx5U%3D&x-oss-signature-version=OSS2

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.

**Comment by tickstep** [comment]
你用的是扫描登录么，不是扫描登录，直连下载不了了

**Comment by pda8888** [comment]
我是用的aliyunpan.exe -login --RefreshToken=xxxxxxxxxxxxx 的方式登录的。

**Comment by pda8888** [comment]
写错了，是我是用的aliyunpan.exe login --RefreshToken=xxxxxxxxxxxxx 的方式登录的。

**Comment by tickstep** [comment]
> 写错了，是我是用的aliyunpan.exe login --RefreshToken=xxxxxxxxxxxxx 的方式登录的。

这个不行，得用这个
login -QrCode

**Comment by pda8888** [comment]
哦，有点麻烦，是要生成新的RefreshToken吗？那么原来的RefreshToekn是否会失效呢？
如果就用aliyunpan.exe login --RefreshToken=xxxxxxxxxxxxx 的方式登录，可以任何文件的直链就好了。

**Comment by xiaoyaofenfen** [comment]
> 哦，有点麻烦，是要生成新的RefreshToken吗？那么原来的RefreshToekn是否会失效呢？ 如果就用aliyunpan.exe login --RefreshToken=xxxxxxxxxxxxx 的方式登录，可以任何文件的直链就好了。

RefreshToken没关系的，都是2个小时就过期的。用扫码登录也很快，你可以试试： login -QrCode。
aliyunpan.exe login --RefreshToken=xxxxxxxxxxxxx 这种登录不行是因为阿里那边有现在，这个改不了了
