### ISSUE TITLE
建立文件夹出现异常，使用官方客户端能够建立

### ISSUE THREAD

**Issue by DolphinSh** [tickstep/aliyunpan#251]
`aliyunpan:test 开心杨99$ mkdir 301003-#网易cc- #小燃燃 竖屏收藏。
创建文件夹成功:  /test/301003-#网易cc-
`
建立的文件夹只有部分。301003-#网易cc-

**Comment by DolphinSh** [comment]
后面确定了下具体原因，是因为文件名中带空格。
我使用的平台是windows11。

**Comment by tickstep** [comment]
> 后面确定了下具体原因，是因为文件名中带空格。
> 我使用的平台是windows11。

加引号即可
```
$ mkdir "301003-#网易cc- #小燃燃 竖屏收藏"
```
