### ISSUE TITLE
not available overseas

### ISSUE THREAD

**Issue by leoxu1007** [tickstep/aliyunpan#254]
Could you please make a copy of the http://file.tickstep.com/rpm/aliyunpan/aliyunpan.repo to github or somewhere else?
It is not available to access China's Aliyun from Japan now...

**Comment by leoxu1007** [comment]
I tried several times to yum update on my machine ( CentOS ) and finally found that there is no trace route to China.
Maybe it is just the 两种全会 matters, because the source code directly downloaded from github still works...

**Comment by tickstep** [comment]
We now use cloudflare proxy to speed up the access for overseas users, you can try it right now.
