### ISSUE TITLE
各位大神们，这个登录后，会占用一个登录设备，如何解决设备限制问题？

### ISSUE THREAD

**Issue by sbwml** [tickstep/aliyunpan#256]
我有在 GitHub Actions 上使用阿里云盘上传文件的需求，有什么方法避免登录设备过多问题吗？毕竟他们官方限制了10设备

```shell
#!/bin/bash
aliyun_token=$(curl -s https://xxxxxxxxxxxxx/token.txt | openssl enc -aes-25xxxxxxxxxxxx)
echo $aliyun_token | ./aliyunpan login
```
![image](https://user-images.githubusercontent.com/16485166/221453916-555d6a27-bb44-4e70-87e4-80e7b4df0830.png)
![image](https://user-images.githubusercontent.com/16485166/221454538-ce78ba14-fcbe-4642-808f-1000829f169a.png)

像这样，只要登录成功，它就会占用一个设备。如果前面已经跑10次工作流后，那么第11次的时候肯定是登录失败了。这种情况如果解决它？

**如果给程序加上登录退出的话**，就方便了，这样在工作流上传任务完成后，进行退登操作，那么这个设备就会在已登录列表消失，就和 app 上退出账号那样，那就可以奔放使用自动化操作了。

**Comment by pda8888** [comment]
是的，我也遇到这个问题，且提出过，期待作者大大在下一次更新解决。
另：作者大大好像说过，不用RefreshToken登录，用扫描二维码方式登录，就可以退出。

**Comment by sbwml** [comment]
> 是的，我也遇到这个问题，且提出过，期待作者大大在下一次更新解决。
> 另：作者大大好像说过，不用RefreshToken登录，用扫描二维码方式登录，就可以退出。

我在github 自动化工作流上根本无法实现扫码，只能token，token的话我在服务器每隔12小时刷新一次，以文本加密的方式通过公网提供给需要aliyunpan 上传的场景使用

**Comment by jjling2011** [comment]
试过commit 828c1fe39aee90b0767c5c7167e6a1998b2aac88 了吗？

**Comment by xiaoyaofenfen** [comment]
可以设置device-id的，你可以专门预留一个device-id给所有工作流用就可以了。
每次用的时候设置一下device-id，这样所有工作流都是同一个device-id
```
aliyunpan config set -device_id=I8TJEWjZYkWcTqS86K2ijqcH
```

下个版本会增加logout登出设备的功能，你用完之后登出就可以了，这样就不会占用登录客户端数量了

**Comment by sbwml** [comment]
> 

牛逼   期待    😚

**Comment by sbwml** [comment]
> 专门预留一个device-id给所有工作流用

谢谢大佬的思路，经测试，效果非常显著

**Comment by sbwml** [comment]
但是目前在不同目录上使用非常局限，当前的版本它只需使用程序相对路径下的配置，假如操作已经超出 aliyunpan 程序所在的位置，就无法继续使用它了。

假如它具备默认的配置文件路径，如：~/.config/aliyunpan_config.json

那么 aliyunpan 就可以直接将其作为系统变量去使用，对于习惯 cli 操作的群人那种体验飞跃式提升。

**Comment by sbwml** [comment]
抱歉！我自己的问题    没看完整readme   https://github.com/tickstep/aliyunpan#%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE%E7%9B%AE%E5%BD%95  它具备了配置定义
