### ISSUE TITLE
文件夹下载的一些建议的优化

### ISSUE THREAD

**Issue by Hao-Wang-Henry** [tickstep/aliyunpan#26]
谢谢大佬的程序！

我是试图在阿里云盘上得网页版下载一整个文件夹，但是文件夹内文件数目非常多，下载总是失败。后来查了才知道，阿里云对下载的限制是一次最多一千个文件。这个是在是太坑了，如果是文件多的话，基本就相当于进去出不来了。但是幸好找到了大佬的程序，本来我以为您的程序的逻辑也会受到单次下载1000文件的限制，我得计划是找到您程序之后，自己写一个自动化的流程。但是我后来发现省事了，因为您程序的逻辑是直接扫描所有文件，并逐个文件下载。至此，您的程序完美解决了我得问题！

我写这个建议是建议您可以对某些文件实行云盘得压缩下载的策略。（网盘是把所有的文件整理起来打包下载）提出这个建议的原因是，既然云盘设置了单次下载最多一千文件的限制，就说明后续可能打压您的这个“扫描并下载所有文件”的操作，或封号，或强制断开连接。所以为了程序以后可以更鲁棒。另外我也认为单次下载大文件会比单次重复下载小文件要更快。

**Comment by tickstep** [comment]
感谢反馈
应该问题不大，这种遍历的方式下载模拟的是单次下载的方式，理论上应该是比较安全的。
压缩的方式，因为阿里的接口经常会改，现在不太想做，等阿里正式版发布了，接口稳定之后再考虑做了。

**Comment by Hao-Wang-Henry** [comment]
感谢回复，目前有一个新问题

下载的时候，会首先遍历所有文件、文件夹，但是遍历经常不全。同时，有的时候运行  ls  命令也无法展示文件夹内的条目而返回空地址（我觉得两者是一回事），所以这样遍历的时候可能把某个非空文件夹返回空的，这样就失去了这个节点的所有子节点。

我目前自己想的解决方案是，重复进行几次下载，因为我理解文件夹的“空访问”是有概率的，多次重复返回空的概率很低，但是还是觉得心里没底。一个优化的建议是，如果遇到了空文件夹，可以多次尝试一下，或等待几秒延迟访问，或遇到空文件夹则重复访问三次。最终，输出“所有空文件夹路径”到console

**Comment by yugu91** [comment]
确实有空文件的情况，网页app打开的时候也有这个情况，会让重试
之前我用另一套webdav 挂载rclone 来同步，随机清空文件夹然后又重新下载

**Comment by xiaoyaofenfen** [comment]
> 感谢回复，目前有一个新问题
> 
> 下载的时候，会首先遍历所有文件、文件夹，但是遍历经常不全。同时，有的时候运行 ls 命令也无法展示文件夹内的条目而返回空地址（我觉得两者是一回事），所以这样遍历的时候可能把某个非空文件夹返回空的，这样就失去了这个节点的所有子节点。
> 
> 我目前自己想的解决方案是，重复进行几次下载，因为我理解文件夹的“空访问”是有概率的，多次重复返回空的概率很低，但是还是觉得心里没底。一个优化的建议是，如果遇到了空文件夹，可以多次尝试一下，或等待几秒延迟访问，或遇到空文件夹则重复访问三次。最终，输出“所有空文件夹路径”到console

这个应该是阿里接口访问限流导致，太频繁调接口会限流，网页上频繁刷新页面也会遇到。这个只能增加延迟和重试避免触发限流
