### ISSUE TITLE
只同步文件夹不同步文件

### ISSUE THREAD

**Issue by lym0929** [tickstep/aliyunpan#261]
新建的文件夹都同步了，但是文件夹里面的文件全都不同步，里面的文件也很小 是新建来测试的，只有几 KB 大小。
我不放在文件夹里，放在同步的根目录也是一样 不同步。

新建文件夹基本是十几秒就同步了，但是 几KB 的文件等了几十分钟都没同步。

**Comment by lym0929** [comment]
用的linux  centos7.4, 搭建的阿里云盘docker版（tickstep/aliyunpan-sync），设置只上传

**Comment by 1351383118** [comment]
我用docker也是只同步文件夹。而且文件夹新建也不会同步，只有重启docker的时候才会同步。log有上传文件的记录，但是几条之后就没有任何输出，看了下网速只有第一条log出现的时候有几十k，剩下的都是几k了。和你一样测试几遍都不好使。

**Comment by lym0929** [comment]
> 我用docker也是只同步文件夹。而且文件夹新建也不会同步，只有重启docker的时候才会同步。log有上传文件的记录，但是几条之后就没有任何输出，看了下网速只有第一条log出现的时候有几十k，剩下的都是几k了。和你一样测试几遍都不好使。

我第一次部署之后是这样，过了第二天之后发现数据已经同步好了，可能是第一次同步有点慢，你部署之后放个大文件在里面  看看第二天同步成功了没有。

**Comment by 1351383118** [comment]
> 

好的，不过我文件也就100m左右，一晚上搞不定的话，大概率是凉凉
