### ISSUE TITLE
你账号已超出最大登录设备数量

### ISSUE THREAD

**Issue by Martinits** [tickstep/aliyunpan#269]
报错：
你账号已超出最大登录设备数量，请先下线一台设备，然后重启本应用，才可以继续使用
我已经退出所有其他设备了，怎么还是这个报错

**Comment by xiaoyaofenfen** [comment]
你得在这里退出才行，教程如下

https://github.com/tickstep/aliyunpan#%E5%A6%82%E4%BD%95%E7%99%BB%E5%87%BA%E5%92%8C%E4%B8%8B%E7%BA%BF%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by Martinits** [comment]
> 你得在这里退出才行，教程如下
> 
> https://github.com/tickstep/aliyunpan#%E5%A6%82%E4%BD%95%E7%99%BB%E5%87%BA%E5%92%8C%E4%B8%8B%E7%BA%BF%E5%AE%A2%E6%88%B7%E7%AB%AF

哦谢谢

**Comment by zhengyaoyaoyao** [comment]
我已经按照教程退出了所有设备，但是登录还是显示超出最大设备。这是为什么？

**Comment by xiaoyaofenfen** [comment]
得重启应用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月17日(周二) 上午10:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tickstep/aliyunpan] 你账号已超出最大登录设备数量 (Issue #269)




 
我已经按照教程退出了所有设备，但是登录还是显示超出最大设备。这是为什么？
