### ISSUE TITLE
一个文件夹内的子文件夹超过501再次创建子文件夹就会报错。

### ISSUE THREAD

**Issue by Adoirsa** [tickstep/aliyunpan#276]
创建文件夹失败：invalid character 'T' looking for beginning of value

**Comment by Adoirsa** [comment]
我怀疑是创建子文件夹会先去判断有没有相同名字的文件夹已经存在，然后每次调用接口只会获取100个子文件夹，到第六次的时候就会因为速度过快被接口限制，然后报错

**Comment by Handgrip** [comment]
我也一直这样，感谢定位了问题😘

**Comment by tickstep** [comment]
> 我怀疑是创建子文件夹会先去判断有没有相同名字的文件夹已经存在，然后每次调用接口只会获取100个子文件夹，到第六次的时候就会因为速度过快被接口限制，然后报错

确实是被风控导致失败。已修复，下个版本合入
