### ISSUE TITLE
登录失败:  invalid character 'T' looking for beginning of value

### ISSUE THREAD

**Issue by chengjuzhen** [tickstep/aliyunpan#277]
出现如下问题（token过期之后，换新的token，就发现不能用了）：

登录失败:  invalid character 'T' looking for beginning of value

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/19363563/226095584-31362f87-f014-4335-b3fa-4a66d2137956.png">

**Comment by auqhjjqdo** [comment]
我这边也遇到了这个bug，在使用同步备份时遇到的个别文件上传失败报错
![image](https://user-images.githubusercontent.com/84632728/226122310-68655231-e964-4d40-92ae-6690ef8e88c0.png)

**Comment by Handgrip** [comment]
+1 上传的时候报错：
```
[1] 2023-03-20 18:11:23 文件上传结果： 失败！检测同名文件失败,invalid character 'T' looking for beginning of value 耗时 17秒
```

**Comment by tickstep** [comment]
做了些优化，应该能减少出现的概率，下个版本合入
