### ISSUE TITLE
长目录名备份时崩溃

### ISSUE THREAD

**Issue by lcsuper** [tickstep/aliyunpan#28]
0.0.6-win-x64 版本，win7系统

`D:\Program Files\aliyunpan-v0.0.6-windows-x64>aliyunpan backup D:/Program Files/aliyunpan-v0.0.6-windows-x64/backup /test
panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x18 pc=0x851158]
goroutine 28 [running]:
github.com/tickstep/aliyunpan/internal/command.checkPath(0xc0000c2060, 0x29, 0x0, 0x0, 0x0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/backup.go:226 +0x378
github.com/tickstep/aliyunpan/internal/command.Backup.func1(0xc000446fb0, 0xc0000a0000, 0xc00031d9e0, 0xc0000ac0d0, 0x5, 0xc00030fb78, 0xc0000c2060, 0x29)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/backup.go:281 +0x6ecreated by github.com/tickstep/aliyunpan/internal/command.Backup
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/backup.go:279 +0x557
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x851158]

goroutine 27 [running]:
github.com/tickstep/aliyunpan/internal/command.checkPath(0xc0000ac0a0, 0xa, 0x0,0x0, 0x0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/backup.go:226 +0x378
github.com/tickstep/aliyunpan/internal/command.Backup.func1(0xc000446fb0, 0xc0000a0000, 0xc00031d9e0, 0xc0000ac0d0, 0x5, 0xc00030fb78, 0xc0000ac0a0, 0xa)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/backup.go:281 +0x6e
created by github.com/tickstep/aliyunpan/internal/command.Backup
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/backup.go:279 +0x557`

换成短目录就行了，不知道是否是program~1的问题

**Comment by xiaoyaofenfen** [comment]
backup命令不再维护了，使用sync命令试试
