### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Jeekate** [tickstep/aliyunpan#3]
环境：树莓派3b， armv7内核，ping百度首页46ms，windows10端putty ssh登录

其他功能测试正常，不能登录，信息如下
pi@pi:~/jk/ftp/ftpuser/download $ sudo aliyunpan login
请输入RefreshToken, 回车键提交 > a8566575feb14442825f4b30dd######
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x3e1780]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/command.CmdLogin.func1(0x10f4580, 0x86b7e0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/internal/command/login.go:52 +0x114
github.com/urfave/cli.HandleAction(0x43cb38, 0x4d99bc, 0x10f4580, 0x10f4580, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x10c
github.com/urfave/cli.Command.Run(0x4b0ab0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4bd459, 0x18, 0x0, ...)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3f4
github.com/urfave/cli.(*App).Run(0x11fefc0, 0x10a4010, 0x2, 0x2, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/main.go:506 +0xb58

**Comment by ixingzi** [comment]
the same issuer

**Comment by Jeekate** [comment]
> > 环境：树莓派3b， armv7内核，ping百度首页46ms，windows10端putty ssh登录
> > 其他功能测试正常，不能登录，信息如下
> > pi@pi:~/jk/ftp/ftpuser/download $ sudo aliyunpan login
> > 请输入RefreshToken, 回车键提交 > a8566575feb14442825f4b30dd######
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x3e1780]
> > goroutine 1 [running]:
> > github.com/tickstep/aliyunpan/internal/command.CmdLogin.func1(0x10f4580, 0x86b7e0, 0x0)
> > /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/internal/command/login.go:52 +0x114
> > github.com/urfave/cli.HandleAction(0x43cb38, 0x4d99bc, 0x10f4580, 0x10f4580, 0x0)
> > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x10c
> > github.com/urfave/cli.Command.Run(0x4b0ab0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4bd459, 0x18, 0x0, ...)
> > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3f4
> > github.com/urfave/cli.(*App).Run(0x11fefc0, 0x10a4010, 0x2, 0x2, 0x0, 0x0)
> > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
> > main.main()
> > /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/main.go:506 +0xb58
> 
> 这个有一直登录不成功呢？还是之前有成功过，后面就不行了？

一直不行，只能在Windows环境登录，树莓派Linux无法登录，不管是在树莓派主机还是ssh都不行

**Comment by xiaoyaofenfen** [comment]
> > > 环境：树莓派3b， armv7内核，ping百度首页46ms，windows10端putty ssh登录
> > > 其他功能测试正常，不能登录，信息如下
> > > pi@pi:~/jk/ftp/ftpuser/download $ sudo aliyunpan login
> > > 请输入RefreshToken, 回车键提交 > a8566575feb14442825f4b30dd######
> > > panic: runtime error: invalid memory address or nil pointer dereference
> > > [signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x3e1780]
> > > goroutine 1 [running]:
> > > github.com/tickstep/aliyunpan/internal/command.CmdLogin.func1(0x10f4580, 0x86b7e0, 0x0)
> > > /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/internal/command/login.go:52 +0x114
> > > github.com/urfave/cli.HandleAction(0x43cb38, 0x4d99bc, 0x10f4580, 0x10f4580, 0x0)
> > > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x10c
> > > github.com/urfave/cli.Command.Run(0x4b0ab0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4bd459, 0x18, 0x0, ...)
> > > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3f4
> > > github.com/urfave/cli.(*App).Run(0x11fefc0, 0x10a4010, 0x2, 0x2, 0x0, 0x0)
> > > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
> > > main.main()
> > > /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/main.go:506 +0xb58
> > 
> > 
> > 这个有一直登录不成功呢？还是之前有成功过，后面就不行了？
> 
> 一直不行，树莓派Linux无法登录，不管是在树莓派主机还是ssh都不行，所有版本都试过了，只能识别【armv5】和【armv7】两个版本，都不能登录
> 
> 腾讯云服务器cent os环境可用 【aliyunpan-v0.0.1-linux-amd64】版本正常登录，但是用【cat /proc/cpuinfo】查看服务器cpu信息显示【Inter(R) Xeon(R) Platinum 8255C】，amd和inter搞混了？或者是tx的锅？

那就是【armv5】和【armv7】的有问题了，我们先看看怎么跟进，手头暂时没有这种设备。
【amd64】这个是指的是64位指令集，amd和intel的CPU都是支持的这个指令集，所以都能用没有问题。

**Comment by tickstep** [comment]
> 环境：树莓派3b， armv7内核，ping百度首页46ms，windows10端putty ssh登录
> 
> 其他功能测试正常，不能登录，信息如下
> pi@pi:~/jk/ftp/ftpuser/download $ sudo aliyunpan login
> 请输入RefreshToken, 回车键提交 > a8566575feb14442825f4b30dd######
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x3e1780]
> 
> goroutine 1 [running]:
> github.com/tickstep/aliyunpan/internal/command.CmdLogin.func1(0x10f4580, 0x86b7e0, 0x0)
> /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/internal/command/login.go:52 +0x114
> github.com/urfave/cli.HandleAction(0x43cb38, 0x4d99bc, 0x10f4580, 0x10f4580, 0x0)
> /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x10c
> github.com/urfave/cli.Command.Run(0x4b0ab0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4bd459, 0x18, 0x0, ...)
> /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3f4
> github.com/urfave/cli.(*App).Run(0x11fefc0, 0x10a4010, 0x2, 0x2, 0x0, 0x0)
> /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
> main.main()
> /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/main.go:506 +0xb58

尝试修复了一版，帮忙验证下是否OK。下面是秒传链接，你用aliyunpan的工具导入到自己网盘然后再下载就可以了。

aliyunpan://aliyunpan-v0.0.1-linux-armv5-tmp.zip|E3240F87FB2892D63487C42E6E77D6F5206221BA|3118557|
aliyunpan://aliyunpan-v0.0.1-linux-armv7-tmp.zip|3C4782E3C84AF00B4437F7E0B7146F955F13B6BD|3100945|

**Comment by tickstep** [comment]
> the same issuer

有空请帮忙验证下是否OK。下面是秒传链接，你用aliyunpan的工具导入到自己网盘然后再下载就可以了。

aliyunpan://aliyunpan-v0.0.1-linux-armv5-tmp.zip|E3240F87FB2892D63487C42E6E77D6F5206221BA|3118557|
aliyunpan://aliyunpan-v0.0.1-linux-armv7-tmp.zip|3C4782E3C84AF00B4437F7E0B7146F955F13B6BD|3100945|

**Comment by Jeekate** [comment]
> > 环境：树莓派3b， armv7内核，ping百度首页46ms，windows10端putty ssh登录
> > 其他功能测试正常，不能登录，信息如下
> > pi@pi:~/jk/ftp/ftpuser/download $ sudo aliyunpan login
> > 请输入RefreshToken, 回车键提交 > a8566575feb14442825f4b30dd######
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x3e1780]
> > goroutine 1 [running]:
> > github.com/tickstep/aliyunpan/internal/command.CmdLogin.func1(0x10f4580, 0x86b7e0, 0x0)
> > /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/internal/command/login.go:52 +0x114
> > github.com/urfave/cli.HandleAction(0x43cb38, 0x4d99bc, 0x10f4580, 0x10f4580, 0x0)
> > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x10c
> > github.com/urfave/cli.Command.Run(0x4b0ab0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4bd459, 0x18, 0x0, ...)
> > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x3f4
> > github.com/urfave/cli.(*App).Run(0x11fefc0, 0x10a4010, 0x2, 0x2, 0x0, 0x0)
> > /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x54c
> > main.main()
> > /Users/tickstep/Documents/Workspace/go/projects/aliyunpan-go/main.go:506 +0xb58
> 
> 尝试修复了一版，帮忙验证下是否OK。下面是秒传链接，你用aliyunpan的工具导入到自己网盘然后再下载就可以了。
> 
> aliyunpan://aliyunpan-v0.0.1-linux-armv5-tmp.zip|E3240F87FB2892D63487C42E6E77D6F5206221BA|3118557|
> aliyunpan://aliyunpan-v0.0.1-linux-armv7-tmp.zip|3C4782E3C84AF00B4437F7E0B7146F955F13B6BD|3100945|

两个版本测试均能登录，非常感谢
