### ISSUE TITLE
配置文件和历史命令可以存放在 `~/.config/aliyunpan/` 下，或者增加一个选项可以选择配置文件的位置

### ISSUE THREAD

**Issue by taicaile** [tickstep/aliyunpan#30]
Hello,

目前 `aliyunpan` 的配置文件和历史命令都是和程序放在同一个目录下，有些情况使用起来可能不太方便。

例如对于 Linux 用户来说，可执行文件放在了 `/usr/local/bin` 目录下(多用户使用的话)。如果不加 `sudo`，会提示无法加载配置文件。

```text
FATAL ERROR: config file error: config file permission denied
```

建议修改默认配置文件位置，或者添加可以额外指定配置文件位置的选项。

（现在是把程序放在了 `~/bin` 下

**Comment by tickstep** [comment]
设置一个ALIYUNPAN_CONFIG_DIR环境变量就可以了，例如

export ALIYUNPAN_CONFIG_DIR=/home/tickstep/tools/aliyunpan/config
