### ISSUE TITLE
登出有问题，logout完，阿里云那边还是显示登陆

### ISSUE THREAD

**Issue by jj-a-li** [tickstep/aliyunpan#308]
不能正常退出登陆，很快就十个设备满了

**Comment by xiaoyaofenfen** [comment]
你使用的是最新版本吗？我试了一下是可以退出的

**Comment by jj-a-li** [comment]
阿里云服务器中使用默认镜像启动系统，安装好你的代码后登录阿里云盘，关机登出后，本地登录阿里云盘，那边显示服务器端仍在登录中，很快就登满十个要手动验证登出

**Comment by xiaoyaofenfen** [comment]
这个现在没法实现自动登出了，阿里那边强制进行手机验证了
