### ISSUE TITLE
如何批量下载相册所有文件  两万多张照片==

### ISSUE THREAD

**Issue by canxunwangluo** [tickstep/aliyunpan#312]
如何批量下载相册所有文件  两万多张照片==

**Comment by redyuan43** [comment]
同问

**Comment by z2z63** [comment]
提个意见，可以增加一个通配符的功能，比如
```
ls *.jpg
```
可以列出所有jpg扩展名的文件
```
download *.jpg
```
可以下载所有jpg扩展名的文件
```
mv *.jpg /path/to/xxx
```
可以把所有jpg文件移动到某个路径

这样就能解决一些常见的批量问题

**Comment by z2z63** [comment]
草率了，文档中提到了如何使用通配符


> 	下载的文件默认保存到, 程序所在目录的 download/ 目录。支持软链接文件，包括Linux/macOS(ln命令)和Windows(mklink命令)创建的符号链接文件。
	通过 aliyunpan config set -savedir <savedir>, 自定义保存的目录。
	支持多个文件或目录下载.
	自动跳过下载重名的文件!

	示例:

	设置保存目录, 保存到 D:\Downloads
	注意区别反斜杠 "\" 和 斜杠 "/" !!!
	aliyunpan config set -savedir D:\\Downloads
	或者
	aliyunpan config set -savedir D:/Downloads

	下载 /我的资源/1.mp4
	aliyunpan download /我的资源/1.mp4

	下载 /我的资源 目录下面所有的mp4文件，使用通配符
	aliyunpan download /我的资源/*.mp4

	下载 /我的资源 整个目录!!
	aliyunpan download /我的资源

	下载 /我的资源 整个目录，但是排除所有的jpg文件
	aliyunpan download -exn "\.jpg$" /我的资源

	下载 /我的资源/1.mp4 并保存下载的文件到本地的 d:/panfile
	aliyunpan download --saveto d:/panfile /我的资源/1.mp4

  参考：
    以下是典型的排除特定文件或者文件夹的例子，注意：参数值必须是正则表达式。在正则表达式中，^表示匹配开头，$表示匹配结尾。
    1)排除@eadir文件或者文件夹：-exn "^@eadir$"
    2)排除.jpg文件：-exn "\.jpg$"
    3)排除.号开头的文件：-exn "^\."
    4)排除~号开头的文件：-exn "^~"
    5)排除 myfile.txt 文件：-exn "^myfile.txt$"

**Comment by xiaoyaofenfen** [comment]
个人相册的文件下载，在下个版本合入，目前已经开发完成，支持一条命令下载指定相册的所有文件并保存到本地同名文件夹中。下个版本可以试试用用看

**Comment by xiaoyaofenfen** [comment]
新版本已发布
