### ISSUE TITLE
【无法登录】Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by horizon86** [tickstep/aliyunpan#317]
```
[2023-6-29 10:44:21.405] use config dir:  /home/jcdu/.local/applications/aliyunpan-v0.2.7-linux-amd64
[2023-6-29 10:44:21.405] use config dir:  /home/jcdu/.local/applications/aliyunpan-v0.2.7-linux-amd64
[2023-6-29 10:44:21.407] use config dir:  /home/jcdu/.local/applications/aliyunpan-v0.2.7-linux-amd64
[2023-6-29 10:44:21.407] use config dir:  /home/jcdu/.local/applications/aliyunpan-v0.2.7-linux-amd64
[2023-6-29 10:44:21.409] 提示: 你已经开启VERBOSE调试日志

提示: 方向键上下可切换历史命令.
提示: Ctrl + A / E 跳转命令 首 / 尾.
提示: 输入 help 获取帮助.
[2023-6-29 10:44:21.409] use config dir:  /home/jcdu/.local/applications/aliyunpan-v0.2.7-linux-amd64
[2023-6-29 10:44:21.410] use config dir:  /home/jcdu/.local/applications/aliyunpan-v0.2.7-linux-amd64
aliyunpan > login -RefreshToken=*************************
[2023-6-29 10:44:44.198] do request url: https://auth.aliyundrive.com/v2/account/token
[2023-6-29 10:45:14.226] get access token error  Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
登录失败
```

**Comment by ming1201xiu** [comment]
相同的问题，不知何因

**Comment by ZiyuGuo99** [comment]
Same question. Solved by reinstalling it.

**Comment by qcmoke** [comment]
遇到了同样的问题

**Comment by ilovejs** [comment]
Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by xiaoyaofenfen** [comment]
看是不是服务器支持Ipv6，ipv6会出现这个问题。下个版本会解决

**Comment by horizon86** [comment]
> 看是不是服务器支持Ipv6，ipv6会出现这个问题。下个版本会解决

还真支持

**Comment by xiaoyaofenfen** [comment]
> > 看是不是服务器支持Ipv6，ipv6会出现这个问题。下个版本会解决
> 
> 还真支持

那你试试这个临时版本
[aliyunpan-v0.2.8-linux-amd64.zip](https://github.com/tickstep/aliyunpan/files/12844089/aliyunpan-v0.2.8-linux-amd64.zip)

**Comment by horizon86** [comment]
> aliyunpan

我现在已经把linux换成windows了，不具备测试环境了

**Comment by horizon86** [comment]
> > > 看是不是服务器支持Ipv6，ipv6会出现这个问题。下个版本会解决
> > 
> > 
> > 还真支持
> 
> 那你试试这个临时版本 [aliyunpan-v0.2.8-linux-amd64.zip](https://github.com/tickstep/aliyunpan/files/12844089/aliyunpan-v0.2.8-linux-amd64.zip)

用不用在windows上试一下

**Comment by xiaoyaofenfen** [comment]
> > aliyunpan
> 
> 我现在已经把linux换成windows了，不具备测试环境了

那可以试试这个
[aliyunpan-v0.2.8-windows-x86.zip](https://github.com/tickstep/aliyunpan/files/12844151/aliyunpan-v0.2.8-windows-x86.zip)

**Comment by horizon86** [comment]
> > > aliyunpan
> > 
> > 
> > 我现在已经把linux换成windows了，不具备测试环境了
> 
> 那可以试试这个 [aliyunpan-v0.2.8-windows-x86.zip](https://github.com/tickstep/aliyunpan/files/12844151/aliyunpan-v0.2.8-windows-x86.zip)

非常好，可以登录了。:blue_heart:

**Comment by huangqingchao** [comment]
adrive -h
Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": lookup auth.aliyundrive.com on 192.168.0.2:53: read udp 192.168.0.3:59633->192.168.0.2:53: i/o timeout
NAME:
   aliyunpan - 阿里云盘客户端 for linux/amd64

USAGE:
   adrive [global options] command [command options] [arguments...]

VERSION:
   v0.2.8

**Comment by Ki-Zhang** [comment]
使用版本v0.2.8下载到远程服务器上，远程服务器ubuntu18没有图形化界面，然后本地windows电脑获取了refreshtoken，在服务器上面登陆不了，报同样的错误Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
登录失败
是什么原因呢

**Comment by tickstep** [comment]
> 使用版本v0.2.8下载到远程服务器上，远程服务器ubuntu18没有图形化界面，然后本地windows电脑获取了refreshtoken，在服务器上面登陆不了，报同样的错误Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 
> 登录失败
> 
> 是什么原因呢

你用上面的临时版本试试，你的服务器是不是有ipv6？

**Comment by Ki-Zhang** [comment]
> > 使用版本v0.2.8下载到远程服务器上，远程服务器ubuntu18没有图形化界面，然后本地windows电脑获取了refreshtoken，在服务器上面登陆不了，报同样的错误Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> > 登录失败
> > 是什么原因呢
> 
> 你用上面的临时版本试试，你的服务器是不是有ipv6？

临时脚本是要替换原release中的aliyunpan脚本吗，它好像在服务器上运行不了也tab不出来，我的服务器支持ipv6

**Comment by tickstep** [comment]
> > > 使用版本v0.2.8下载到远程服务器上，远程服务器ubuntu18没有图形化界面，然后本地windows电脑获取了refreshtoken，在服务器上面登陆不了，报同样的错误Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> > > 登录失败
> > > 是什么原因呢
> > 
> > 
> > 你用上面的临时版本试试，你的服务器是不是有ipv6？
> 
> 临时脚本是要替换原release中的aliyunpan脚本吗，它好像在服务器上运行不了也tab不出来，我的服务器支持ipv6

直接替换 aliyunpan 这个应用程序文件就行。如果你使用 apt 安装，那就替换这个文件 /usr/local/bin/aliyunpan

**Comment by xialei123456** [comment]
> > > 看是不是服务器支持Ipv6，ipv6会出现这个问题。下个版本会解决
> > 
> > 
> > 还真支持
> 
> 那你试试这个临时版本 [aliyunpan-v0.2.8-linux-amd64.zip](https://github.com/tickstep/aliyunpan/files/12844089/aliyunpan-v0.2.8-linux-amd64.zip)

通过使用临时版解决了，感谢
