### ISSUE TITLE
我输入aliyunpan没用

### ISSUE THREAD

**Issue by yyhhkya** [tickstep/aliyunpan#320]
提示没有这个命令

**Comment by Riczzoe** [comment]
你有试试看输入 `./aliyunpan` 吗?

而且 [README.md](https://github.com/tickstep/aliyunpan#:~:text=v0.2.7%2Dlinux%2Damd64-,./aliyunpan,-apt%E5%AE%89%E8%A3%85) 有教怎么使用啊.

另外,为什么没有Linux的最基本的常识要在在Linux下使用阿里云盘的命令行工具呢? 并且这种问题随便google一下关键字[Linux Command not found](https://www.google.com/search?q=linux+command+not+found) 就能随便找到答案的啊. 例如这篇回答: [How to fix a "Command not found" error in Linux](https://www.redhat.com/sysadmin/fix-command-not-found-error-linux)

对于这个问题你可以看看一下回答:
1. [[Why when we run a executable file we need to add ./ ahead?](https://unix.stackexchange.com/questions/194142/why-when-we-run-a-executable-file-we-need-to-add-ahead)](https://unix.stackexchange.com/questions/194142/why-when-we-run-a-executable-file-we-need-to-add-ahead)
2. [What are the differences between an executable program and command in Linux?](https://www.quora.com/What-are-the-differences-between-an-executable-program-and-command-in-Linux)
