### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by PHCSJC** [tickstep/aliyunpan#324]
[0] 当前文件上传最大并发量为: 1, 上传分片大小为: 10.00MB
打开上传未完成数据库错误: panupload.UploadingDatabase.UploadingList: []*panupload.Uploading: panupload.Uploading.State: uploader.InstanceState.BlockList: []*uploader.BlockState: uploader.BlockState.readFieldHash: expect :, but found ,, error found in #1 byte of ...|,{"id":1345|..., bigger context ...|,{"id":1345,"range":{"begin":14103347200,"end":1411|...

**Comment by PHCSJC** [comment]
我把这个目录删除，重新登录就好了
/etc/aliyunpan-cmd/

**Comment by economicBYTE** [comment]
直接删除/etc/aliyunpan、目录下的upload/update开头的json文件就可以，因为之前上传的时候意外断掉就会产生一个这样一个文件，删除后重新传就好。
