### ISSUE TITLE
新版已区分为资源盘+备份盘

### ISSUE THREAD

**Issue by djanchew** [tickstep/aliyunpan#331]
![image](https://github.com/tickstep/aliyunpan/assets/42028431/6b568287-bd9f-4a98-88bb-9f4dc03d5914)

应该如何切换到资源盘的工作目录? 还是说还没支持/无法支持

**Comment by redyuan43** [comment]
同问？

**Comment by xiaoyaofenfen** [comment]
还在适配中，最近比较忙，可能得国庆假期才能开发了

**Comment by xiaoyaofenfen** [comment]
下个版本合入
