### ISSUE TITLE
下载速度骤降80%~90%，是阿里云那边限速吗

### ISSUE THREAD

**Issue by ogios** [tickstep/aliyunpan#336]
想问一下大伙，最开始下载很正常 ( 总10-20mb/s )，但是几个文件之后就变成每个文件300-500kb/s，总2mb/s以下了
这个是阿里云这边限速的原因吗

**Comment by sw586** [comment]
难兄难弟：
https://github.com/tickstep/aliyunpan/issues/338#issue-1887423755

**Comment by xiaoyaofenfen** [comment]
应该是的，开始限制速度了
