### ISSUE TITLE
这两天是不是阿里云限速了

### ISSUE THREAD

**Issue by sw586** [tickstep/aliyunpan#338]
我也发现了，这两天上传下载都是kb，下面这个图片是啊阿里云ecs上的，用新版本直接没有速度，用0.1老版本有速度但是也是kb级别，不知道什么原因，因为作者有空看看，我还了两个账号也是一样情况。
新版本经典模式和sce模式都没有速度 好奇怪

![image](https://github.com/tickstep/aliyunpan/assets/24788222/262914b2-5229-43ac-8ebb-474164fb81b8)

下面是老版本的，有速度
![image](https://github.com/tickstep/aliyunpan/assets/24788222/9915a209-b7d3-4673-a9b2-778dce1bd12e)

**Comment by Tyler913** [comment]
我也遇到了这个问题只有几百KB

**Comment by Tyler913** [comment]
确实是限速了，不是这个插件的问题，我做了个每日任务拿了个会员1天试用。速度瞬间拉满了

**Comment by sw586** [comment]
> 确实是限速了，不是这个插件的问题，我做了个每日任务拿了个会员1天试用。速度瞬间拉满了

我觉得也是

**Comment by tiny1990** [comment]
> > 确实是限速了，不是这个插件的问题，我做了个每日任务拿了个会员1天试用。速度瞬间拉满了
> 
> 我觉得也是

emm 我现在领了个一天会员 稳定在300k

**Comment by sunshine-xp** [comment]
![image](https://github.com/tickstep/aliyunpan/assets/87742741/618af2db-a03e-47e9-92af-72ab8211ce15)
感觉真限速了，以前就觉的要限速

**Comment by tiny1990** [comment]
> ![image](https://user-images.githubusercontent.com/87742741/280532408-618af2db-a03e-47e9-92af-72ab8211ce15.png) 感觉真限速了，以前就觉的要限速

退出登陆换个 token试试呢？
我换了一个 好点 稳定4MB

**Comment by sunshine-xp** [comment]
> ![image](https://user-images.githubusercontent.com/87742741/280532408-618af2db-a03e-47e9-92af-72ab8211ce15.png) 感觉真限速了，以前就觉的要限速

![image](https://github.com/tickstep/aliyunpan/assets/87742741/3108b88a-bcd4-401b-b460-6348ae275ae3)
速度恢复了，可能是昨天换了VPN节点

**Comment by XuecWu** [comment]
> > ![image](https://user-images.githubusercontent.com/87742741/280532408-618af2db-a03e-47e9-92af-72ab8211ce15.png) 感觉真限速了，以前就觉的要限速
> 
> ![image](https://private-user-images.githubusercontent.com/87742741/280658618-3108b88a-bcd4-401b-b460-6348ae275ae3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODc3MzksIm5iZiI6MTcwMjM4NzQzOSwicGF0aCI6Ii84Nzc0Mjc0MS8yODA2NTg2MTgtMzEwOGI4OGEtYmNkNC00MDFiLWI0NjAtNjM0OGFlMjc1YWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEzMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDIzYWY1M2E3OGE5MzE3NTA0MDJiNjE1N2NiYzNjYmMyMTlkNjY3NWNkNjY4Mzc5ZjJhYjJlY2ZkYWZkOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G6_C-VkKnsK50HtPzGIed6QLxtS8kc62NzAqXQY93Bw) 速度恢复了，可能是昨天换了VPN节点

@sunshine-xp 老哥你这个换节点是什么意思？你把你服务器的节点换了还是阿里那边什么的？我最近速度还是很慢，只有几百KB，以前到到10MB+

**Comment by xiaoyaofenfen** [comment]
v0.3.0新版本暂时没有限速，可以试试
