### ISSUE TITLE
重试问题

### ISSUE THREAD

**Issue by 362227** [tickstep/aliyunpan#345]
文件上传结果： 失败！检测同名文件失败,签名过期，需要更新签名密钥 耗时 13分32秒
文件上传结果： 失败！检测同名文件失败,网关错误，可能是请求的参数有误 耗时 40秒

加了--retry，这种不会重试，而且耗时太长，能不能加超时选项

**Comment by 362227** [comment]
耗时太长的原因应该知道了， 是网盘文件太多导致api list加载时间太长。

**Comment by xiaoyaofenfen** [comment]
用v0.3.0版本试试，这个版本有重试机制
