### ISSUE TITLE
没有webdev吗

### ISSUE THREAD

**Issue by ZHYxulei** [tickstep/aliyunpan#346]
要用webdev，其他的webdev没有切换库的功能，这个有，但是找不到webdev配置的东西

**Comment by tickstep** [comment]
新版本没有了，这个webdav的bug有点多，很难改，索性就不做了😫

**Comment by ZHYxulei** [comment]
> 新版本没有了，这个webdav的bug有点多，很难改，索性就不做了😫

啊?不行啊我装这个就是为了webdev啊
要不要在下一个版本中重新搞啊

**Comment by longkui-clown** [comment]
哈哈，同求，能支持webdev就好了

**Comment by longkui-clown** [comment]
代码中看到了相关代码，大佬厉害，只是没放开，已经挂上使用了
![image](https://github.com/tickstep/aliyunpan/assets/39942604/2a9cb837-3525-40ee-bfbd-246b857ab072)
![image](https://github.com/tickstep/aliyunpan/assets/39942604/764ce11f-b727-4e88-8c58-ed7d0b389201)
[aliyunpan.zip](https://github.com/tickstep/aliyunpan/files/13041842/aliyunpan.zip)

**Comment by ZHYxulei** [comment]
> 代码中看到了相关代码，大佬厉害，只是没放开，已经挂上使用了
> ![image](https://github.com/tickstep/aliyunpan/assets/39942604/2a9cb837-3525-40ee-bfbd-246b857ab072)
> ![image](https://github.com/tickstep/aliyunpan/assets/39942604/764ce11f-b727-4e88-8c58-ed7d0b389201)
> [aliyunpan.zip](https://github.com/tickstep/aliyunpan/files/13041842/aliyunpan.zip)
> 

老哥怎么搞的，出个教程行不行

**Comment by ZHYxulei** [comment]
> > > 代码中看到了相关代码，大佬厉害，只是没放开，已经挂上使用了
> > > ![image](https://github.com/tickstep/aliyunpan/assets/39942604/2a9cb837-3525-40ee-bfbd-246b857ab072)
> > > ![image](https://github.com/tickstep/aliyunpan/assets/39942604/764ce11f-b727-4e88-8c58-ed7d0b389201)
> > > [aliyunpan.zip](https://github.com/tickstep/aliyunpan/files/13041842/aliyunpan.zip)
> > 
> > 老哥怎么搞的，出个教程行不行
> 
> ---
> 分割线
> ---
> 1、用上面的aliyunpan的包运行，和大佬的包一样，只是放开了webdav，命令在图里截有，需要先登陆再执行命令，命令是启动webdav服务器的
> ```bash
> webdav start -port 8085 -webdav_user "admin" -webdav_password "admin123"
> ```
> 2、安装RaiDrivee，安装略过
> 3、添加webdav服务，挂载磁盘
> - 打开RaiDrivee，如图按钮
> ![image](https://github.com/tickstep/aliyunpan/assets/39942604/a69d99a2-a5c4-4ca3-8a14-20af8a0324de)
> - 设置服务如下步骤
> ![image](https://github.com/tickstep/aliyunpan/assets/39942604/7e42570d-fe60-4c60-b0b9-e3ab16621b9b)
> - 设置完成如下
> ![image](https://github.com/tickstep/aliyunpan/assets/39942604/5d156f6b-4d35-4922-81a2-9f5d3c8c864b)
> - 我的电脑中已经挂载成功
> ![image](https://github.com/tickstep/aliyunpan/assets/39942604/963bc574-164c-4115-98c6-e8ff5d46141f)
> 
> 

Linux系统的怎么搞😭

**Comment by longkui-clown** [comment]
@ZHYxulei 
---
分割线
---
linux包如下
[aliyunpan_linux.zip](https://github.com/tickstep/aliyunpan/files/13068669/aliyunpan_linux.zip)
---

- # 1、安装`davfs2`
    - ## 不同系统可能安装不同，可以百度，以centos7.6为例
    - ## 执行`yum -y install davfs2`
- # 2、创建挂载点
    - ## 形如 `mkdir /mnt/cloud-test`
- # 3、启动`aliyunpan`
    - ## 登陆 步骤省略
    - ## 启动webdav服务 `webdav start -port 8085 -webdav_user "admin" -webdav_password "admin123"`
    ![image](https://github.com/tickstep/aliyunpan/assets/39942604/7aa42492-469c-41bb-b0d1-ec07c387c2e4)
- # 4、挂载webdav到目录
    - ## `mount -t davfs http://localhost:8085 /mnt/cloud-test`
    - ## 挂载的路径`/mnt/cloud-test`为步骤2创建的目录
- # 5、进入目录查看挂载成功
    ![image](https://github.com/tickstep/aliyunpan/assets/39942604/e2e46f6d-8545-45ab-95c1-b3b0d2ebcac0)

**Comment by longkui-clown** [comment]
linux'上传好像有bug

**Comment by longkui-clown** [comment]
linux上有bug
@ZHYxulei
