### ISSUE TITLE
Download speed is slow(300kb/s) while it's fast(8M/s) when I connect a VPN

### ISSUE THREAD

**Issue by Tom-Teamo** [tickstep/aliyunpan#349]
I find that the download traffic does not pass through the node of my VPN. I wonder why><?

**Comment by xiaoyaofenfen** [comment]
You can set the proxy by yourself like this:
```
aliyunpan config set -proxy=http://127.0.0.1:8888
or
aliyunpan config set -proxy=socks5://127.0.0.1:8889
```

**Comment by Tom-Teamo** [comment]
I mean that the download traffic does not pass through the node of my VPN. I just open the VPN. However, the download speed raises a lot. Why? You can have a try.

**Comment by xiaoyaofenfen** [comment]
Please use new version v0.3.0 for a try. this version will be fast in theoretically.
