### ISSUE TITLE
需要增加下载超时机制，避免某些无法下载的文件一直占用下载线程

### ISSUE THREAD

**Issue by choppin** [tickstep/aliyunpan#35]
需要增加下载超时机制，避免某些无法下载的文件一直占用下载线程。
比如，某些文件被禁（ban）了后，下载时一直没有速度，然后一直在下载该文件造成下载线程阻塞。浪费大量时间。或者有没有别的办法可以自动跳过这种资源。
![2021-12-11 16-31-37屏幕截图](https://user-images.githubusercontent.com/9331042/145670198-fb03110d-014f-45a2-82e6-53276c5c1bed.png)
![2021-12-11 16-32-17屏幕截图](https://user-images.githubusercontent.com/9331042/145670201-fd01980f-9ca9-43e0-ad8b-896a88c38517.png)
。

**Comment by tickstep** [comment]
打开debug日志，下载这个文件看看日志返回什么错误

**Comment by choppin** [comment]
![
![2021-12-13 21-51-14屏幕截图](https://user-images.githubusercontent.com/9331042/145824636-e5f91144-616e-40b8-bf1c-ee1928d0aa72.png)

![2021-12-13 21-50-51屏幕截图](https://user-images.githubusercontent.com/9331042/145824589-00097985-83c8-4cca-9be7-ac3b5097aca7.png)

![2021-12-13 21-50-34屏幕截图](https://user-images.githubusercontent.com/9331042/145824582-37421325-8086-4e3e-88f3-5e53e6140f17.png)
2021-12-13 21-50-12屏幕截图](https://user-images.githubusercontent.com/9331042/145824569-e03e53f7-2c44-4a7a-88d5-5969e0fd0cb9.png)

**Comment by tickstep** [comment]
新版本已修复
