### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by 362227** [tickstep/aliyunpan#350]
0B/4.95KB(0.00%) 0B/s(0B/s) in 1h42m47s  
一个小文件，0B/s 无止境上传

**Comment by AkaiShuichi7** [comment]
我也是遇到这个问题，无止境上传小文件，而且还上传不上去，只在云端创建了文件夹

**Comment by xiaoyaofenfen** [comment]
请使用v0.3.0再试试，上传有优化
