### ISSUE TITLE
好多天了登录还是失败Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by LIU-YUXI** [tickstep/aliyunpan#351]
怎么办呀求助

**Comment by tickstep** [comment]
这是网络连不上，你的服务器支持IPv6吗？

**Comment by LIU-YUXI** [comment]
> 这是网络连不上，你的服务器支持IPv6吗？

支持的 请问我要怎么通过ipv6连上呢？

**Comment by tickstep** [comment]
> > 这是网络连不上，你的服务器支持IPv6吗？
> 
> 
> 
> 支持的 请问我要怎么通过ipv6连上呢？

#317 这个issue有临时版本，你可以试试

**Comment by LIU-YUXI** [comment]
> > > 这是网络连不上，你的服务器支持IPv6吗？
> > 
> > 
> > 支持的 请问我要怎么通过ipv6连上呢？
> 
> #317 这个issue有临时版本，你可以试试

可以的 非常感谢！

**Comment by tickstep** [comment]
> > 这是网络连不上，你的服务器支持IPv6吗？
> 
> get access token error Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2407:400a:f10::1f1]:443: connect: connection refused problem same as the title by IPv6

you can use this interim version for a try:
[aliyunpan-v0.2.8-linux-amd64-tmp.zip](https://github.com/tickstep/aliyunpan/files/13282164/aliyunpan-v0.2.8-linux-amd64-tmp.zip)

**Comment by cameronyq** [comment]
thx try it

**Comment by cameronyq** [comment]
root@mx:/home/hua/Downloads/aliyunpan-v0.2.8-linux-amd64-tmp# ./aliyunpan
bash: ./aliyunpan: Permission denied

any help!!!

**Comment by cameronyq** [comment]
failed by Ipv6. I think refused ipv6 by Ali.
Thx. everything is fine by ipv4.
well job! Thx.
