### ISSUE TITLE
同步备份功能的运作机制请教

### ISSUE THREAD

**Issue by dzki** [tickstep/aliyunpan#354]
首先感谢大神创造如此好的工具，真的太好用了，手动点赞！

我是使用sh脚本以命令行方式启动的同步备份功能，用的双向同步模式，也运行过扫描功能，sh脚本同步备份命令如下：
aliyunpan sync start -ldir "....localpath" -pdir ".....panpath" -mode "sync"
在运行脚本后文件在远程和本地能实现同步一次，但之后对于文件夹内容的修改都不会触发同步功能，除非再次运行脚本才能开始同步。
系统平台是Ubuntu 20.04.5 LTS，而且奇怪的是在aliyunpan刚更新到0.2.8时，印象中运行脚本后，对于后续文件夹内容的修改是可以同步的，不知道什么时候开始只能在运行脚本后同步一次，后面的变化就不同步了。

想请教大神这个问题是什么原因造成的？同步备份功能的运作机制是什么样的，是否只在命令运行后同步一次，还是会持续监控文件内容的变化进行同步？
还请帮忙解惑，感谢！

**Comment by xiaoyaofenfen** [comment]
Sync模式当前bug有点多，建议先用upload或者download的模式。sync模式的bug修不动了，在准备重构了

**Comment by dzki** [comment]
> Sync模式当前bug有点多，建议先用upload或者download的模式。sync模式的bug修不动了，在准备重构了

感谢大神回复，先用download模式顶一段，坐等新版发布

**Comment by dzki** [comment]
> Sync模式当前bug有点多，建议先用upload或者download的模式。sync模式的bug修不动了，在准备重构了

大神，经过两天的测试，使用download模式问题依旧，在初次运行脚本后可以同步一次，然后再次修改远程文件夹内容，可以再同步一次，之后的变动就没有反应了。
暂时使用crontab添加定时任务的方式解决，每3个小时运行一次同步命令，以下是定时任务命令格式，给有需要的伙伴参考：
0 */3 * * * killall aliyunpan
1 */3 * * * /aliyunpan sync start -ldir "/....localpath" -pdir "/....remotepath" -mode "sync"

**Comment by evoshop** [comment]
我也遇到这个问题了，只能同步一次，如果在这次同步结束之前加入新文件，是可以同步的，如果同步完成之后再加入新文件，就不会同步，你说的三小时运行一次也有点不妥，下载几十个G的电影三个小时下载不完，如果重新运行，这个电影会下载失败（这是第二个问题，表面看着这个电影是在继续下载，当电影下载完成后会变成0B）

**Comment by xiaoyaofenfen** [comment]
请使用v0.3.0新版本再试试，sync命令进行了重构。
