### ISSUE TITLE
在浏览器获取二维码的服务API的代码在哪一块

### ISSUE THREAD

**Issue by chungdz** [tickstep/aliyunpan#358]
你好，我们在使用这个开源项目的时候，扫码登陆这一部分./aliyunpan login -QrCode会访问到一个接口 https://api.tickstep.com/pages/tickstep/aliyunpan/qrcode/login。 提供这个API服务的部分的代码在这个repo的哪个位置？我们想要在自己的服务器上实现这个功能。谢谢

**Comment by xiaoyaofenfen** [comment]
这个代码没在这里，在我们另一个项目里面专门做这种OAuth授权的。包含阿里的，百度的，微软的，google这些。本质上都是oauth2.0的。你可以找找oauth2.0的资料，然后再抓下阿里云盘的网络包就能做出来了

**Comment by chungdz** [comment]
请问下你们另一个项目是哪个？我们没有接触过oauth2.0。想参考一下，谢谢。

**Comment by tickstep** [comment]
> 请问下你们另一个项目是哪个？我们没有接触过oauth2.0。想参考一下，谢谢。

不好意思，那个项目没有开源，因为有其他商用项目用了。这东西不复杂，找几篇博客就能看懂了
