### ISSUE TITLE
建立多个容器可以使用同一个设备ID吗？还是必须用不同的？

### ISSUE THREAD

**Issue by shanyan-wcx** [tickstep/aliyunpan#359]
如题。

**Comment by xiaoyaofenfen** [comment]
我记得是不能，阿里那边的机制是同一个设备ID只能最后一个在线，其他的token会被注销不能用没法上传下载

**Comment by shanyan-wcx** [comment]
> 我记得是不能，阿里那边的机制是同一个设备ID只能最后一个在线，其他的token会被注销不能用没法上传下载

好的，感谢。
