### ISSUE TITLE
能否支持一个docker容器同步多个目录呢？

### ISSUE THREAD

**Issue by shanyan-wcx** [tickstep/aliyunpan#361]
现在想要同步多个目录需要给每个目录开一个容器，感觉不太方便，还占用登陆设备数量。

**Comment by birdxs** [comment]
我也有这个需求，希望大佬能抽空搞一下

**Comment by birdxs** [comment]
> 现在想要同步多个目录需要给每个目录开一个容器，感觉不太方便，还占用登陆设备数量。

试了下sync_handler.js 插件，查看文档的说明也只有针对文件的关键词屏蔽。目前没摸索出屏蔽某个文件夹的配置。

**Comment by xiaoyaofenfen** [comment]
可以支持的，但是需要手动编辑sync_drive_config.json这个文件然后映射给docker容器使用
“”“
配置文件需要保存在：(配置目录)/sync_drive/sync_drive_config.json，样例如下：

{
 "configVer": "1.0",
 "syncTaskList": [
  {
   "name": "设计文档备份",
   "localFolderPath": "D:/tickstep/Documents/设计文档",
   "panFolderPath": "/备份盘/我的文档",
   "mode": "upload",
   "driveName": "backup"
  },
  {
   "name": "手机图片备份",
   "localFolderPath": "D:/tickstep/Photos/手机图片",
   "panFolderPath": "/备份盘/手机图片",
   "mode": "upload",
   "driveName": "resource"
  }
 ]
}

相关字段说明如下：
name - 任务名称
localFolderPath - 本地目录
panFolderPath - 网盘目录
mode - 模式，支持: upload(备份本地文件到云盘),download(备份云盘文件到本地)
driveName - 网盘，支持：backup(备份盘), resource(资源盘)
”“”

在docker-compose.yml命令需要映射
"""
version: '3'
services:
  sync:
    image: tickstep/aliyunpan-sync:<tag>
    container_name: aliyunpan-sync
    restart: always
    volumes:
 # （推荐）挂载sync_drive同步数据库到本地，这样即使容器销毁，同步数据库还可以用于以后使用
      #- ./sync_drive:/home/app/config/sync_drive
"""

详细可以参考：https://github.com/tickstep/aliyunpan/blob/main/docs/manual.md#%E5%90%8C%E6%AD%A5%E5%A4%87%E4%BB%BD%E5%8A%9F%E8%83%BD
