### ISSUE TITLE
关于同步功能的疑问

### ISSUE THREAD

**Issue by runishiwo** [tickstep/aliyunpan#363]
双向同步功能的优先级参数只针对同名文件有效
我想把本地的文件强制覆盖到云盘上，比如本地有增删的话云盘同步增删，好像不能实现
而且sync命令的同步间隔多久呢？

我现在是使用定时任务脚本
在执行upload到阿里云盘时会先把云盘对应目录下的所有文件删除（不太会编脚本，不会直接用脚本删除云盘里超过30天的文件，所以在本地的目录做了只保留30天的文件的脚本）
然后再上传本地文件到对应目录，来保证本地和云盘内的文件完全一致

**Comment by xiaoyaofenfen** [comment]
双向同步的模式目前有很多问题，如果需要删除的是目前只能使用rm命令进行，然后再同步。你的用脚本的思路是OK的。
