### ISSUE TITLE
运行过程中有时候会自己停止

### ISSUE THREAD

**Issue by shanyan-wcx** [tickstep/aliyunpan#364]
日志是这样的
bytes.(*Buffer).ReadFrom(0xc0000a6278, 0xf11080, 0xc000210150, 0x40b6a5, 0xc26840, 0xcbb7a0)
        /usr/local/go/src/bytes/buffer.go:204 +0xbe
crypto/tls.(*Conn).readFromUntil(0xc0000a6000, 0xf12260, 0xc00042e018, 0x5, 0xc00042e018, 0x100011e36)
        /usr/local/go/src/crypto/tls/conn.go:798 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0000a6000, 0x0, 0x0, 0x438ffc)
        /usr/local/go/src/crypto/tls/conn.go:605 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:573
crypto/tls.(*Conn).Read(0xc0000a6000, 0xc0007f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1276 +0x165
net/http.(*persistConn).Read(0xc000262360, 0xc0007f9000, 0x1000, 0x1000, 0xc0003ac360, 0xc000917d40, 0x405755)
        /usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc000a52cc0)
        /usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000a52cc0, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
        /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc000262360)
        /usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1743 +0xc77

goroutine 1374 [select]:
net/http.(*persistConn).writeLoop(0xc000262360)
        /usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1744 +0xc9c

**Comment by xiaoyaofenfen** [comment]
这日志看的全是网络的报错，看不出啥问题了
