### ISSUE TITLE
准备长时间下载，结果不久就下载失败了。

### ISSUE THREAD

**Issue by choppin** [tickstep/aliyunpan#37]
不知道为什么下载的时候下着下着就失败了。有时候下载1个多小时就失败了，有时候下载4，5小时就不行了。附件中的前4个图是晚上下载了4个多小时就下失败了的截图，后面4张是早上重新执行下载，然后支上班了，回来一看，只下载了1个多小时就失败了。白费了一天时间。最后一张是设置的参数情况。我使用的系统是debian 10
![2021-12-17 06-40-22屏幕截图](https://user-images.githubusercontent.com/9331042/146545330-1597c546-7405-4ffb-bf06-d9bb82dd14de.png)
![2021-12-17 06-40-45屏幕截图](https://user-images.githubusercontent.com/9331042/146545621-26525758-e387-4f1c-b210-ab75a3e476a8.png)
![2021-12-17 06-41-25屏幕截图](https://user-images.githubusercontent.com/9331042/146545624-55cb4636-a895-4031-b430-47014f322548.png)
![2021-12-17 06-41-57屏幕截图](https://user-images.githubusercontent.com/9331042/146545627-a8db1aee-aa58-4de5-a578-82d76e6b6627.png)
![2021-12-17 20-27-43屏幕截图](https://user-images.githubusercontent.com/9331042/146545630-e27082d6-4610-4b2e-a9d4-9d089cf23ec3.png)
![2021-12-17 20-28-02屏幕截图](https://user-images.githubusercontent.com/9331042/146545631-d5810fa4-da8c-49ce-bd33-48f90cb07d97.png)
![2021-12-17 20-28-44屏幕截图](https://user-images.githubusercontent.com/9331042/146545632-6faaf074-140b-4a50-a735-617a053f252f.png)
![2021-12-17 20-28-58屏幕截图](https://user-images.githubusercontent.com/9331042/146545633-747e3972-fc5e-4211-8b35-bba6dffb60ed.png)
![2021-12-17 20-35-18屏幕截图](https://user-images.githubusercontent.com/9331042/146545635-2fc44f98-9181-4adc-a0a7-03e69b102c8f.png)

**Comment by choppin** [comment]
可能是因为我开了多个窗口同时下载文件造成的，只开一个窗口下载好像就没有这个问题。具体是什么情况就不知道了。

**Comment by xiaoyaofenfen** [comment]
> 可能是因为我开了多个窗口同时下载文件造成的，只开一个窗口下载好像就没有这个问题。具体是什么情况就不知道了。

如果需要多窗口下载，每一个就用一个单独的aliyunpan应用，共用是会有问题的，因为配置文件和下载配置可能会冲突
