### ISSUE TITLE
上传时报错 goroutine 119 [running]:

### ISSUE THREAD

**Issue by badfish2019** [tickstep/aliyunpan#371]
goroutine 119 [running]:
<img width="908" alt="运行问题" src="https://github.com/tickstep/aliyunpan/assets/50726809/3f30a9bb-36f8-4bb7-beed-8f1d3a83ce2b">
如图.....看不懂啥问题

**Comment by xiaoyaofenfen** [comment]
这也看不出问题了，用最新版本再跟进下
