### ISSUE TITLE
服务器开着同步功能，今天一看同步进程挂掉了

### ISSUE THREAD

**Issue by 894276610** [tickstep/aliyunpan#372]
panic: runtime error: invalid memory address or ni
l pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa6957a]

goroutine 4804 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).uploadFile(0xc0000c0000, {0xe363a0, 0xc0002fa050})
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:496 +0xbda
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc0000c0000, {0xe363a0, 0xc0002fa050})
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:70 +0x145
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1()
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x3c5

**Comment by obany-c** [comment]
我也遇到了

panic: runtime error: index out of range [0] with length 0

goroutine 19 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).uploadFile(0xc006214000, 0xf20678, 0xc000133580, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:540 +0x2505
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc006214000, 0xf20678, 0xc000133580, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:70 +0x1cf0
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc006214000, 0xf20678, 0xc000133580, 0xc0002a80e0, 0xc000237050)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x30d

**Comment by xiaoyaofenfen** [comment]
请用v0.3.0版本试试，之前的版本sync命令问题很多
