### ISSUE TITLE
为什么项目依赖了btcd

### ISSUE THREAD

**Issue by liomen** [tickstep/aliyunpan#374]
安装的时候发现项目依赖了btcd
btcd是btc的客户端
为什么这个项目依赖会用到btc客户端呢？
内含挖矿程序？
还没看代码，存疑

**Comment by NeoNexusX** [comment]
逆天，我本来还想用的，吓死了

**Comment by cilidm** [comment]
看了下源码，是因为 `github.com/tickstep/library-go/crypto/secp256k1` 包引用了 `github.com/btcsuite/btcd/btcec`来实现椭圆曲线数字签名算法。
`aliyunpan-api`引用了`library-go`项目的包，本项目使用了`aliyunpan-api`的包，btcd在这里是间接依赖

**Comment by kuangxiaoye** [comment]
> 因为阿里云的token签名用了这个曲线算法，你也可以用其他的库没影响
> 
> 只在这里用了，不放心可以全局搜下 ![image](https://private-user-images.githubusercontent.com/31570634/298270085-dfe5b487-6abe-450f-a596-7d8b2a480985.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzA2OTgsIm5iZiI6MTcwNTk3MDM5OCwicGF0aCI6Ii8zMTU3MDYzNC8yOTgyNzAwODUtZGZlNWI0ODctNmFiZS00NTBmLWE1OTYtN2Q4YjJhNDgwOTg1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMDM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2YxZTg3NTk5ODA0NDI4NzYzMWFiNTRlYmEzZTlmMDFjNjQwNGQ2ZDk3NWI5MmVmZGFlMGE1ZGVhMjIzOGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QHiWGDukPoedyKwUFbfBky9WS332esQigLsEEEYrlXY)

老哥 希望可以看下阿里云盘100m的问题XD

**Comment by xiaoyaofenfen** [comment]
> > 因为阿里云的token签名用了这个曲线算法，你也可以用其他的库没影响
> > 只在这里用了，不放心可以全局搜下 ![image](https://private-user-images.githubusercontent.com/31570634/298270085-dfe5b487-6abe-450f-a596-7d8b2a480985.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzA2OTgsIm5iZiI6MTcwNTk3MDM5OCwicGF0aCI6Ii8zMTU3MDYzNC8yOTgyNzAwODUtZGZlNWI0ODctNmFiZS00NTBmLWE1OTYtN2Q4YjJhNDgwOTg1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QwMDM5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2YxZTg3NTk5ODA0NDI4NzYzMWFiNTRlYmEzZTlmMDFjNjQwNGQ2ZDk3NWI5MmVmZGFlMGE1ZGVhMjIzOGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QHiWGDukPoedyKwUFbfBky9WS332esQigLsEEEYrlXY)
> 
> 老哥 希望可以看下阿里云盘100m的问题XD

下载限制的问题请在#375统一跟进

**Comment by xiaoyaofenfen** [comment]
这个我看看能不能换一个其他加密库吧，让大家放心点

**Comment by liomen** [comment]
看了下代码，确实只用到了btc的椭圆曲线，没有用到其他的，我的锅，检讨
另外，感谢作者
