### ISSUE TITLE
docker v0.2.7 创建文件夹成功 文件一直上传

### ISSUE THREAD

**Issue by Da-Hua** [tickstep/aliyunpan#376]

**Comment by xiaoyaofenfen** [comment]
请使用 v0.3.0进行验证，该版本重构了sync命令

**Comment by kuangxiaoye** [comment]
抱歉，我想问一下为什么v0.2.7 现在依然可用？

因为之前100M文件限制我没有关闭sync容器，一直到今天，但是我今天打开阿里云盘惊讶地发现它居然在三月初恢复了工作！？

请问这是为啥 hhh
