### ISSUE TITLE
无法下载zip压缩包

### ISSUE THREAD

**Issue by Andy-wen197** [tickstep/aliyunpan#377]
无法下载zip压缩包，但可以下载其他文件
![image](https://github.com/tickstep/aliyunpan/assets/79688361/dd8121d0-43c5-44c5-8797-159cbad7faf2)

**Comment by cszy98** [comment]
我也。。

**Comment by 4709olivia** [comment]
这怎么办

**Comment by leisongju** [comment]
我也是，不仅是zip文件，模型权重pt文件也不行

**Comment by shuiqingwuyv** [comment]
可以看更新说明


***重要说明：由于本程序使用的是web网页端的API接口，会遇到超过100MB文件无下载失败的问题，因为这个是阿里在服务端做了限制所以这个问题当前无法解决。预计只能使用阿里的开放接口了进行替代才可能解决，目前还在适配中。

**Comment by xiaoyaofenfen** [comment]
#396 测试版本应该能解决，可以尝试下
