### ISSUE TITLE
下载超过100MB的文件将报错:"下载文件失败, 文件被禁止下载".

### ISSUE THREAD

**Issue by yht0511** [tickstep/aliyunpan#379]
## 描述
我使用该项目在希沃电脑上全自动录制网课,并借助aliyunpan项目将音视频文件同步至服务器:[Online-Courses项目](https://github.com/yht0511/Online-Courses).
而日志文件显示,自2024-01-18开始,aliyunpan间断而看似随机地无法下载部分文件到本地.
经检查,当文件大于100MB时,aliyunpan将无法下载,而官方应用程序不受影响.
显然,阿里云盘官方加强了限制.

## 临时解决方案:
上传前对文件压缩或分片,控制在100M以内.

**Comment by kuangxiaoye** [comment]
对于mp4的分片来说这或许可以临时解决

但是对于某些权重文件或数据库备份文件，这种分割是不现实的

只能换盘了吗

**Comment by xiaoyaofenfen** [comment]
下载限制的问题请在#375统一跟进
