### ISSUE TITLE
感觉阿里云盘最近是不是升级了，新上传的文件无法下载

### ISSUE THREAD

**Issue by monk-after-90s** [tickstep/aliyunpan#380]
```shell
[1] 准备下载: /work/GPT_SoVITS_model.rar
[1] 将会下载到路径: /mnt/disks/sdb/alidownload/63046233a77fr23492993da9ff8c79cae30/work/GPT_SoVITS_model.rar
[1] 下载失败，文件不合法或者被禁止下载: /mnt/disks/sdb/alidownload/63046233a77fr23492993da9ff8c79cae30/work/GPT_SoVITS_model.rar
[1] 下载文件失败, 文件被禁止下载
```

**Comment by Harris-X** [comment]
同上作者所述

**Comment by xmzcl** [comment]
我也遇到了同样的问题~~使用的版本是tickstep/aliyunpan-sync:v0.2.7。

**Comment by xmzcl** [comment]
补充说明一下：提示文件不合法是错误的，用官方客户端和小白羊云盘，文件都是可以正常下载的。

**Comment by qianhg0706** [comment]
我也遇到了同样的问题，我的版本是0.2.8，下载小文件和上传都是可以的，但是下载大文件的话就不行了

**Comment by vyouzhis** [comment]
我的电影也是下载不了， 都是提示 ： 下载失败，文件不合法或者被禁止下载

**Comment by XuecWu** [comment]
> 补充说明一下：提示文件不合法是错误的，用官方客户端和小白羊云盘，文件都是可以正常下载的。

老哥，阿里云盘官方有linux的了？

**Comment by Bekaboo** [comment]
> 补充说明一下：提示文件不合法是错误的，用官方客户端和小白羊云盘，文件都是可以正常下载的。

希望能尽快修复这个 bug 🙏. 在 linux 下还是用 cli 比较简洁, 实在不想为了网盘再装一个 electron 了

**Comment by tickstep** [comment]
由于我们这个用的是web端的接口，超100MB的单个文件会被禁止下载，得换其他接口才行了

**Comment by xiaoyaofenfen** [comment]
下载限制的问题请在#375统一跟进
