### ISSUE TITLE
请教一下文件不能正常上传和下载的问题何时能够解决？

### ISSUE THREAD

**Issue by XuecWu** [tickstep/aliyunpan#382]
如题，请教下作者阿里云盘的限制问题何时才能解决？
这个对日常工作的影响还是蛮大的，依赖性是比较强的
谢谢作者团队❤

**Comment by kuangxiaoye** [comment]
昨天开始上传也g了...

**Comment by xiaoyaofenfen** [comment]
不能下载上传的问题新版本应该有解决，下载限制的问题请在#375跟进
