### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by xiaoxia0722** [tickstep/aliyunpan#383]
输入命令`aliyunpan ls`报错: unexpected end of JSON input。
重新登陆和更新token都没用，程序更新也是最新的。
请问这要怎样解决？

**Comment by Tom-Teamo** [comment]
+1

**Comment by QinglvWei** [comment]
+1

**Comment by shuiqingwuyv** [comment]
+1，不知道有啥替代的不挨

**Comment by xiaoyan94** [comment]
是的  接口更改了

**Comment by sbwml** [comment]
https://us.cooluc.com/aliyunpan-cli/

ps：编译于 aliyunpan-v0.2.7 版本源码

**Comment by chenxuan520** [comment]
> https://us.cooluc.com/aliyunpan-cli/
> 
> ps：编译于 aliyunpan-v0.2.7 版本源码

很有用,开个mr合并或者fork新仓库就更好了

**Comment by sbwml** [comment]
没心思弄这些，主要是我在GitHub Actions 有使用阿里云盘上传文件，就弄了下，源码版本我都懒得pull  直接用以前本地的编译来用

发自我的iPhone

**Comment by tickstep** [comment]
新版已经发布，请大家更新到v0.2.9版本
