### ISSUE TITLE
ls返回错误

### ISSUE THREAD

**Issue by shuiqingwuyv** [tickstep/aliyunpan#385]
aliyunpan:/ 初闻不知(备份盘)$ ls
unexpected end of JSON input

**Comment by shake** [comment]
同样问题，应该是阿里云盘的有啥变化导致的？

**Comment by ToJ112** [comment]
接口应该是不给用了 @tickstep 是不是可以换开发者接口

**Comment by IT-Shaw** [comment]
+1

**Comment by sbwml** [comment]
https://us.cooluc.com/aliyunpan-cli/

文件列表的接口失效的缘故，x86 可以下载上面 aliyunpan-v0.2.7 这个来用   不过不是最新源码，是上一个版本源码编译的

**Comment by yijinsheng** [comment]
唉，开通会员就是图在公司破网络环境下传文件的，这一下子不支持了。先把会员取消了。。

**Comment by vincentaxhe** [comment]
同样，期待作者更新下

**Comment by ZhangDapao121388** [comment]
unexpected end of JSON input+1

**Comment by shuiqingwuyv** [comment]
> https://us.cooluc.com/aliyunpan-cli/
> 
> 文件列表的接口失效的缘故，x86 可以下载上面 aliyunpan-v0.2.7 这个来用 不过不是最新源码，是上一个版本源码编译的

大佬1这个咋用呀，我解压也解压不出来

**Comment by sbwml** [comment]
> > https://us.cooluc.com/aliyunpan-cli/
> > 文件列表的接口失效的缘故，x86 可以下载上面 aliyunpan-v0.2.7 这个来用 不过不是最新源码，是上一个版本源码编译的
> 
> 大佬1这个咋用呀，我解压也解压不出来

?

**Comment by chenxuan520** [comment]
> > https://us.cooluc.com/aliyunpan-cli/
> > 文件列表的接口失效的缘故，x86 可以下载上面 aliyunpan-v0.2.7 这个来用 不过不是最新源码，是上一个版本源码编译的
> 
> 大佬1这个咋用呀，我解压也解压不出来

这个是二进制文件,直接替换原来的aliyunpan就可以了

**Comment by xiaoyaofenfen** [comment]
确实是接口更新了，我适配下
