### ISSUE TITLE
请问一下，docker安装这个错误如何解决？

### ISSUE THREAD

**Issue by asd519627326** [tickstep/aliyunpan#386]
docker: Error response from daemon: manifest for tickstep/aliyunpan-sync:v0.2.9 not found: manifest unknown: manifest unknown.

**Comment by xiaoyaofenfen** [comment]
docker还没发布，得等一下了

**Comment by asd519627326** [comment]
> docker版本还没发布，得等一下了

好的

**Comment by tickstep** [comment]
已发布
