### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by QuectelWB** [tickstep/aliyunpan#388]
~/aliyunpan-v0.2.8-linux-amd64$ ./aliyunpan ls
unexpected end of JSON input

以前还可以用。现在用不了了？

**Comment by QuectelWB** [comment]
非要换到 0.2.9  才可以

**Comment by tickstep** [comment]
阿里限制了旧接口不给用了，只能用0.2.9版本适配好的新接口
