### ISSUE TITLE
挂载webdav访问失败？

### ISSUE THREAD

**Issue by oncebeloved** [tickstep/aliyunpan#39]
使用命令行：./aliyunpan webdav start -ip "127.0.0.1" -port 23077 -webdav_user "admin" -webdav_password "admin" -pan_dir_path "/" -bs 1024
创建webdav 无法访问到文件，请问如何解决，还是存在Bug呢？
![004](https://user-images.githubusercontent.com/51181996/148000338-3a86be5d-8d9c-4b17-b2bb-d68091b6caee.png)

**Comment by tickstep** [comment]
试试这个解决方法，readme文件里有

3 解决 missing Location in call to Date 问题

**Comment by tickstep** [comment]
已修复，请用v0.0.8版本试试

**Comment by vvlaw** [comment]
不知道为什么我运行webdav start后是这样的。。。
[url=https://postimg.cc/N99M05K2][img]https://i.postimg.cc/N99M05K2/image.png[/img][/url]

**Comment by vvlaw** [comment]
不知道为什么我使用webdav start命令后，出现这样的结果：
<a href="https://ibb.co/KwWYKgq"><img src="https://i.ibb.co/ws4TcqW/image.png" alt="image" border="0"></a>

**Comment by tickstep** [comment]
你用webdav客户端试试

**Comment by vvlaw** [comment]
linux 底下有webdav客户端吗？可以 推荐一下吗？谢谢！

**Comment by tickstep** [comment]
> linux 底下有webdav客户端吗？可以 推荐一下吗？谢谢！

davfs2，挺好用的

**Comment by vvlaw** [comment]
> > linux 底下有webdav客户端吗？可以 推荐一下吗？谢谢！
> 
> davfs2，挺好用的

davfs2配置了一番才好，可以正常访问，不过毕竟是远程的，访问有点慢！
<a href="https://imgbb.com/"><img src="https://i.ibb.co/WxXFYcH/aliyunpan3.png" alt="aliyunpan3" border="0"></a>
