### ISSUE TITLE
备份盘和资源库DRIVE ID相同是怎么回事儿？

### ISSUE THREAD

**Issue by Jinlixian** [tickstep/aliyunpan#391]
备份盘和资源库DRIVE ID相同是怎么回事儿？
![WX20240223-140555@2x](https://github.com/tickstep/aliyunpan/assets/7472208/b6b1851b-9114-4776-89ff-93ada85d6ef8)
不论进入备份盘还是资源库，里面的内容都是资源库的内容。
我应该如何才能正常进入备份盘呢？

**Comment by xiaoyaofenfen** [comment]
你这个有点神奇，重新登录看看能不能解决

**Comment by leisongju** [comment]
> 你这个有点神奇，重新登录看看能不能解决

大佬是不是在解决文件上传的事，大佬辛苦

**Comment by xiaoyaofenfen** [comment]
> > 你这个有点神奇，重新登录看看能不能解决
> 
> 大佬是不是在解决文件上传的事，大佬辛苦

#396 测试版本应该能解决，你可以尝试下
