### ISSUE TITLE
怎么把备份调整到资源库呢？

### ISSUE THREAD

**Issue by greyhanttee** [tickstep/aliyunpan#397]
docker下设置的，默认在备份盘里，使用了./aliyunpan drive，选择了资源库，可还是往备份盘里存，我是漏掉了什么环节吗？

**Comment by xiaoyaofenfen** [comment]
这个确实还不支持，当前支持备份盘不支持资源库。sync命令还是重构，重构的时候把这个资源库加上。你可以关注下 #396 这个issue。
