### ISSUE TITLE
我要对网盘的目录结构进行分析，想问下如何把ls或者tree的结果写入txt文件中

### ISSUE THREAD

**Issue by songzijiang** [tickstep/aliyunpan#398]
如题

**Comment by songzijiang** [comment]
我用python的[api](https://github.com/foyoux/aligo)解决了，不过作者大大可以考虑放开一些api接口

**Comment by xiaoyaofenfen** [comment]
用标准linux命令应该就可以的做到。例如
[root ~/Downloads]$ aliyunpan ll > myfiles.txt

打开myfiles.txt文件就有了
![image](https://github.com/tickstep/aliyunpan/assets/5262333/7b1fbac9-2e0e-4369-98c0-bd9d5e002995)
