### ISSUE TITLE
RefreshToken参数是不是取消了

### ISSUE THREAD

**Issue by 362227** [tickstep/aliyunpan#399]
aliyunpan login -RefreshToken=e08696c7be3448aXXXXXXXX  这样不行了
我知道怎么获取RefreshToken，但现在好像只能授权扫码了，但会卡住，第二次扫码没反应，能不能恢复 aliyunpan login -RefreshToken

**Comment by 362227** [comment]
已经成功了，但我觉得比直接填RefreshToken麻烦多了，而且要扫两次。有时候那个授权链接还打不开

**Comment by xiaoyaofenfen** [comment]
是的，取消了。新版本使用了阿里的官方开放接口，阿里的流程必须在网页端授权登录，这个限制绕不开。
