### ISSUE TITLE
支持一个docker容器同时备份2个本地目录到阿里云盘？

### ISSUE THREAD

**Issue by ncist2011** [tickstep/aliyunpan#400]

**Comment by xiaoyaofenfen** [comment]
需要自己手动去配置，你需要了解docker文件映射的知识

1，把这个文件映射出来到本地，然后启动容器
"""
version: '3'
services:
  sync:
    image: tickstep/aliyunpan-sync:<tag>
    container_name: aliyunpan-sync
    restart: always
    volumes:
      ...
      # （推荐）挂载sync_drive同步数据库到本地，这样即使容器销毁，同步数据库还可以用于以后使用
      - ./sync_drive:/home/app/config/sync_drive
      ...
"""
2，然后你就会看到sync_drive_config.json这个文件
按照手册的教程去配置这个文件，可以配置多个任务
"""
https://github.com/tickstep/aliyunpan/blob/main/docs/manual.md#%E5%A4%87%E4%BB%BD%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E
"""
然后重启容器即可

**Comment by xiaoyaofenfen** [comment]
你可以参考 #401 这个issue的例子
