### ISSUE TITLE
local_addrs 设置能否用网路接口名称？

### ISSUE THREAD

**Issue by YaoFei509** [tickstep/aliyunpan#402]
比如我想用ipv6传输，还是走系统里的第二个网卡（还是个无线网卡），那么我现在只能在配置里写[24xx:xxxx:xxxx:xxxx] 这样一串。考虑到IPv6地址每隔一段时间就变了，这样就太不方便了。能改成可以写网卡名称吗? 类似 traceroute6 -i enp3s0 这样的？

**Comment by xiaoyaofenfen** [comment]
local_addrs 这个好像是不支持ipv6的，只能指定ipv4的地址。
网卡名称这个是不支持的，我可以看看能不能做。

**Comment by YaoFei509** [comment]
IPv6地址要加[]方括号

**Comment by xiaoyaofenfen** [comment]
> IPv6地址要加[]方括号
好的。感谢反馈，网口名称下个版本支持。
