### ISSUE TITLE
登录几分钟后便失效

### ISSUE THREAD

**Issue by CescMessi** [tickstep/aliyunpan#403]
使用0.3.0版，可以成功登录，进入程序后可以正常下载，退出程序后不会立即退出账号，但几分钟后再使用程序就需要重新登录。

![image](https://github.com/tickstep/aliyunpan/assets/15847281/4998c24a-3fe4-45be-8f84-917e93072b4a)

**Comment by xiaoyaofenfen** [comment]
开debug日志看看，最可能是配置文件没有写入权限，可以用 ./aliyunpan config 看看配置文件在哪

**Comment by CescMessi** [comment]
> 开debug日志看看，最可能是配置文件没有写入权限，可以用 ./aliyunpan config 看看配置文件在哪

找到问题了，是之前旧版本的同步进程没有退出导致的，谢谢
