### ISSUE TITLE
请问什么时候可以添加镜像备份功能呢？

### ISSUE THREAD

**Issue by xmzcl** [tickstep/aliyunpan#404]
主要是用来把本地的备份到阿里网盘，因为每天数据都会按日期有一份备份。如果只用upload，本地的备份文件会一直往网盘上同步。本地清理掉的文件，还得手工在网盘上做清理。

**Comment by xiaoyaofenfen** [comment]
我咨询一下，你这个是需要本地文件上传到云盘，要一一完全一致，本地文件有更新对应的网盘文件也需要对应更新，本地文件如果删除了对应的网盘文件也需要进行对应删除，你这个需求是这样么？如果是的话sync命令可以，它有个upload模式就是这种场景用，不过对应文件删除的功能得下个版本才能发布

**Comment by xmzcl** [comment]
是的~就是你说的这个意思!期待新版本的发布！

**Comment by jth445600** [comment]
@xiaoyaofenfen 我看文档里说, 同步有三种模式, 上传/下载/完全, 为啥没看到有完全

**Comment by tickstep** [comment]
v0.3.1 版本已合入

**Comment by xmzcl** [comment]
今早，第一时间把版本更新到了。V0.3.1,但是好像并没有得到期望中的效果。我需要将配置文件中的upload，改成sync嘛？
![image](https://github.com/tickstep/aliyunpan/assets/30224176/d7193ddf-1771-4d37-b669-057dcab7a54d)
还是需要将原来的同步内容删除掉，重新扫描。
![Uploading image.png…]()

**Comment by xmzcl** [comment]
附一张我现在云盘的内容
![image](https://github.com/tickstep/aliyunpan/assets/30224176/756f7341-eeaf-48e3-ae2d-bcbb3af1b632)

另外我本地文件的内容。
![image](https://github.com/tickstep/aliyunpan/assets/30224176/9c4ec1a8-b185-440d-b975-9845a87cb682)

**Comment by xiaoyaofenfen** [comment]
> 今早，第一时间把版本更新到了。V0.3.1,但是好像并没有得到期望中的效果。我需要将配置文件中的ALIYUNPAN_SYNC_MODE=upload，改成sync嘛？ 还是需要将原来的同步内容删除掉，重新扫描。 ![image](https://private-user-images.githubusercontent.com/30224176/324315530-15864b76-0b90-4e91-b912-92d1aef72130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjczNTEsIm5iZiI6MTcxMzc2NzA1MSwicGF0aCI6Ii8zMDIyNDE3Ni8zMjQzMTU1MzAtMTU4NjRiNzYtMGI5MC00ZTkxLWI5MTItOTJkMWFlZjcyMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA2MjQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZmQxYzgyYzc4MzAxZmEzOGEwYzhhMjA5YmI2M2M3YmJjY2RiNWQyNjAyYjA2ODJiNDFlNTU5ZDRlYTc0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ULdkKrVZX00zQPNVpEep0uVS8hMadK249WAmIJbrZ6M)

sync还没有做，v0.3.1做的是镜像备份功能。sync大概率做不了了，目前还在找有没有其他方案

**Comment by xmzcl** [comment]
可以了，研究了一下，配置文件。要将"policy"改成"exclusive"

**Comment by xiaoyaofenfen** [comment]
> 可以了，研究了一下，配置文件。要将"policy"改成"exclusive"

是的，这个是排他备份就是上面说的镜像备份，一开始就起了这个名字所以没有改了。个人觉得你这个”镜像备份“应该更好一点

**Comment by jth445600** [comment]
@xmzcl 大佬, 咋弄的呀, 能不能实现, 本地和云端, 无论哪一端变化, 另外一端都自动变化吗
