### ISSUE TITLE
v0.3.0在docker下很难使用login登陆。因为提示登陆失败而一直在重启，重启的过程又无法登陆后台。是我打开方式不对吗？

### ISSUE THREAD

**Issue by whou17** [tickstep/aliyunpan#406]
v0.3.0在docker下很难使用login登陆。因为提示登陆失败而一直在重启，重启的过程又无法登陆后台。是我打开方式不对吗？

**Comment by tickstep** [comment]
docker的需要用在其他地方登录好的config文件，你看看教程，里面有。docker不能自己登录

**Comment by whou17** [comment]
忽视了教程，感谢耐心指导！

**Comment by hudingwen** [comment]
怪不得 我是说容器老是掉 但是又登录不了..

**Comment by hudingwen** [comment]
已经ok,下载个window的版本扫码登录拿到跟目录下的json文件映射到docker中去解决
