### ISSUE TITLE
出现这个错误 请求过快，请等待 x-retry-after 毫秒后再请求

### ISSUE THREAD

**Issue by jungleaspen** [tickstep/aliyunpan#408]
请问运行tree命令时出现这个错误怎么办：
请求过快，请等待 x-retry-after 毫秒后再请求

可以把出错信息上一行的目录、上一级和上两层的目录重新请求一次。
除此之外，还有可能再上一级目录有遗漏吗？
会不会需要从这次请求的根目录开始都要重新请求？

有没有更好一点的解决办法？

**Comment by tickstep** [comment]
这是短时间请求太多被阿里风控了。你目录里面很多文件么？大概多少数量级？1000？

**Comment by jungleaspen** [comment]
不止，10万级。

问题是，怎么处理？
想要重新请求，只能根据粗略判断写脚本重做。
能否从tree的源码收到报错的时候，就记住哪些完成了哪些没完成？
或者，把请求间隔加长点，或随机化，能否降低被风控的概率

**Comment by tickstep** [comment]
> 不止，10万级。
> 
> 问题是，怎么处理？ 想要重新请求，只能根据粗略判断写脚本重做。 能否从tree的源码收到报错的时候，就记住哪些完成了哪些没完成？ 或者，把请求间隔加长点，或随机化，能否降低被风控的概率

没啥好的手段，我们下个版本适配下，之前我们是固定时间sleep降低风控，现在只能改成阿里[x-retry-after 毫秒]进行sleep。你要不按子目录去tree吧，降低文件数量，然后再把所有子目录的结果进行拼接

**Comment by jungleaspen** [comment]
> > 不止，10万级。
> > 问题是，怎么处理？ 想要重新请求，只能根据粗略判断写脚本重做。 能否从tree的源码收到报错的时候，就记住哪些完成了哪些没完成？ 或者，把请求间隔加长点，或随机化，能否降低被风控的概率
> 
> 没啥好的手段，我们下个版本适配下，之前我们是固定时间sleep降低风控，现在只能改成阿里[x-retry-after 毫秒]进行sleep。你要不按子目录去tree吧，降低文件数量，然后再把所有子目录的结果进行拼接

好的 谢谢大牛！

**Comment by tickstep** [comment]
v0.3.1 版本已修复
