### ISSUE TITLE
`aliyunpan_config.json` 中没有 openapi 的 `refresh_token` ?

### ISSUE THREAD

**Issue by yiyungent** [tickstep/aliyunpan#419]
如题，这玩意是保存在哪的啊？
我看又实现了自动刷新 `access_token`，

话说后续完全转向 openapi, 应该就可用自己申请的 `clientId` 了吧，

谢谢！！！

**Comment by tickstep** [comment]
refresh token保存在服务器，因为这个东西需要配合app secrect key才能用，这个东西是不可能放客户端本地的。

**Comment by tickstep** [comment]
> 如题，这玩意是保存在哪的啊？
> 
> 我看又实现了自动刷新 `access_token`，
> 
> 
> 
> 话说后续完全转向 openapi, 应该就可用自己申请的 `clientId` 了吧，
> 
> 
> 
> 谢谢！！！
> 
> 
> 
> 
> 
> 
> 
> 

是可以的，只要你实现服务端登录的业务就可以配合你自己的client id来用了

**Comment by yiyungent** [comment]
> > 如题，这玩意是保存在哪的啊？
> > 我看又实现了自动刷新 `access_token`，
> > 话说后续完全转向 openapi, 应该就可用自己申请的 `clientId` 了吧，
> > 谢谢！！！
> 
> 是可以的，只要你实现服务端登录的业务就可以配合你自己的client id来用了

感谢解答！！！非常棒的开源项目！！！
