### ISSUE TITLE
考虑支持华硕路由器吗，可以赞助💰

### ISSUE THREAD

**Issue by AsaMitakaIT** [tickstep/aliyunpan#420]
我想把电影文件夹直接同步到路由器上插的硬盘里，这样在家里的时候就可以高速观看了

**Comment by xiaoyaofenfen** [comment]
你这个需求和这个工具关系不大，你应该找找SMB的同步工具，或者你路由器刷软路由系统，例如openwrt，应该有文件同步工具的

**Comment by AsaMitakaIT** [comment]
我可能说的太简洁了，但我确信我需要的就是这个工具。我的电影文件夹就在阿里云盘而不是NAS上，用这个项目相当于给播放器增加了一个本地缓存。

**Comment by xiaoyaofenfen** [comment]
那你看一下华硕的路由器能不能开启ssh远程连接，能开启的话应该就能够跑这个程序了，或者看一下它能不能支持docker。因为我有用openwrt软路由这个是支持的，暂时不考虑专门为单品类的产品专门进行适配的，这样适配不过来的。如果有其他网友考虑适配我们可以提供技术支持
