### ISSUE TITLE
change default config and command history file to be under ~/.config

### ISSUE THREAD

**Issue by YjzJim** [tickstep/aliyunpan#423]
changing default config and command history file to be under ~/.config, for example ~/.config/aliyunpan. Then root access won't be needed out of the box ( and it shouldn't be required )

**Comment by xiaoyaofenfen** [comment]
you can use the environment variable ALIYUNPAN_CONFIG_DIR to set it, for example:
```
export ALIYUNPAN_CONFIG_DIR=~/.config/aliyunpan
```
