### ISSUE TITLE
sync start 上传的文件目录错乱

### ISSUE THREAD

**Issue by jingc1413** [tickstep/aliyunpan#430]
windwos环境
login成功后 
执行 sync start -ldir "E:\cppcryptfs" -pdir "/cppcryptfs" -mode "upload"
![image](https://github.com/tickstep/aliyunpan/assets/13563637/abdf0334-9fa0-410a-9adb-bf2f5ecffb0c)
上图是我本地文件目录
![image](https://github.com/tickstep/aliyunpan/assets/13563637/d9ed3427-91c2-4c07-ad63-c2effefbef78)
上图是上传后的截图，感觉是把文件夹里面的文件提取出来了

**Comment by jingc1413** [comment]
closed

**Comment by w38351479** [comment]
Linux也一样错乱
