### ISSUE TITLE
wishlist: Use Basedir configuration directories on Linux

### ISSUE THREAD

**Issue by popjdh** [tickstep/aliyunpan#433]
App should follow the xdg basedir spec. More information can be found here: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

In Linux, the default configuration directory can follow this priority
1. `"$ALIYUNPAN_CONFIG_DIR"`
2. `"$XDG_CONFIG_HOME"/aliyunpan`
3. `"$HOME"/.config/aliyunpan`

**Comment by popjdh** [comment]
Similarly, the download directory should also follow the xdg user directories. 
1. "$ALIYUNPAN_DOWNLOAD_DIR"
2. "$XDG_DOWNLOAD_DIR"
3. "~/Downloads"

I found this repo https://github.com/adrg/xdg. I am not familiar with go, but It seems that this should be able to complete the above functions.

**Comment by xiaoyaofenfen** [comment]
thanks for your feedback. 

> Similarly, the download directory should also follow the xdg user directories.
> 
> 1. `"$ALIYUNPAN_DOWNLOAD_DIR"`
> 2. `"$XDG_DOWNLOAD_DIR"` (Not a environment variable: https://www.freedesktop.org/wiki/Software/xdg-user-dirs/)
> 3. `"~/Downloads"`
> 
> I found this repo https://github.com/adrg/xdg. I am not familiar with go, but It seems that this should be able to complete the above functions.

thanks for your feedback.  it seems to work, we will add it in the next version.

**Comment by tickstep** [comment]
v0.3.3 new version has support the XDG folder rule
