### ISSUE TITLE
指定目录无效

### ISSUE THREAD

**Issue by shuiqingwuyv** [tickstep/aliyunpan#434]
使用命令指定下载目录，现在文件不在指定的文件夹求解
![11](https://github.com/tickstep/aliyunpan/assets/66666003/352487cb-89b8-4218-b554-f16fbaba34ff)

**Comment by xiaoyaofenfen** [comment]
环境变量指定的是配置目录，下载目录需要使用config命令指定，例如
```
config set -savedir=/data/Aliyunpan_download
```

**Comment by shuiqingwuyv** [comment]
感谢解惑，可以降这个加入到.md中吗
