### ISSUE TITLE
每次下载到90%就卡住了，0KB/s

### ISSUE THREAD

**Issue by Chuge0335** [tickstep/aliyunpan#438]
![Screenshot from 2024-07-08 11-25-59](https://github.com/tickstep/aliyunpan/assets/128665532/04774a4b-e151-41ea-a242-22040a5cf0d7)

**Comment by xiaoyaofenfen** [comment]
重新下载能继续么？打开log看看有没有报错

**Comment by KKKKeybird** [comment]
同样情况，重新下载也没用，只能单个下载不会出现问题

**Comment by xudooo** [comment]
> 同样情况，重新下载也没用，只能单个下载不会出现问题

是的，我也遇到了这个问题，下载两个及以上就会出现 0B/s，单个没有

**Comment by tickstep** [comment]
v0.3.3已经解决了该问题，请使用新版本验证
