### ISSUE TITLE
DOcker版aliyunpan-sync:v0.3.3-arm64创建容器后一直登陆失败

### ISSUE THREAD

**Issue by birdxs** [tickstep/aliyunpan#450]
设备：arm64盒子
安装方式：docker容器部署
使用镜像：aliyunpan-sync:v0.3.3-arm64
已经提前获取aliyunpan_config.json文件，然后部署的容器，查看日志报错

**_第一次使用的aliyunpan_config.json是在windows使用下载的win64报登录获取的，以为是系统不一样，linux不认
第二次尝试直接下载aliyunpan-v0.3.3-linux-arm64，现在盒子系统用命令行登陆获取aliyunpan_config.json，丢入doccker配置文件后重启容器仍然报以下错误_**
如下：
`未登录账号

using existed sync_drive_config.json file

当前帐号UID:  , 昵称:  , 三方权益包: 未开通, 当前使用网盘：备份盘

cache token is valid, not need to re-login

尝试登录失败，请使用 login 命令进行重新登录

  名称                   值                        建议值                        描述                                                                                          

  cache_size             0B                        1KB ~ 256KB                   下载缓存, 如果硬盘占用高或下载速度慢, 请尝试调大此值                                          

  max_download_parallel  0                         1 ~ 20                        最大下载并发量，即同时下载文件最大数量                                                        

  max_upload_parallel    0                         1 ~ 20                        最大上传并发量，即同时上传文件最大数量                                                        

  max_download_rate      不限制                                                  限制单个文件最大下载速度, 0代表不限制                                                         

  max_upload_rate        不限制                                                  限制单个文件最大上传速度, 0代表不限制                                                         

  savedir                /home/app/Downloads                                     下载文件的储存目录                                                                            

  proxy                                                                          设置代理, 支持 http/socks5 代理，例如: http://127.0.0.1:8888 或者 socks5://127.0.0.1:8889     

  local_addrs                                                                    绑定本地网卡地址, 多个地址用逗号隔开，支持网口名称，例如: 127.0.0.1,192.168.100.126,en0,eth0  

  ip_type                ipv4                      ipv4-优先IPv4，ipv6-优先IPv6  设置域名解析IP优先类型。修改后需要重启应用生效                                                

  file_record_config     开启                      1-开启，2-禁用                设置是否开启上传、下载、同步文件的结果记录，开启后会把结果记录到CSV文件方便后期查看           

  device_id                                               客户端ID，用于标识登录客户端，阿里单个账号最多允许10个客户端同时在线。修改后需要重启应用生效  

保存配置成功!

尝试登录失败，请使用 login 命令进行重新登录

未登录账号`

**Comment by xiaoyaofenfen** [comment]
aliyunpan_config.json 这个文件是通用的。windows / linux 都可以通用。
你开启Debug模式打印log看看哪一步失败了

**Comment by xiaoyaofenfen** [comment]
> > aliyunpan_config.json 这个文件是通用的。windows / linux 都可以通用。 你开启Debug模式打印log看看哪一步失败了 增加一个ALIYUNPAN_VERBOSE的环境变量，然后销毁容器，重新启动即可
> > ```
> > version: '3'
> > services:
> >   sync:
> >     image: tickstep/aliyunpan-sync:<tag>
> >     ......
> >     environment:
> >       # 开启Debug日志
> >       - ALIYUNPAN_VERBOSE=1
> > ```
> 
> `[2024-9-2 21:32:19.416] use config dir from ALIYUNPAN_CONFIG_DIR env: /home/app/config
> 
> [2024-9-2 21:32:19.420] use config dir from ALIYUNPAN_CONFIG_DIR env: /home/app/config
> 
> [2024-9-2 21:32:19.425] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
> 
> [2024-9-2 21:32:19.448] get drive info error Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> 
> [2024-9-2 21:32:19.448] setup user error
> 
> [2024-9-2 21:32:19.448] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
> 
> [2024-9-2 21:32:19.448] get drive info error Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> 
> [2024-9-2 21:32:19.449] 尝试登录失败: Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> 
> 尝试登录失败，请使用 login 命令进行重新登录
> 
> [2024-9-2 21:32:19.453] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
> 
> [2024-9-2 21:32:19.454] get drive info error Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> 
> [2024-9-2 21:32:19.454] setup user error
> 
> 未登录账号` 是ipv6的问题吗？

看着像，请求走了ipv6线路，一般docker不会有ipv6的。你可以试试把这个aliyunpan_config.json文件配置项"preferIPType"改成"ipv4"强制走ipv4线路试试
![image](https://github.com/user-attachments/assets/586e9011-62ce-4a53-8725-9c2e92ebd4ab)

**Comment by birdxs** [comment]
> > > aliyunpan_config.json 这个文件是通用的。windows / linux 都可以通用。 你开启Debug模式打印log看看哪一步失败了 增加一个ALIYUNPAN_VERBOSE的环境变量，然后销毁容器，重新启动即可
> > > ```
> > > version: '3'
> > > services:
> > >   sync:
> > >     image: tickstep/aliyunpan-sync:<tag>
> > >     ......
> > >     environment:
> > >       # 开启Debug日志
> > >       - ALIYUNPAN_VERBOSE=1
> > > ```
> > 
> > 
> > `[2024-9-2 21:32:19.416] use config dir from ALIYUNPAN_CONFIG_DIR env: /home/app/config
> > [2024-9-2 21:32:19.420] use config dir from ALIYUNPAN_CONFIG_DIR env: /home/app/config
> > [2024-9-2 21:32:19.425] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
> > [2024-9-2 21:32:19.448] get drive info error Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> > [2024-9-2 21:32:19.448] setup user error
> > [2024-9-2 21:32:19.448] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
> > [2024-9-2 21:32:19.448] get drive info error Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> > [2024-9-2 21:32:19.449] 尝试登录失败: Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> > 尝试登录失败，请使用 login 命令进行重新登录
> > [2024-9-2 21:32:19.453] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
> > [2024-9-2 21:32:19.454] get drive info error Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp [2408:4000:200::39a]:443: connect: cannot assign requested address
> > [2024-9-2 21:32:19.454] setup user error
> > 未登录账号` 是ipv6的问题吗？
> 
> 看着像，请求走了ipv6线路，一般docker不会有ipv6的。你可以试试把这个aliyunpan_config.json文件配置项"preferIPType"改成"ipv4"强制走ipv4线路试试 ![image](https://private-user-images.githubusercontent.com/5262333/363886887-586e9011-62ce-4a53-8725-9c2e92ebd4ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTc1ODQsIm5iZiI6MTcyNTM1NzI4NCwicGF0aCI6Ii81MjYyMzMzLzM2Mzg4Njg4Ny01ODZlOTAxMS02MmNlLTRhNTMtODcyNS05YzJlOTJlYmQ0YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDNUMDk1NDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY1YjQ5MmQ0MWE1NTdlM2QxNGYwOGVmYTEyN2Q0ZmQ3YTczNDI3YmM0NGEwYjNjNTY5M2IwYTI1ZThhYTk0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bmFzuHot-P5acglvBM050H8XjOg23I9mqb_hWUkWmzk)

![Screenshot_20240903_175402_com estrongs android pop pro](https://github.com/user-attachments/assets/4eae7993-7f99-4d68-8d6c-048d7bd1e0aa)
看了配置文件，就是设置的ipv4。

**Comment by xiaoyaofenfen** [comment]
你这docker容器是不是只有ipv6，而没有ipv4的地址吧？

**Comment by xiaoyaofenfen** [comment]
如果还有问题，用新版试试
