### ISSUE TITLE
是否支持关闭终端后仍后台上传？

### ISSUE THREAD

**Issue by li7355608** [tickstep/aliyunpan#451]
如题提问，在关闭终端后上传任务是否后台继续？如果不继续再次打开新的终端上传，是重新上传还是接着之前断掉的地方断点续传？

**Comment by xiaoyaofenfen** [comment]
1，有很多方法，最简单就用nohup就行
第一步，先新建一个up.sh脚本文件，内容如下，路径要改成你自己的
```
#!/bin/bash

# 是否开启调试日志
export ALIYUNPAN_VERBOSE=0
# 配置目录的绝对路径（可选）
export ALIYUNPAN_CONFIG_DIR=/Users/tickstep/Applications/adrive/config
# aliyunpan程序所在的绝对路径
export ALIYUNPAN_BIN=/Users/tickstep/Applications/adrive/aliyunpan

# 本地目录
LOCAL_DIR="/Users/tickstep/Downloads/video"
# 网盘目录
PAN_DIR="/video"

# 执行
"$ALIYUNPAN_BIN" upload -exn "^\."  -exn "^@eadir$" "$LOCAL_DIR" "$PAN_DIR"
```
第二补，打开终端，切换到up.sh所在目录，执行后台上传
```
nohup bash ./up.sh > aliyunpan.log 2>&1 &
```
2，会的接着上传，支持断点续传

**Comment by li7355608** [comment]
> 1，有很多方法，最简单就用nohup就行 第一步，先新建一个up.sh脚本文件，内容如下，路径要改成你自己的
> 
> ```
> #!/bin/bash
> 
> # 是否开启调试日志
> export ALIYUNPAN_VERBOSE=0
> # 配置目录的绝对路径（可选）
> export ALIYUNPAN_CONFIG_DIR=/Users/tickstep/Applications/adrive/config
> # aliyunpan程序所在的绝对路径
> export ALIYUNPAN_BIN=/Users/tickstep/Applications/adrive/aliyunpan
> 
> # 本地目录
> LOCAL_DIR="/Users/tickstep/Downloads/video"
> # 网盘目录
> PAN_DIR="/video"
> 
> # 执行
> "$ALIYUNPAN_BIN" upload -exn "^\."  -exn "^@eadir$" "$LOCAL_DIR" "$PAN_DIR"
> ```
> 
> 第二补，打开终端，切换到up.sh所在目录，执行后台上传
> 
> ```
> nohup bash ./up.sh > aliyunpan.log 2>&1 &
> ```
> 
> 2，会的接着上传，支持断点续传

也就是说，无论是使用脚本还是命令行，只要创建了上传任务出现上传进度后，就可以直接关掉终端，任务仍会在后台进行对吧？

**Comment by li7355608** [comment]
> > > 1，有很多方法，最简单就用nohup就行 第一步，先新建一个up.sh脚本文件，内容如下，路径要改成你自己的
> > > ```
> > > #!/bin/bash
> > > 
> > > # 是否开启调试日志
> > > export ALIYUNPAN_VERBOSE=0
> > > # 配置目录的绝对路径（可选）
> > > export ALIYUNPAN_CONFIG_DIR=/Users/tickstep/Applications/adrive/config
> > > # aliyunpan程序所在的绝对路径
> > > export ALIYUNPAN_BIN=/Users/tickstep/Applications/adrive/aliyunpan
> > > 
> > > # 本地目录
> > > LOCAL_DIR="/Users/tickstep/Downloads/video"
> > > # 网盘目录
> > > PAN_DIR="/video"
> > > 
> > > # 执行
> > > "$ALIYUNPAN_BIN" upload -exn "^\."  -exn "^@eadir$" "$LOCAL_DIR" "$PAN_DIR"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 第二补，打开终端，切换到up.sh所在目录，执行后台上传
> > > ```
> > > nohup bash ./up.sh > aliyunpan.log 2>&1 &
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 2，会的接着上传，支持断点续传
> > 
> > 
> > 也就是说，无论是使用脚本还是命令行，只要创建了上传任务出现上传进度后，就可以直接关掉终端，任务仍会在后台进行对吧？
> 
> 不能这么理解，如果你没有用nohup命令，你关掉终端，进程会被kill掉。你只有用了nohup命令，这时候关掉终端，任务才会在后台进行。

了解。还有一个疑问，如果想卸载该脚本的话，如何卸载才能保证卸载干净。

**Comment by xiaoyaofenfen** [comment]
> > > > 1，有很多方法，最简单就用nohup就行 第一步，先新建一个up.sh脚本文件，内容如下，路径要改成你自己的
> > > > ```
> > > > #!/bin/bash
> > > > 
> > > > # 是否开启调试日志
> > > > export ALIYUNPAN_VERBOSE=0
> > > > # 配置目录的绝对路径（可选）
> > > > export ALIYUNPAN_CONFIG_DIR=/Users/tickstep/Applications/adrive/config
> > > > # aliyunpan程序所在的绝对路径
> > > > export ALIYUNPAN_BIN=/Users/tickstep/Applications/adrive/aliyunpan
> > > > 
> > > > # 本地目录
> > > > LOCAL_DIR="/Users/tickstep/Downloads/video"
> > > > # 网盘目录
> > > > PAN_DIR="/video"
> > > > 
> > > > # 执行
> > > > "$ALIYUNPAN_BIN" upload -exn "^\."  -exn "^@eadir$" "$LOCAL_DIR" "$PAN_DIR"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 第二补，打开终端，切换到up.sh所在目录，执行后台上传
> > > > ```
> > > > nohup bash ./up.sh > aliyunpan.log 2>&1 &
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 2，会的接着上传，支持断点续传
> > > 
> > > 
> > > 也就是说，无论是使用脚本还是命令行，只要创建了上传任务出现上传进度后，就可以直接关掉终端，任务仍会在后台进行对吧？
> > 
> > 
> > 不能这么理解，如果你没有用nohup命令，你关掉终端，进程会被kill掉。你只有用了nohup命令，这时候关掉终端，任务才会在后台进行。
> 
> 了解。还有一个疑问，如果想卸载该脚本的话，如何卸载才能保证卸载干净。

直接Kill 进程就行了
