### ISSUE TITLE
ALIYUNPAN_LOCAL_DELAY_TIME不生效

### ISSUE THREAD

**Issue by itribs** [tickstep/aliyunpan#452]
在docker-compose.yml中，设置了
`ALIYUNPAN_LOCAL_DELAY_TIME=1800`,文档说单位是秒，这里应该设置了半小时间隔，但实际会一直不断的扫描，不管文件有没有更新，中间大概间隔50秒左右，修改成18000也没用，还是大概50秒间隔。
查看sync_drive_config.json文件lastSyncTime是空，
`"lastSyncTime": ""`不知道是不是因为这个

**Comment by xiaoyaofenfen** [comment]
这个参数不是设置扫描间隔的，目前扫描间隔固定是1分钟。

**Comment by itribs** [comment]
那这个参数是控制什么间隔的呢，另外建议需要一个扫描间隔，做远程备份不需要一直扫描，甚至一天只扫一次都行，如果用cron控制容器的话，我怕token过期

**Comment by xiaoyaofenfen** [comment]
得用新版本，旧版本没有，下面的参数
```
      # 扫描文件间隔时间，单位：分钟
      - ALIYUNPAN_SCAN_INTERVAL_TIME=1
```
