### ISSUE TITLE
docker版本启动后大量ipv6链接，上传了许多流量是什么情况

### ISSUE THREAD

**Issue by MasterKe2003** [tickstep/aliyunpan#453]
![image](https://github.com/user-attachments/assets/c739b9ce-037a-4ea3-8176-c232ad4c4bef)
![image](https://github.com/user-attachments/assets/45323915-0270-4dfa-b1f6-5151ab30e885)

**Comment by MasterKe2003** [comment]
![image](https://github.com/user-attachments/assets/aff0f114-a63f-4dc5-9754-7ee0117541fe)

**Comment by xiaoyaofenfen** [comment]
你禁掉ipv6，只让它用ipv4。ipv6很不稳定可能会有大量重传

**Comment by MasterKe2003** [comment]
> 你禁掉ipv6，只让它用ipv4。ipv6很不稳定可能会有大量重传

请问有什么好的办法只禁用这个容器的ipv6么，因为我还运行了一个ipv6的ddns

**Comment by xiaoyaofenfen** [comment]
你可以先禁用aliyunpan程序用ipv6看看，直接改文件“aliyunpan_config.json”，这个 "preferIPType"为"ipv4"，重启docker即可

**Comment by MasterKe2003** [comment]
> 你可以先禁用aliyunpan程序用的pv6看看，直接改文件“aliyunpan_config.json”，这个 "preferIPType"改为"ipv4"，重启docker即可

这个preferIPType""ipv4原来就是这么设置的
网上搜索了docker禁用ipv6有这个方案，添加一个额外环境变量，好像是修复了
-e "extra_params=--o:net.proto=IPv4"
