### ISSUE TITLE
如何卸载linux版本的阿里云盘

### ISSUE THREAD

**Issue by JordanSeaGold** [tickstep/aliyunpan#454]
我想在服务器上更新linux阿里云盘，由于无法在服务器上面安装加速器等软件，导致无法更新，所以只能卸载重装。问题是如何卸载现有版本咧，我没有找到卸载的相关指令。

**Comment by JordanSeaGold** [comment]
我刚刚把之前版本的阿里云盘的文件夹给删除了，但是在终端输入aliyunpan跳转的还是之前版本。我在最新版的阿里云盘文件夹里面运行./aliyunpan才会显示最新版

**Comment by xiaoyaofenfen** [comment]
linux的版本你用linux的命令就行，例如用apt安装的就用apt卸载，用yum安装的就用yum卸载

**Comment by JordanSeaGold** [comment]
> linux的版本你用linux的命令就行，例如用apt安装的就用apt卸载，用yum安装的就用yum卸载

谢谢，我刚刚卸载成功了。卸载又遇到问题了，我无法通过直接下载本地来进行安装也就是通过这个方式：wget https://github.com/tickstep/aliyunpan/releases/download/v0.3.4/aliyunpan-v0.3.4-linux-amd64.zip
unzip aliyunpan-v0.3.4-linux-amd64.zip
cd aliyunpan-v0.3.4-linux-amd64
./aliyunpan。我通过这种方式，输入./aliyunpan他会直接跳转到阿里云盘，而不会显示安装。并且我在bash终端输入aliyunpan后他会提示bash: /usr/local/bin/aliyunpan: No such file or directory。

**Comment by xiaoyaofenfen** [comment]
> > linux的版本你用linux的命令就行，例如用apt安装的就用apt卸载，用yum安装的就用yum卸载
> 
> 谢谢，我刚刚卸载成功了。卸载又遇到问题了，我无法通过直接下载本地来进行安装也就是通过这个方式：wget https://github.com/tickstep/aliyunpan/releases/download/v0.3.4/aliyunpan-v0.3.4-linux-amd64.zip unzip aliyunpan-v0.3.4-linux-amd64.zip cd aliyunpan-v0.3.4-linux-amd64 ./aliyunpan。我通过这种方式，输入./aliyunpan他会直接跳转到阿里云盘，而不会显示安装。并且我在bash终端输入aliyunpan后他会提示bash: /usr/local/bin/aliyunpan: No such file or directory。

1）zip安装包是得使用这个./aliyunpan方式启动，代表执行当前目录的文件。你要直接输入aliyunpan就启动那得增加路径到PATH变量
2）可以直接删除这个旧的链接文件：rm -f /usr/local/bin/aliyunpan

**Comment by JordanSeaGold** [comment]
谢谢，我明白了
