### ISSUE TITLE
下载更新文件发生错误: Get "https://github.com/tickstep/aliyunpan/releases/download/v0.3.4/aliyunpan-v0.3.4-linux-amd64.zip": dial tcp 20.205.243.166:443: connect: connection timed out

### ISSUE THREAD

**Issue by JordanSeaGold** [tickstep/aliyunpan#458]
下载更新文件发生错误: Get "https://github.com/tickstep/aliyunpan/releases/download/v0.3.4/aliyunpan-v0.3.4-linux-amd64.zip": dial tcp 20.205.243.166:443: connect: connection timed out,
大大们，能搞个镜像源下载更新吗，服务器上无法搞梯子，下载不了最新版呀

**Comment by xiaoyaofenfen** [comment]
不好搞，没有这种文件服务器（主要是贵）。手动更新吧
