### ISSUE TITLE
多进程同时download比较慢

### ISSUE THREAD

**Issue by lyxcc127** [tickstep/aliyunpan#470]
我在服务器开了2个进程去云端download的时候，感觉好像两个进程会等待，有什么办法解决吗

**Comment by xiaoyaofenfen** [comment]
是的，多进程下载并没有什么用，因为阿里官方那边限制了并发只有3，不管是单个进程还是几个进程的，加起来不能超过3，反而多开了进程之后因为会有出现相互竞争的情况，可能还更慢了。你要想下载快只有两条路，第1条路开三方的权益包速度就快了，第2条路可以用多用户联合下载。

**Comment by lyxcc127** [comment]
> 是的，多进程下载并没有什么用，因为阿里官方那边限制了并发只有3，不管是单个进程还是几个进程的，加起来不能超过3，反而多开了进程之后因为会有出现相互竞争的情况，可能还更慢了。你要想下载快只有两条路，第1条路开三方的权益包速度就快了，第2条路可以用多用户联合下载。

多用户联合下载是什么意思

**Comment by xiaoyaofenfen** [comment]
> > 是的，多进程下载并没有什么用，因为阿里官方那边限制了并发只有3，不管是单个进程还是几个进程的，加起来不能超过3，反而多开了进程之后因为会有出现相互竞争的情况，可能还更慢了。你要想下载快只有两条路，第1条路开三方的权益包速度就快了，第2条路可以用多用户联合下载。
> 
> 多用户联合下载是什么意思

文档：https://github.com/tickstep/aliyunpan/blob/main/docs/manual.md#%E5%A4%9A%E7%94%A8%E6%88%B7%E8%81%94%E5%90%88%E4%B8%8B%E8%BD%BD
要快的话还是得开三方权益

**Comment by lyxcc127** [comment]
> > > 是的，多进程下载并没有什么用，因为阿里官方那边限制了并发只有3，不管是单个进程还是几个进程的，加起来不能超过3，反而多开了进程之后因为会有出现相互竞争的情况，可能还更慢了。你要想下载快只有两条路，第1条路开三方的权益包速度就快了，第2条路可以用多用户联合下载。
> > 
> > 
> > 多用户联合下载是什么意思
> 
> 文档：https://github.com/tickstep/aliyunpan/blob/main/docs/manual.md#%E5%A4%9A%E7%94%A8%E6%88%B7%E8%81%94%E5%90%88%E4%B8%8B%E8%BD%BD 要快的话还是得开三方权益

好的感谢
