### ISSUE TITLE
Linux端上传大文件（20GB）失败

### ISSUE THREAD

**Issue by Guangqi-He** [tickstep/aliyunpan#5]
我用的0.02版amd64的Linux客户端，上传20G的文件出现以下报错
![image](https://user-images.githubusercontent.com/50493251/132269705-1a155b8e-5963-4657-8053-d994b330ccf2.png)
但是小文件可以正常上传
![image](https://user-images.githubusercontent.com/50493251/132269730-9b4ffa9e-ee91-476a-9755-639664622a22.png)

**Comment by xiaoyaofenfen** [comment]
> 我用的0.02版amd64的Linux客户端，上传20G的文件出现以下报错
> ![image](https://user-images.githubusercontent.com/50493251/132269705-1a155b8e-5963-4657-8053-d994b330ccf2.png)
> 但是小文件可以正常上传
> ![image](https://user-images.githubusercontent.com/50493251/132269730-9b4ffa9e-ee91-476a-9755-639664622a22.png)

大文件在上传的时候使用bs参数指定一下分片大小，改大点，例如：
upload -bs 8192 /home/hgq/workdir/pedigree/04.VarCalling/R01_R10.g.vcf.gz /data

**Comment by Guangqi-He** [comment]
谢谢您，已成功上传！
![image](https://user-images.githubusercontent.com/50493251/132299839-aa6f78b7-a65a-4506-89ef-7c545066244d.png)
