### ISSUE TITLE
Docker-Compose安装，如何切换到相册网盘？

### ISSUE THREAD

**Issue by sonce** [tickstep/aliyunpan#50]
> 切换网盘
> 程序默认工作在文件网盘下，如需切换到相册网盘，可以使用本命令进行切换。
>
> aliyunpan drive <driveId>
> aliyunpan drive
>
>输入要切换的网盘 # 值 > 

WebDav挂载显示的文件网盘。能切换到相册网盘吗？

**Comment by tickstep** [comment]
现在还不支持
