### ISSUE TITLE
建议添加上传限速功能

### ISSUE THREAD

**Issue by CarmJos** [tickstep/aliyunpan#51]
针对部分较低带宽的服务器，使用上传或备份功能时存在阻塞上传通道而影响其他服务的情况。

建议为上传、下载功能添加限制最高速度的参数。

**Comment by xiaoyaofenfen** [comment]
这个有的，直接configs设置即可
config set -max_download_rate 10KB
config set -max_upload_rate10KB

**Comment by CarmJos** [comment]
好的，谢谢！
