### ISSUE TITLE
大佬建议增加触发服务器端视频转码的功能

### ISSUE THREAD

**Issue by PHCSJC** [tickstep/aliyunpan#53]
打个比方，我上传了一个新的视频文件（没有秒传），此时打开阿里云盘app去观看这个视频，再随意拖动一个进度，会发现卡住了，要等10几秒才能播放，原因是这个视频正在服务器端转码，要等待转码完成才能继续播放。

服务器端大概要10分钟左右可以把视频转码完成，此时再随意拖动进度会发现非常快。

简单说就是新上传的视频服务器端不会自动转码，只有点过播放才会转码，所以大佬能否增加一个触发服务器端转码的功能？

**Comment by xiaoyaofenfen** [comment]
一般是什么格式的视频使用转码？

**Comment by PHCSJC** [comment]
@xiaoyaofenfen 我用的最多的是mp4，其实任意格式的视频上传到阿里云盘后，在阿里云盘app观看视频，都是看的转码后的（后台自己转码，用户无感），不是直接看的原画。

**Comment by xiaoyaofenfen** [comment]
已增加，下个版本合入。

**Comment by PHCSJC** [comment]
已经测试，的确可以了，非常感谢！大佬v587！
