### ISSUE TITLE
backup大量文件时会报错

### ISSUE THREAD

**Issue by AsakuraFuuko** [tickstep/aliyunpan#55]
指令是这个 backup --sync -p 5 Z:/game/NS /Games
好像delete不会

> aliyunpan:/ Fuuko$ panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x0 pc=0xeedde0]
> 
> goroutine 14 [running]:
> github.com/tickstep/aliyunpan/internal/functions/panupload.(*boltDB).Next(0xc0001c1410, 0xc00030d8a0, 0x9, 0x0, 0x0, 0x0)
>         G:/aliyunpan/internal/functions/panupload/sync_database_bolt.go:149 +0x460
> github.com/tickstep/aliyunpan/internal/functions/panupload.(*boltDB).clean(0xc0001c1410, 0x0)
>         G:/aliyunpan/internal/functions/panupload/sync_database_bolt.go:89 +0x199
> github.com/tickstep/aliyunpan/internal/functions/panupload.(*boltDB).Close(0xc0001c1410, 0x0, 0x0)
>         G:/aliyunpan/internal/functions/panupload/sync_database_bolt.go:179 +0x50
> github.com/tickstep/aliyunpan/internal/command.DelRemoteFileFromDB(0xc00030d560, 0x6, 0xc00030d830, 0xa, 0xc00030d8a0, 0x9, 0x1)
>         G:/aliyunpan/internal/command/backup.go:218 +0x967
> github.com/tickstep/aliyunpan/internal/command.Backup.func1(0xc00030d820, 0xc000300001, 0xc000391ce0, 0xc00030d250, 0x6, 0xc0003a54b8, 0xc00030d240, 0xa)
>         G:/aliyunpan/internal/command/backup.go:285 +0x329
> created by github.com/tickstep/aliyunpan/internal/command.Backup
>         G:/aliyunpan/internal/command/backup.go:279 +0x70e

**Comment by xiaoyaofenfen** [comment]
初步看是备份数据库文件访问失败了，能不能开下debug日志看看

**Comment by xiaoyaofenfen** [comment]
这个大量预计是多少个文件，在哪个数量级，1000? 2000?

**Comment by AsakuraFuuko** [comment]
大概2600多，开过debug没什么有用的信息
是不是因为被上传的文件夹是用samba共享的问题？

**Comment by AsakuraFuuko** [comment]
![828A7A8D-F0BC-4388-830A-C817F967424C](https://user-images.githubusercontent.com/3427282/153711153-a4d84947-9c58-4654-a2b3-ead269a533be.png)

**Comment by AsakuraFuuko** [comment]
刷到这个data是nil就报错了

**Comment by ranshuo-ICer** [comment]
我也有这个问题，现在还没解决吗

**Comment by tickstep** [comment]
可以试试v0.1.6 版本的sync命令，看是否可以解决
