### ISSUE TITLE
问下上传默认的并发量是多少？

### ISSUE THREAD

**Issue by 362227** [tickstep/aliyunpan#59]
问下上传单文件并发量是多少？能不能自定义？
类似这个max_upload_parallel  https://github.com/qjfoidnh/BaiduPCS-Go

**Comment by tickstep** [comment]
> 问下上传单文件并发量是多少？能不能自定义？
> 
> 类似这个max_upload_parallel  https://github.com/qjfoidnh/BaiduPCS-Go

默认是10吧，你可以通过config去自行更改

**Comment by 362227** [comment]
> > 问下上传单文件并发量是多少？能不能自定义？
> > 类似这个max_upload_parallel  https://github.com/qjfoidnh/BaiduPCS-Go
> 
> 默认是10吧，你可以通过config去自行更改

我看说明怎么说的是“最大上传并发量，即同时上传文件最大数量 "
不是我想的单文件上传并发量，无法提升上传速度。我用BaiduPCS-Go，把这个提高可以显著改善上传速度

**Comment by tickstep** [comment]
> > > 问下上传单文件并发量是多少？能不能自定义？
> 
> > > 类似这个max_upload_parallel  https://github.com/qjfoidnh/BaiduPCS-Go
> 
> > 
> 
> > 默认是10吧，你可以通过config去自行更改
> 
> 
> 
> 我看说明怎么说的是“最大上传并发量，**即同时上传文件最大数量** "
> 
> 不是我想的单文件上传并发量，无法提升上传速度。我用BaiduPCS-Go，把这个提高可以显著改善上传速度

这个不一样了，百度网盘可以一个文件同时多个分片上传所以可以这样搞，但是阿里云盘不行，阿里只能一个分片一个分片按序上传，单个文件最大上传速度再20mb，所以只能多个文件同时上传而不能单个文件多线上传
