### ISSUE TITLE
backup出错

### ISSUE THREAD

**Issue by www18dev** [tickstep/aliyunpan#60]
./aliyunpan backup -sync /hd/downloads/incomplete /aliyuncli 
同步数据库打开失败！ timeout

[0] 当前文件上传最大并发量为: 10, 上传分片大小为: 10.00MB
/hd/downloads/incomplete 同步数据库打开失败,跳过该目录的备份 timeout

上传结束, 时间: 5秒, 数据总量: 0B

**Comment by tickstep** [comment]
可以试试v0.1.6 版本的sync命令进行备份
