### ISSUE TITLE
同步本地目录到阿里云盘，命令是aliyunpan backup -exn "^\." -p 5 --norapid --ow --sync ${SOURCE_DIR} ${TARGET_DIR}，提示以下文件上传失败:

### ISSUE THREAD

**Issue by huangjianye** [tickstep/aliyunpan#75]
![image](https://user-images.githubusercontent.com/49425015/161375867-b2b40507-59e9-4d37-8df9-127e47e75033.png)

**Comment by tickstep** [comment]
可以试试v0.1.6 版本的sync命令
