### ISSUE TITLE
在终端中可以正常运行，但在crontab的定时任务中运行时会出现panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by huangjianye** [tickstep/aliyunpan#76]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x220 pc=0x8dcb56]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/command.parseDriveId(0xc0000a6dc0, 0x2, 0xc000304420)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/command.go:70 +0x36
github.com/tickstep/aliyunpan/internal/command.Backup(0xc0000a6dc0, 0xdb2160, 0xc000095ca0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/backup.go:268 +0x215
github.com/urfave/cli.HandleAction(0x953fc0, 0xa311b8, 0xc0000a6dc0, 0xc0000a6dc0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x105
github.com/urfave/cli.Command.Run(0xa05727, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa0fe78, 0x15, 0xa25c22, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc000160380, 0xc00001e0c0, 0xc, 0xc, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x7e8
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:618 +0x187e

**Comment by tickstep** [comment]
crontob 完整的命令发来看看

**Comment by huangjianye** [comment]
02 13 * * * /bin/bash /root/.script/sync_file_to_ali.sh



---原始邮件---
发件人: "tickstep studio ***@***.***&gt;
发送时间: 2022年4月3日(周日) 晚上11:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tickstep/aliyunpan] 在终端中可以正常运行，但在crontab的定时任务中运行时会出现panic: runtime error: invalid memory address or nil pointer dereference (Issue #76)




 
crontob 完整的命令发来看看

**Comment by huangjianye** [comment]
关于这个问题，哪位大佬交流一下你们的定时备份任务是怎么配置成功的，我用的是centos7.6，环境变量需要做什么特殊配置吗？希望大佬能指导一下，谢谢了！

**Comment by baoqihui** [comment]
> 
可以直接用
https://github.com/baoqihui/script/blob/main/backup-ali.sh

**Comment by zhangyinyuan** [comment]
请问要怎么解决, 我也遇到了这个问题, 尝试了不同的版本, 发现的都存在这个问题

**Comment by zhangyinyuan** [comment]
> 关于这个问题，哪位大佬交流一下你们的定时备份任务是怎么配置成功的，我用的是centos7.6，环境变量需要做什么特殊配置吗？希望大佬能指导一下，谢谢了！

你好, 请问是怎么解决的 ?

**Comment by huangjianye** [comment]
> > 关于这个问题，哪位大佬交流一下你们的定时备份任务是怎么配置成功的，我用的是centos7.6，环境变量需要做什么特殊配置吗？希望大佬能指导一下，谢谢了！
> 
> 你好, 请问是怎么解决的 ?

我是在脚本里面加了这句 . /etc/profile 就不报错了，你可以试试！
