### ISSUE TITLE
图片文件会进行数据修改？

### ISSUE THREAD

**Issue by zhendery** [tickstep/aliyunpan#78]
阿里网盘里的图片文件，用网盘客户端下载下来是正常的，可是用webdav就不正常，打开显示文件被截断，缩略图预览底下一部分失效了。
右键查看文件属性是一样的，文件大小和占用空间**一模一样**。但md5是**不一样**的，通过ultraEdit查看二进制可以看到文件除了文件头部分，后面的数据也是**完全不一样**的，利用beyondCompare对比也是一样的结论。
以下是图片文件的一些对比：
![对比](https://user-images.githubusercontent.com/13639590/161569266-be0a9f3d-7c95-403e-a335-649058d643a4.jpg)
以下分别是原图和webdav里的图：
![原文件](https://user-images.githubusercontent.com/13639590/161565143-f66ece92-4a40-499b-a097-b4669f2097be.jpg)
![webdav](https://user-images.githubusercontent.com/13639590/161565094-ec2d8160-172f-4696-8577-3461759bf1a9.jpg)

另外我又对比了一些其他格式的文件，发现只有图片格式的文件数据会被修改。
虽然不少图片文件的数据被修改后仍然显示正常，但也有不小的一部分图就坏了（通过网盘网页版和客户端查看下载都是正常的，只有webdav有问题）
![对比2](https://user-images.githubusercontent.com/13639590/161571782-f39998ef-b3c7-465d-bea2-925fdfdf49b3.jpg)

因此想来问问看，是会对图片文件进行数据修改吗？如果是为了压缩大小我还能理解，但是文件大小完全没变，只是把内容改坏了我不是很理解....

**Comment by tickstep** [comment]
这个不会，应该是bug，怀疑是webdav断点续传得问题，部分数据没下载对。你webdav用的是什么客户端？

**Comment by zhendery** [comment]
> 这个不会，应该是bug，怀疑是webdav断点续传得问题，部分数据没下载对。你webdav用的是什么客户端？

很怪，我测试了**jpg**和**png**格式的文件都会这样，虽然有的图片被修改后显示正常。
我在windows里用aliyunpan-v0.1.3-windows-**x64**，然后用RaiDrive挂载为网络磁盘，在win自带的**资源管理器**里，以及win版的**kodi**里，这张图都是坏的。
在Debian里用aliyunpan-v0.1.3-linux-**amd64**和在Armbian里用aliyunpan-v0.1.3-linux-**arm64**，然后在win版和android版的**kodi**里连接webdav，也都是这样。
因此我认为和webdav的客户端应该是没关系，或者webdav协议本身就有这样的问题/优化。

**Comment by zhendery** [comment]
> 这个不会，应该是bug，怀疑是webdav断点续传得问题，部分数据没下载对。你webdav用的是什么客户端？

另外我用了另一个webdav的项目测试了也是这样，我怀疑是webdav本身的问题，或者是阿里云盘的问题。
那个项目：https://github.com/messense/aliyundrive-webdav/discussions/372#discussioncomment-2512557

**Comment by tickstep** [comment]
> > 这个不会，应该是bug，怀疑是webdav断点续传得问题，部分数据没下载对。你webdav用的是什么客户端？
> 
> 
> 
> 另外我用了另一个webdav的项目测试了也是这样，我怀疑是webdav本身的问题，或者是阿里云盘的问题。
> 
> 那个项目：https://github.com/messense/aliyundrive-webdav/discussions/372#discussioncomment-2512557

有空我也去看下

**Comment by cn4** [comment]
我也测试了，本项目应该无问题，猜测楼主可能是两个项目用了相同地址和端口，然后浏览器缓存没刷新。

**Comment by zhendery** [comment]
> 

是真的！这个项目我换了个端口就好了！

**Comment by zhendery** [comment]
> 我也测试了，本项目应该无问题，猜测楼主可能是两个项目用了相同地址和端口，然后浏览器缓存没刷新。

是真的！这个项目我换了个端口就好了！
