### ISSUE TITLE
什么命令可以指定下载某个目录下的所有文件到本地的某个目录下？而不是克隆整个目录路径

### ISSUE THREAD

**Issue by baoqihui** [tickstep/aliyunpan#79]
如下图：我想将网盘的 `/Backup/config` 目录下的所有文件直接下载到 `/opt/config` 目录下，但我尝试后都将存到`/opt/config/Backup/config/redis.conf` 下；不可以直接指定吗？

![image](https://user-images.githubusercontent.com/50536515/162409632-3e4e1c20-d97b-4b30-b50e-6fa0d67a4025.png)

**Comment by baoqihui** [comment]
我尝试过的命令有 `./aliyunpan d /Backup/config/ --saveto /opt/config/`

**Comment by baoqihui** [comment]
因为我的目录可能有多层，比如备份了 /opt下的所有文件，我想恢复 /opt下所有文件或目录到原来位置，就不知道如何做了

**Comment by huangjianye** [comment]
> 因为我的目录可能有多层，比如备份了 /opt下的所有文件，我想恢复 /opt下所有文件或目录到原来位置，就不知道如何做了

你可以先打包压缩，在上传备份。这样下载下来再解压不就行了吗？这样应该能解决你的需求，只是多了压缩和解压的步骤。

**Comment by baoqihui** [comment]
> > 因为我的目录可能有多层，比如备份了 /opt下的所有文件，我想恢复 /opt下所有文件或目录到原来位置，就不知道如何做了
> 
> 你可以先打包压缩，在上传备份。这样下载下来再解压不就行了吗？这样应该能解决你的需求，只是多了压缩和解压的步骤。

谢谢你的回复，我已经接收建议并将个人的备份，恢复整合为脚本

**Comment by baoqihui** [comment]
已经采纳建议使用zip打包后上传，也写了恢复脚本，有需要的朋友可以来看看顺便点个stars：https://github.com/baoqihui/script
![image](https://user-images.githubusercontent.com/50536515/162560631-106b5b33-97e3-45d8-b619-0caa1688e314.png)

**Comment by tickstep** [comment]
v0.1.6版本的JS插件应该可以做到
