### ISSUE TITLE
有计划增加支持相薄功能吗？

### ISSUE THREAD

**Issue by wuxiao2522** [tickstep/aliyunpan#80]

**Comment by wuxiao2522** [comment]
用此工具在相册里面增加文件夹，网页和手机的官方端都是看不见的。而相薄不支持的话，相册照片无法分类，ls反应也超慢。

**Comment by tickstep** [comment]
> 用此工具在相册里面增加文件夹，网页和手机的官方端都是看不见的。而相薄不支持的话，相册照片无法分类，ls反应也超慢。

好的，我抽时间排着做下

**Comment by tickstep** [comment]
0.1.5版本已经做了基本功能的支持，后续再完善了

**Comment by wuxiao2522** [comment]
感谢大佬！！！

**Comment by tickstep** [comment]
> 感谢大佬！！！

这个还是beta版，还不算完善。你也可以把体验说下，我准备收集了看看有没有更好的设计方式。
