### ISSUE TITLE
关于备份目录功能占用大量运行内存问题

### ISSUE THREAD

**Issue by AMGL07** [tickstep/aliyunpan#84]
# 描述
在备份几TB大容量硬盘时遇到问题，运行内存占用率越来越大。不得不强行停止程序，强行停止程序后发现同步数据库损坏，无法进行下次备份。
# 希望增加
1. 任务管理
2. 回收内存

**Comment by labolado** [comment]
遇到了同样的问题，目录下有大量小文件，从来没有备份成功过，运行一段时间就会被系统(centos8)自动kill掉，说是outofmemory。

**Comment by tickstep** [comment]
可以试试v0.1.6 版本的sync命令
