### ISSUE TITLE
大佬可不可以做一个清除分片的操作

### ISSUE THREAD

**Issue by XKN217** [tickstep/aliyunpan#90]
我在同时上传两个文件的时候发生了错误，重新上传不成功，Debug显示分片错误，导致这两个文件无法上传。有什么解决的办法吗，本人菜鸟一枚。
![07354F24-C4C5-49a1-9B7F-9331AD145504](https://user-images.githubusercontent.com/70200704/169071846-fc9ca32c-188f-4824-a132-afddd87ef062.png)
![D5402473-DDB7-4a55-A2A0-C02E780E3738](https://user-images.githubusercontent.com/70200704/169071899-f3241130-88c3-439f-a032-94e0246e4727.png)

**Comment by tickstep** [comment]
v0.1.6版本已修复
