### ISSUE TITLE
使用洛杉矶VPS登陆失败

### ISSUE THREAD

**Issue by lovechang1986** [tickstep/aliyunpan#92]
使用一台洛杉矶VPS，一直登陆失败如何破。。。
```
[2022-5-20 16:50:59.002] do request url: https://auth.aliyundrive.com/v2/account/token
[2022-5-20 16:51:01.592] get access token error  Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: no route to host
Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: no route to host
登录失败
```

**Comment by ALixuhui** [comment]
+1

**Comment by tickstep** [comment]
你这台机器是不是只有ipv6？

**Comment by lovechang1986** [comment]
![image](https://user-images.githubusercontent.com/8605164/171310828-ac06d991-fae5-49d5-a60f-842a4b42d9ed.png)
并没有呢，只有一个IP4v4的地址。
另外这台VPS之前使用aliyunpan登陆过，也设置了间隔1小时更新refresh_token的crontab，但后来不知道怎么还是过期了。
目前使用refresh_token和二维码登陆都不行，但是使用另外一个github的库(alidrive-uploader)却可以正常登陆和上传，因为alidrive-uploader没有sync功能，所以还是希望用aliyunpan...

**Comment by lovechang1986** [comment]
能帮看看啥问题吗？

**Comment by tickstep** [comment]
> 能帮看看啥问题吗？

绑定ipv4地址试试

config set -local_addrs 127.0.0.1(换成你自己服务器的Ipv4地址)

**Comment by huangwb8** [comment]
我也有这个问题。我的Racknerd VPS，也是在洛杉矶。不过，我还套了Cloudflare的CDN，不知道这个是否有影响。我用Docker版却可以成功。总之有点奇怪。。。

**Comment by tickstep** [comment]
> 我也有这个问题。我的Racknerd VPS，也是在洛杉矶。不过，我还套了Cloudflare的CDN，不知道这个是否有影响。我用Docker版却可以成功。总之有点奇怪。。。

这有点奇怪，如果docker可以就不是网络的问题，你有试过绑定eth0网卡吗，config可以绑定

**Comment by huangwb8** [comment]
@tickstep 感谢大佬回复!
我的应用场景是Docker Duplicati 联合aliyunpan-WebDav进行远程备份。我发现aliyunpan-WebDav，无论Docker还是原生的安装方法吧，总是不稳定，即有一段时间可以用，有一段时间aliyunpan-WebDav就自己掉线了。不知您有没有什么建议？

**Comment by huangwb8** [comment]
@tickstep 

我用WebDav主要是因为Duplicati支持的标准协议之一是WebDav。。。哎(～￣▽￣)～ 

![image](https://user-images.githubusercontent.com/35643122/177166359-8fe1f43f-b5b7-49cf-b995-58b412bfa940.png)

**Comment by tickstep** [comment]
> @tickstep 
> 
> 
> 
> 我用WebDav主要是因为Duplicati支持的标准协议之一是WebDav。。。哎(～￣▽￣)～ 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/35643122/177166359-8fe1f43f-b5b7-49cf-b995-58b412bfa940.png)
> 
> 

你帮忙抓下debug日志，我看能不能改善一下。readme文件有教程怎么开debug日志

**Comment by huangwb8** [comment]
> 

OK，我以后有遇到的时候看一下

**Comment by huangwb8** [comment]
> > 能帮看看啥问题吗？
> 
> 绑定ipv4地址试试
> 
> config set -local_addrs 127.0.0.1(换成你自己服务器的Ipv4地址)

这样做会有新的报错：

```

Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": dial tcp 127.0.0.1:0->[2408:4001:1000::4]:443: connect: address family not supported by protocol
登录失败

```

**Comment by tickstep** [comment]
> > > 能帮看看啥问题吗？
> > 
> > 
> > 绑定ipv4地址试试
> > config set -local_addrs 127.0.0.1(换成你自己服务器的Ipv4地址)
> 
> 这样做会有新的报错：
> 
> ```
> 
> Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": dial tcp 127.0.0.1:0->[2408:4001:1000::4]:443: connect: address family not supported by protocol
> 登录失败
> ```

在服务器运行trace命令，贴上来看看

traceroute auth.aliyundrive.com

**Comment by huangwb8** [comment]
@tickstep 谢谢大佬关心，我后面直接用docker镜像成功了，所以就没有管它了

**Comment by huangwb8** [comment]
在Duplicati里使用aliyun-Webdav时，偶尔会出现这种报错：
![image](https://user-images.githubusercontent.com/35643122/179396769-b29d76a8-5623-42d4-ae9b-ad6467db3fd5.png)
用Google Drive、OneDrive的时候不会出现，不知道为啥 (￣△￣；)

**Comment by huangwb8** [comment]
> traceroute auth.aliyundrive.com

@tickstep 输出如下：

traceroute to auth.aliyundrive.com (47.92.21.245), 30 hops max, 60 byte packets
 1  unassigned.calpop.com (216.240.140.65)  2.080 ms  2.026 ms  2.004 ms
 2  multacom.com (96.45.162.9)  1.985 ms  1.968 ms  1.944 ms
 3  182.54.129.90 (182.54.129.90)  1.910 ms  1.877 ms  1.854 ms
 4  10.31.0.238 (10.31.0.238)  8.816 ms  8.778 ms  8.755 ms
 5  219.158.33.77 (219.158.33.77)  11.859 ms  11.855 ms  11.828 ms
 6  219.158.96.37 (219.158.96.37)  154.809 ms  158.670 ms  158.620 ms
 7  219.158.16.65 (219.158.16.65)  155.786 ms  155.777 ms  155.783 ms
 8  219.158.5.149 (219.158.5.149)  158.625 ms  158.588 ms  158.549 ms
 9  125.33.186.194 (125.33.186.194)  153.761 ms 124.65.194.18 (124.65.194.18)  156.138 ms  156.126 ms
10  * * 125.33.185.110 (125.33.185.110)  153.612 ms
11  * 61.49.143.134 (61.49.143.134)  156.794 ms *
12  * * *
13  119.38.212.81 (119.38.212.81)  168.042 ms * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *

**Comment by 1059841705** [comment]
> Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: connection timed out 登录失败
> 
> 改ip之后 connect: address family not supported by protocol 登录失败
> 
> 而且我docker的webdav能用，sync的却一直在重启

CONTAINER ID   IMAGE                                  COMMAND                 CREATED          STATUS                          PORTS     NAMES
16c7ba0a4fa5   tickstep/aliyunpan-sync:v0.1.8-amd64   "/bin/sh -c ./app.sh"   22 minutes ago   Restarting (2) 48 seconds ago             aliyunpan-sync

**Comment by tickstep** [comment]
> Token登录失败： Post "https://auth.aliyundrive.com/v2/account/token": dial tcp [2408:4001:1000::4]:443: connect: connection timed out
> 
> 登录失败
> 
> 
> 
> 改ip之后
> 
> connect: address family not supported by protocol
> 
> 登录失败
> 
> 
> 
> 而且我docker的webdav能用，sync的却一直在重启

这个现象是因为你这个aliyunpan工具用了ipv6的链路，但是这个工具当前还没有适配ipv6，它只能用ipv4。(>﹏<)

**Comment by lovechang1986** [comment]
我ping了一下登陆的443端口，发现IPv6的无法连接，但是IPv4的就可以连接，信息如下：
```
(base) [root@tt01 alis]# telnet auth.aliyundrive.com 443
Trying 2408:4001:1000::4...
telnet: connect to address 2408:4001:1000::4: No route to host
Trying 47.92.21.245...
Connected to auth.aliyundrive.com.
Escape character is '^]'.
```

不过根据我购买的VPS信息是不包含IPv6的，不知道为什么首先要连接IPv6，有没有办法只使用IPv4的链路？还是说这个是由VPS供应商负责解决?

**Comment by lovechang1986** [comment]
解决，关闭问题。
由于是无法使用ipv6登录，因此强制使用ipv4即可。操作参考如下(网址)[https://www.thegeekdiary.com/centos-rhel-7-how-to-disable-ipv6/]。

**Comment by kuangxiaoye** [comment]
> 解决，关闭问题。 由于是无法使用ipv6登录，因此强制使用ipv4即可。操作参考如下[网址](https://www.thegeekdiary.com/centos-rhel-7-how-to-disable-ipv6/)。

According to method 2 in the URL, it has been solved smoothly, and there is no need to restart or download.
